var annotated_dup =
[
    [ "_ByteOrderChangeData", "struct__ByteOrderChangeData.html", "struct__ByteOrderChangeData" ],
    [ "_ExifContent", "struct__ExifContent.html", "struct__ExifContent" ],
    [ "_ExifContentPrivate", "struct__ExifContentPrivate.html", "struct__ExifContentPrivate" ],
    [ "_ExifData", "struct__ExifData.html", "struct__ExifData" ],
    [ "_ExifDataPrivate", "struct__ExifDataPrivate.html", "struct__ExifDataPrivate" ],
    [ "_ExifEntry", "struct__ExifEntry.html", "struct__ExifEntry" ],
    [ "_ExifEntryPrivate", "struct__ExifEntryPrivate.html", "struct__ExifEntryPrivate" ],
    [ "_ExifLoader", "struct__ExifLoader.html", "struct__ExifLoader" ],
    [ "_ExifLog", "struct__ExifLog.html", "struct__ExifLog" ],
    [ "_ExifMem", "struct__ExifMem.html", "struct__ExifMem" ],
    [ "_ExifMnoteData", "struct__ExifMnoteData.html", "struct__ExifMnoteData" ],
    [ "_ExifMnoteDataCanon", "struct__ExifMnoteDataCanon.html", "struct__ExifMnoteDataCanon" ],
    [ "_ExifMnoteDataFuji", "struct__ExifMnoteDataFuji.html", "struct__ExifMnoteDataFuji" ],
    [ "_ExifMnoteDataMethods", "struct__ExifMnoteDataMethods.html", "struct__ExifMnoteDataMethods" ],
    [ "_ExifMnoteDataOlympus", "struct__ExifMnoteDataOlympus.html", "struct__ExifMnoteDataOlympus" ],
    [ "_ExifMnoteDataPentax", "struct__ExifMnoteDataPentax.html", "struct__ExifMnoteDataPentax" ],
    [ "_ExifMnoteDataPriv", "struct__ExifMnoteDataPriv.html", "struct__ExifMnoteDataPriv" ],
    [ "_MnoteCanonEntry", "struct__MnoteCanonEntry.html", "struct__MnoteCanonEntry" ],
    [ "_MNoteFujiDataPrivate", "struct__MNoteFujiDataPrivate.html", "struct__MNoteFujiDataPrivate" ],
    [ "_MnoteFujiEntry", "struct__MnoteFujiEntry.html", "struct__MnoteFujiEntry" ],
    [ "_MnoteOlympusEntry", "struct__MnoteOlympusEntry.html", "struct__MnoteOlympusEntry" ],
    [ "_MnotePentaxEntry", "struct__MnotePentaxEntry.html", "struct__MnotePentaxEntry" ],
    [ "_testcase", "struct__testcase.html", "struct__testcase" ],
    [ "canon_entry_table_t", "structcanon__entry__table__t.html", "structcanon__entry__table__t" ],
    [ "ExifRational", "structExifRational.html", "structExifRational" ],
    [ "ExifSRational", "structExifSRational.html", "structExifSRational" ],
    [ "TagEntry", "structTagEntry.html", "structTagEntry" ],
    [ "TestCase", "structTestCase.html", "structTestCase" ]
];