EXIF library (libexif) Internals: libexif/exif-ifd.h File Reference
exif-ifd.h File Reference
Enumerations
enum ExifIfd {
EXIF_IFD_0 = 0 , EXIF_IFD_1 , EXIF_IFD_EXIF , EXIF_IFD_GPS ,
EXIF_IFD_INTEROPERABILITY , EXIF_IFD_COUNT
}
Possible EXIF Image File Directories.
Functions
const char * exif_ifd_get_name (ExifIfd ifd)
Return a textual name of the given IFD.
Enumeration Type Documentation
ExifIfd
enum ExifIfd
Possible EXIF Image File Directories.
Enumerator
EXIF_IFD_0
EXIF_IFD_1
EXIF_IFD_EXIF
EXIF_IFD_GPS
EXIF_IFD_INTEROPERABILITY
EXIF_IFD_COUNT
Not a real value, just (max_value + 1).
Definition at line 29 of file exif-ifd.h.
Function Documentation
exif_ifd_get_name()
const char* exif_ifd_get_name (ExifIfd ifd)
Return a textual name of the given IFD.
The name is a short, unique, non-localized text string containing only US-ASCII alphanumeric characters.
Parameters
[in] ifd IFD
Returns
textual name of the IFD, or NULL if unknown
Definition at line 40 of file exif-ifd.c.
References ExifIfdTable, ifd, and name.
Referenced by exif_content_fix(), exif_data_dump(), exif_data_load_data_content(), exif_data_save_data_content(), and remove_not_recorded().
libexif Generated by