EXIF library (libexif) Internals: libexif/fuji/exif-mnote-data-fuji.h File Reference
exif-mnote-data-fuji.h File Reference
#include <libexif/exif-mnote-data.h>
#include <libexif/exif-mnote-data-priv.h>
#include <libexif/exif-data.h>
#include <libexif/fuji/mnote-fuji-entry.h>
Data Structures
struct _ExifMnoteDataFuji
Typedefs
typedef struct _ExifMnoteDataFuji ExifMnoteDataFuji
Functions
int exif_mnote_data_fuji_identify (const ExifData *ed, const ExifEntry *e)
Detect if MakerNote is recognized as one handled by the Fuji module.
ExifMnoteData * exif_mnote_data_fuji_new (ExifMem *)
Typedef Documentation
ExifMnoteDataFuji
typedef struct _ExifMnoteDataFuji ExifMnoteDataFuji
Definition at line 29 of file exif-mnote-data-fuji.h.
Function Documentation
exif_mnote_data_fuji_identify()
int exif_mnote_data_fuji_identify (const ExifData * ed, const ExifEntry * e)
Detect if MakerNote is recognized as one handled by the Fuji module.
Parameters
[in] ed image ExifData to identify as as a Fuji type
[in] e ExifEntry for EXIF_TAG_MAKER_NOTE, from within ed but duplicated here for convenience
Returns
0 if not recognized, nonzero if recognized. The specific nonzero value returned may identify a subtype unique within this module.
Definition at line 320 of file exif-mnote-data-fuji.c.
References _ExifEntry::data, and _ExifEntry::size.
Referenced by interpret_maker_note().
exif_mnote_data_fuji_new()
ExifMnoteData* exif_mnote_data_fuji_new (ExifMem *)
Definition at line 327 of file exif-mnote-data-fuji.c.
References _ExifMnoteDataMethods::count, exif_mem_alloc(), exif_mnote_data_construct(), exif_mnote_data_fuji_count(), exif_mnote_data_fuji_free(), exif_mnote_data_fuji_get_description(), exif_mnote_data_fuji_get_id(), exif_mnote_data_fuji_get_name(), exif_mnote_data_fuji_get_title(), exif_mnote_data_fuji_get_value(), exif_mnote_data_fuji_load(), exif_mnote_data_fuji_save(), exif_mnote_data_fuji_set_byte_order(), exif_mnote_data_fuji_set_offset(), _ExifMnoteDataMethods::free, _ExifMnoteDataMethods::get_description, _ExifMnoteDataMethods::get_id, _ExifMnoteDataMethods::get_name, _ExifMnoteDataMethods::get_title, _ExifMnoteDataMethods::get_value, _ExifMnoteDataMethods::load, _ExifMnoteData::methods, _ExifMnoteDataMethods::save, _ExifMnoteDataMethods::set_byte_order, and _ExifMnoteDataMethods::set_offset.
Referenced by interpret_maker_note().
libexif Generated by