EXIF library (libexif) Internals: libexif/apple/exif-mnote-data-apple.h File Reference
exif-mnote-data-apple.h File Reference
#include <libexif/exif-byte-order.h>
#include <libexif/exif-data.h>
#include <libexif/exif-mem.h>
#include <libexif/exif-mnote-data-priv.h>
#include <libexif/apple/mnote-apple-entry.h>
Data Structures
struct _ExifMnoteDataApple
Typedefs
typedef struct _ExifMnoteDataApple ExifMnoteDataApple
Functions
int exif_mnote_data_apple_identify (const ExifData *, const ExifEntry *)
ExifMnoteData * exif_mnote_data_apple_new (ExifMem *)
Typedef Documentation
ExifMnoteDataApple
typedef struct _ExifMnoteDataApple ExifMnoteDataApple
Definition at line 32 of file exif-mnote-data-apple.h.
Function Documentation
exif_mnote_data_apple_identify()
int exif_mnote_data_apple_identify (const ExifData * ed, const ExifEntry * e)
Definition at line 260 of file exif-mnote-data-apple.c.
References _ExifEntry::data, and _ExifEntry::size.
exif_mnote_data_apple_new()
ExifMnoteData * exif_mnote_data_apple_new (ExifMem * mem)
Definition at line 270 of file exif-mnote-data-apple.c.
References _ExifMnoteDataMethods::count, exif_mem_alloc(), exif_mnote_data_apple_count(), exif_mnote_data_apple_free(), exif_mnote_data_apple_get_description(), exif_mnote_data_apple_get_id(), exif_mnote_data_apple_get_name(), exif_mnote_data_apple_get_title(), exif_mnote_data_apple_get_value(), exif_mnote_data_apple_load(), exif_mnote_data_apple_set_byte_order(), exif_mnote_data_apple_set_offset(), exif_mnote_data_construct(), _ExifMnoteDataMethods::free, _ExifMnoteDataMethods::get_description, _ExifMnoteDataMethods::get_id, _ExifMnoteDataMethods::get_name, _ExifMnoteDataMethods::get_title, _ExifMnoteDataMethods::get_value, _ExifMnoteDataMethods::load, _ExifMnoteData::methods, _ExifMnoteDataMethods::set_byte_order, and _ExifMnoteDataMethods::set_offset.
libexif Generated by