EXIF library (libexif) Internals: libexif/exif-format.h File Reference
exif-format.h File Reference
Handling native EXIF data types.
Enumerations
enum ExifFormat {
EXIF_FORMAT_BYTE = 1 , EXIF_FORMAT_ASCII = 2 , EXIF_FORMAT_SHORT = 3 , EXIF_FORMAT_LONG = 4 ,
EXIF_FORMAT_RATIONAL = 5 , EXIF_FORMAT_SBYTE = 6 , EXIF_FORMAT_UNDEFINED = 7 , EXIF_FORMAT_SSHORT = 8 ,
EXIF_FORMAT_SLONG = 9 , EXIF_FORMAT_SRATIONAL = 10 , EXIF_FORMAT_FLOAT = 11 , EXIF_FORMAT_DOUBLE = 12
}
EXIF tag data formats.
Functions
const char * exif_format_get_name (ExifFormat format)
Return a textual representation of the given EXIF data type.
unsigned char exif_format_get_size (ExifFormat format)
Return the raw size of the given EXIF data type.
Detailed Description
Handling native EXIF data types.
Definition in file exif-format.h.
Enumeration Type Documentation
ExifFormat
enum ExifFormat
EXIF tag data formats.
Enumerator
EXIF_FORMAT_BYTE
EXIF_FORMAT_ASCII
EXIF_FORMAT_SHORT
EXIF_FORMAT_LONG
EXIF_FORMAT_RATIONAL
EXIF_FORMAT_SBYTE
EXIF_FORMAT_UNDEFINED
EXIF_FORMAT_SSHORT
EXIF_FORMAT_SLONG
EXIF_FORMAT_SRATIONAL
EXIF_FORMAT_FLOAT
EXIF_FORMAT_DOUBLE
Definition at line 34 of file exif-format.h.
Function Documentation
exif_format_get_name()
const char * exif_format_get_name (ExifFormat format)
Return a textual representation of the given EXIF data type.
Parameters
[in] format EXIF data format
Returns
localized textual name, or NULL if unknown
Definition at line 55 of file exif-format.c.
References _, bindtextdomain, ExifFormatTable, format, and name.
Referenced by content_foreach_func(), content_foreach_func(), content_foreach_func(), exif_entry_dump(), and exif_entry_fix().
exif_format_get_size()
unsigned char exif_format_get_size (ExifFormat format)
Return the raw size of the given EXIF data type.
Parameters
[in] format EXIF data format
Returns
size in bytes
Definition at line 68 of file exif-format.c.
References ExifFormatTable, and format.
Referenced by check_entry_format(), exif_array_set_byte_order(), exif_data_load_data_entry(), exif_data_save_data_entry(), exif_entry_fix(), exif_entry_format_value(), exif_entry_get_value(), exif_entry_initialize(), exif_entry_initialize_gps(), exif_mnote_data_apple_load(), exif_mnote_data_apple_set_byte_order(), exif_mnote_data_canon_load(), exif_mnote_data_canon_save(), exif_mnote_data_canon_set_byte_order(), exif_mnote_data_fuji_load(), exif_mnote_data_fuji_save(), exif_mnote_data_fuji_set_byte_order(), exif_mnote_data_olympus_load(), exif_mnote_data_olympus_save(), exif_mnote_data_olympus_set_byte_order(), exif_mnote_data_pentax_load(), exif_mnote_data_pentax_save(), exif_mnote_data_pentax_set_byte_order(), main(), and mnote_apple_entry_get_value().
libexif Generated by