EXIF library (libexif) Internals: libexif/apple/exif-mnote-data-apple.c File Reference
exif-mnote-data-apple.c File Reference
#include <config.h>
#include "exif-mnote-data-apple.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libexif/exif-data.h>
#include <libexif/exif-utils.h>
Functions
static void exif_mnote_data_apple_free (ExifMnoteData *md)
static void exif_mnote_data_apple_load (ExifMnoteData *md, const unsigned char *buf, unsigned int buf_size)
static void exif_mnote_data_apple_set_offset (ExifMnoteData *md, unsigned int o)
static void exif_mnote_data_apple_set_byte_order (ExifMnoteData *md, ExifByteOrder o)
static unsigned int exif_mnote_data_apple_count (ExifMnoteData *md)
static unsigned int exif_mnote_data_apple_get_id (ExifMnoteData *md, unsigned int i)
static const char * exif_mnote_data_apple_get_name (ExifMnoteData *md, unsigned int i)
static const char * exif_mnote_data_apple_get_title (ExifMnoteData *md, unsigned int i)
static const char * exif_mnote_data_apple_get_description (ExifMnoteData *md, unsigned int i)
static char * exif_mnote_data_apple_get_value (ExifMnoteData *md, unsigned int i, char *val, unsigned int maxlen)
int exif_mnote_data_apple_identify (const ExifData *ed, const ExifEntry *e)
ExifMnoteData * exif_mnote_data_apple_new (ExifMem *mem)
Function Documentation
exif_mnote_data_apple_count()
static unsigned int exif_mnote_data_apple_count (ExifMnoteData * md) static
Definition at line 201 of file exif-mnote-data-apple.c.
Referenced by exif_mnote_data_apple_new().
exif_mnote_data_apple_free()
static void exif_mnote_data_apple_free (ExifMnoteData * md) static
Definition at line 32 of file exif-mnote-data-apple.c.
References _ExifMnoteDataApple::count, _MnoteAppleEntry::data, _ExifMnoteDataApple::entries, exif_mem_free(), and _ExifMnoteData::mem.
Referenced by exif_mnote_data_apple_load(), and exif_mnote_data_apple_new().
exif_mnote_data_apple_get_description()
static const char* exif_mnote_data_apple_get_description (ExifMnoteData * md, unsigned int i) static
Definition at line 241 of file exif-mnote-data-apple.c.
References _ExifMnoteDataApple::count, _ExifMnoteDataApple::entries, mnote_apple_tag_get_description(), and _MnoteAppleEntry::tag.
Referenced by exif_mnote_data_apple_new().
exif_mnote_data_apple_get_id()
static unsigned int exif_mnote_data_apple_get_id (ExifMnoteData * md, unsigned int i) static
Definition at line 208 of file exif-mnote-data-apple.c.
References _ExifMnoteDataApple::count, _ExifMnoteDataApple::entries, and _MnoteAppleEntry::tag.
Referenced by exif_mnote_data_apple_new().
exif_mnote_data_apple_get_name()
static const char* exif_mnote_data_apple_get_name (ExifMnoteData * md, unsigned int i) static
Definition at line 219 of file exif-mnote-data-apple.c.
References _ExifMnoteDataApple::count, _ExifMnoteDataApple::entries, mnote_apple_tag_get_name(), and _MnoteAppleEntry::tag.
Referenced by exif_mnote_data_apple_new().
exif_mnote_data_apple_get_title()
static const char* exif_mnote_data_apple_get_title (ExifMnoteData * md, unsigned int i) static
Definition at line 230 of file exif-mnote-data-apple.c.
References _ExifMnoteDataApple::count, _ExifMnoteDataApple::entries, mnote_apple_tag_get_title(), and _MnoteAppleEntry::tag.
Referenced by exif_mnote_data_apple_new().
exif_mnote_data_apple_get_value()
static char* exif_mnote_data_apple_get_value (ExifMnoteData * md, unsigned int i, char * val, unsigned int maxlen) static
Definition at line 252 of file exif-mnote-data-apple.c.
References _ExifMnoteDataApple::count, _ExifMnoteDataApple::entries, and mnote_apple_entry_get_value().
Referenced by exif_mnote_data_apple_new().
exif_mnote_data_apple_identify()
int exif_mnote_data_apple_identify (const ExifData * ed, const ExifEntry * e)
Definition at line 263 of file exif-mnote-data-apple.c.
References _ExifEntry::data, and _ExifEntry::size.
Referenced by interpret_maker_note().
exif_mnote_data_apple_load()
static void exif_mnote_data_apple_load (ExifMnoteData * md, const unsigned char * buf, unsigned int buf_size) static
Definition at line 57 of file exif-mnote-data-apple.c.
References _MnoteAppleEntry::components, _ExifMnoteDataApple::count, _MnoteAppleEntry::data, _ExifMnoteDataApple::entries, EXIF_BYTE_ORDER_INTEL, EXIF_BYTE_ORDER_MOTOROLA, exif_format_get_size(), exif_get_long(), exif_get_short(), exif_log(), EXIF_LOG_CODE_CORRUPT_DATA, EXIF_LOG_NO_MEMORY, exif_mem_alloc(), exif_mnote_data_apple_free(), _MnoteAppleEntry::format, _ExifMnoteData::log, _ExifMnoteData::mem, _ExifMnoteDataApple::offset, _ExifMnoteDataApple::order, _MnoteAppleEntry::order, _MnoteAppleEntry::size, and _MnoteAppleEntry::tag.
Referenced by exif_mnote_data_apple_new().
exif_mnote_data_apple_new()
ExifMnoteData* exif_mnote_data_apple_new (ExifMem * mem)
Definition at line 273 of file exif-mnote-data-apple.c.
References _ExifMnoteDataMethods::count, exif_mem_alloc(), exif_mnote_data_apple_count(), exif_mnote_data_apple_free(), exif_mnote_data_apple_get_description(), exif_mnote_data_apple_get_id(), exif_mnote_data_apple_get_name(), exif_mnote_data_apple_get_title(), exif_mnote_data_apple_get_value(), exif_mnote_data_apple_load(), exif_mnote_data_apple_set_byte_order(), exif_mnote_data_apple_set_offset(), exif_mnote_data_construct(), _ExifMnoteDataMethods::free, _ExifMnoteDataMethods::get_description, _ExifMnoteDataMethods::get_id, _ExifMnoteDataMethods::get_name, _ExifMnoteDataMethods::get_title, _ExifMnoteDataMethods::get_value, _ExifMnoteDataMethods::load, _ExifMnoteData::methods, _ExifMnoteDataMethods::set_byte_order, and _ExifMnoteDataMethods::set_offset.
Referenced by interpret_maker_note().
exif_mnote_data_apple_set_byte_order()
static void exif_mnote_data_apple_set_byte_order (ExifMnoteData * md, ExifByteOrder o) static
Definition at line 178 of file exif-mnote-data-apple.c.
References _MnoteAppleEntry::components, _ExifMnoteDataApple::count, _MnoteAppleEntry::data, _ExifMnoteDataApple::entries, exif_array_set_byte_order(), exif_format_get_size(), _MnoteAppleEntry::format, _ExifMnoteDataApple::order, _MnoteAppleEntry::order, and _MnoteAppleEntry::size.
Referenced by exif_mnote_data_apple_new().
exif_mnote_data_apple_set_offset()
static void exif_mnote_data_apple_set_offset (ExifMnoteData * md, unsigned int o) static
Definition at line 167 of file exif-mnote-data-apple.c.
Referenced by exif_mnote_data_apple_new().
libexif Generated by