EXIF library (libexif) Internals: libexif/exif-mem.h File Reference
exif-mem.h File Reference
Define the ExifMem data type and the associated functions.
#include <libexif/exif-utils.h>
Typedefs
typedef void *(* ExifMemAllocFunc) (ExifLong s)
Should work like calloc()
typedef void *(* ExifMemReallocFunc) (void *p, ExifLong s)
Should work like realloc()
typedef void(* ExifMemFreeFunc) (void *p)
Free method for ExifMem.
typedef struct _ExifMem ExifMem
ExifMem define a memory allocator.
Functions
ExifMem * exif_mem_new (ExifMemAllocFunc a, ExifMemReallocFunc r, ExifMemFreeFunc f)
Create a new ExifMem.
void exif_mem_ref (ExifMem *)
Refcount an ExifMem.
void exif_mem_unref (ExifMem *)
Unrefcount an ExifMem.
void * exif_mem_alloc (ExifMem *m, ExifLong s)
void * exif_mem_realloc (ExifMem *m, void *p, ExifLong s)
void exif_mem_free (ExifMem *m, void *p)
ExifMem * exif_mem_new_default (void)
Create a new ExifMem with default values for your convenience.
Detailed Description
Define the ExifMem data type and the associated functions.
ExifMem defines the memory management functions used within libexif.
Definition in file exif-mem.h.
Typedef Documentation
ExifMem
typedef struct _ExifMem ExifMem
ExifMem define a memory allocator.
Definition at line 59 of file exif-mem.h.
ExifMemAllocFunc
typedef void *(* ExifMemAllocFunc) (ExifLong s)
Should work like calloc()
Parameters
[in] s the size of the block to allocate.
Returns
the allocated memory and initialized.
Definition at line 41 of file exif-mem.h.
ExifMemFreeFunc
typedef void(* ExifMemFreeFunc) (void *p)
Free method for ExifMem.
Parameters
[in] p the pointer to free
Returns
the freed pointer
Definition at line 56 of file exif-mem.h.
ExifMemReallocFunc
typedef void *(* ExifMemReallocFunc) (void *p, ExifLong s)
Should work like realloc()
Parameters
[in] p the pointer to reallocate
[in] s the size of the reallocated block
Returns
allocated memory
Definition at line 49 of file exif-mem.h.
Function Documentation
exif_mem_alloc()
void * exif_mem_alloc (ExifMem * m, ExifLong s)
Definition at line 101 of file exif-mem.c.
References _ExifMem::alloc_func, and _ExifMem::realloc_func.
Referenced by exif_content_new_mem(), exif_data_alloc(), exif_data_new_mem(), exif_entry_alloc(), exif_entry_get_value(), exif_entry_new_mem(), exif_loader_alloc(), exif_loader_new_mem(), exif_log_new_mem(), exif_mnote_data_apple_load(), exif_mnote_data_apple_new(), exif_mnote_data_canon_load(), exif_mnote_data_canon_new(), exif_mnote_data_canon_save(), exif_mnote_data_construct(), exif_mnote_data_fuji_load(), exif_mnote_data_fuji_new(), exif_mnote_data_fuji_save(), exif_mnote_data_olympus_load(), exif_mnote_data_olympus_new(), exif_mnote_data_olympus_save(), exif_mnote_data_pentax_load(), exif_mnote_data_pentax_new(), exif_mnote_data_pentax_save(), and main().
exif_mem_free()
void exif_mem_free (ExifMem * m, void * p)
Definition at line 91 of file exif-mem.c.
References _ExifMem::free_func.
Referenced by exif_content_free(), exif_content_new_mem(), exif_content_remove_entry(), exif_data_free(), exif_data_load_data_thumbnail(), exif_data_new_mem(), exif_data_save_data_entry(), exif_entry_fix(), exif_entry_free(), exif_entry_get_value(), exif_entry_new_mem(), exif_entry_realloc(), exif_loader_free(), exif_loader_reset(), exif_log_free(), exif_mem_unref(), exif_mnote_data_apple_free(), exif_mnote_data_canon_clear(), exif_mnote_data_canon_load(), exif_mnote_data_free(), exif_mnote_data_fuji_clear(), exif_mnote_data_olympus_clear(), and exif_mnote_data_pentax_clear().
exif_mem_new()
ExifMem * exif_mem_new (ExifMemAllocFunc a, ExifMemReallocFunc r, ExifMemFreeFunc f)
Create a new ExifMem.
Parameters
[in] a the allocator function
[in] r the reallocator function
[in] f the free function
Returns
allocated ExifMem, or NULL on error
Definition at line 56 of file exif-mem.c.
References _ExifMem::alloc_func, _ExifMem::free_func, _ExifMem::realloc_func, and _ExifMem::ref_count.
Referenced by exif_mem_new_default().
exif_mem_new_default()
ExifMem * exif_mem_new_default (void)
Create a new ExifMem with default values for your convenience.
Returns
return a new default ExifMem
Definition at line 117 of file exif-mem.c.
References exif_mem_alloc_func(), exif_mem_free_func(), exif_mem_new(), and exif_mem_realloc_func().
Referenced by exif_content_new(), exif_data_new(), exif_entry_new(), exif_loader_new(), exif_log_new(), and main().
exif_mem_realloc()
void * exif_mem_realloc (ExifMem * m, void * p, ExifLong s)
Definition at line 111 of file exif-mem.c.
References _ExifMem::realloc_func.
Referenced by exif_content_add_entry(), exif_content_remove_entry(), exif_data_save_data_content(), exif_data_save_data_entry(), exif_entry_realloc(), exif_mnote_data_canon_save(), exif_mnote_data_fuji_save(), exif_mnote_data_olympus_save(), and exif_mnote_data_pentax_save().
exif_mem_ref()
void exif_mem_ref (ExifMem * mem)
Refcount an ExifMem.
Definition at line 76 of file exif-mem.c.
References _ExifMem::ref_count.
Referenced by exif_content_new_mem(), exif_data_new_mem(), exif_entry_new_mem(), exif_loader_new_mem(), exif_log_new_mem(), and exif_mnote_data_construct().
exif_mem_unref()
void exif_mem_unref (ExifMem * mem)
Unrefcount an ExifMem.
If the refcount reaches 0, the ExifMem is freed
Definition at line 83 of file exif-mem.c.
References exif_mem_free(), and _ExifMem::ref_count.
Referenced by exif_content_free(), exif_content_new(), exif_data_free(), exif_data_new(), exif_entry_free(), exif_entry_new(), exif_loader_free(), exif_loader_new(), exif_log_free(), exif_log_new(), exif_mnote_data_free(), and main().
libexif Generated by