EXIF library (libexif) Internals: libexif/fuji/exif-mnote-data-fuji.c File Reference
exif-mnote-data-fuji.c File Reference
#include <stdlib.h>
#include <string.h>
#include <config.h>
#include <libexif/exif-byte-order.h>
#include <libexif/exif-utils.h>
#include "exif-mnote-data-fuji.h"
Data Structures
struct _MNoteFujiDataPrivate
Macros
#define CHECKOVERFLOW(offset, datasize, structsize) (((offset) >= (datasize)) || ((structsize) > (datasize)) || ((offset) > (datasize) - (structsize)))
Functions
static void exif_mnote_data_fuji_clear (ExifMnoteDataFuji *n)
static void exif_mnote_data_fuji_free (ExifMnoteData *n)
static char * exif_mnote_data_fuji_get_value (ExifMnoteData *d, unsigned int i, char *val, unsigned int maxlen)
static void exif_mnote_data_fuji_save (ExifMnoteData *ne, unsigned char **buf, unsigned int *buf_size)
static void exif_mnote_data_fuji_load (ExifMnoteData *en, const unsigned char *buf, unsigned int buf_size)
static unsigned int exif_mnote_data_fuji_count (ExifMnoteData *n)
static unsigned int exif_mnote_data_fuji_get_id (ExifMnoteData *d, unsigned int n)
static const char * exif_mnote_data_fuji_get_name (ExifMnoteData *d, unsigned int i)
static const char * exif_mnote_data_fuji_get_title (ExifMnoteData *d, unsigned int i)
static const char * exif_mnote_data_fuji_get_description (ExifMnoteData *d, unsigned int i)
static void exif_mnote_data_fuji_set_byte_order (ExifMnoteData *d, ExifByteOrder o)
static void exif_mnote_data_fuji_set_offset (ExifMnoteData *n, unsigned int o)
int exif_mnote_data_fuji_identify (const ExifData *ed, const ExifEntry *e)
Detect if MakerNote is recognized as one handled by the Fuji module.
ExifMnoteData * exif_mnote_data_fuji_new (ExifMem *mem)
Macro Definition Documentation
CHECKOVERFLOW
#define CHECKOVERFLOW (offset, datasize, structsize) (((offset) >= (datasize)) || ((structsize) > (datasize)) || ((offset) > (datasize) - (structsize)))
Definition at line 33 of file exif-mnote-data-fuji.c.
Function Documentation
exif_mnote_data_fuji_clear()
static void exif_mnote_data_fuji_clear (ExifMnoteDataFuji * n) static
Definition at line 40 of file exif-mnote-data-fuji.c.
References _ExifMnoteDataFuji::count, _MnoteFujiEntry::data, _ExifMnoteDataFuji::entries, exif_mem_free(), and _ExifMnoteData::mem.
Referenced by exif_mnote_data_fuji_free(), and exif_mnote_data_fuji_load().
exif_mnote_data_fuji_count()
static unsigned int exif_mnote_data_fuji_count (ExifMnoteData * n) static
Definition at line 273 of file exif-mnote-data-fuji.c.
Referenced by exif_mnote_data_fuji_new().
exif_mnote_data_fuji_free()
static void exif_mnote_data_fuji_free (ExifMnoteData * n) static
Definition at line 60 of file exif-mnote-data-fuji.c.
References exif_mnote_data_fuji_clear().
Referenced by exif_mnote_data_fuji_new().
exif_mnote_data_fuji_get_description()
static const char * exif_mnote_data_fuji_get_description (ExifMnoteData * d, unsigned int i) static
Definition at line 309 of file exif-mnote-data-fuji.c.
References _ExifMnoteDataFuji::count, _ExifMnoteDataFuji::entries, mnote_fuji_tag_get_description(), and _MnoteFujiEntry::tag.
Referenced by exif_mnote_data_fuji_new().
exif_mnote_data_fuji_get_id()
static unsigned int exif_mnote_data_fuji_get_id (ExifMnoteData * d, unsigned int n) static
Definition at line 279 of file exif-mnote-data-fuji.c.
References _ExifMnoteDataFuji::count, _ExifMnoteDataFuji::entries, and _MnoteFujiEntry::tag.
Referenced by exif_mnote_data_fuji_new().
exif_mnote_data_fuji_get_name()
static const char * exif_mnote_data_fuji_get_name (ExifMnoteData * d, unsigned int i) static
Definition at line 289 of file exif-mnote-data-fuji.c.
References _ExifMnoteDataFuji::count, _ExifMnoteDataFuji::entries, mnote_fuji_tag_get_name(), and _MnoteFujiEntry::tag.
Referenced by exif_mnote_data_fuji_new().
exif_mnote_data_fuji_get_title()
static const char * exif_mnote_data_fuji_get_title (ExifMnoteData * d, unsigned int i) static
Definition at line 299 of file exif-mnote-data-fuji.c.
References _ExifMnoteDataFuji::count, _ExifMnoteDataFuji::entries, mnote_fuji_tag_get_title(), and _MnoteFujiEntry::tag.
Referenced by exif_mnote_data_fuji_new().
exif_mnote_data_fuji_get_value()
static char * exif_mnote_data_fuji_get_value (ExifMnoteData * d, unsigned int i, char * val, unsigned int maxlen) static
Definition at line 68 of file exif-mnote-data-fuji.c.
References _ExifMnoteDataFuji::count, _ExifMnoteDataFuji::entries, and mnote_fuji_entry_get_value().
Referenced by exif_mnote_data_fuji_new().
exif_mnote_data_fuji_identify()
int exif_mnote_data_fuji_identify (const ExifData * ed, const ExifEntry * e)
Detect if MakerNote is recognized as one handled by the Fuji module.
Parameters
[in] ed image ExifData to identify as as a Fuji type
[in] e ExifEntry for EXIF_TAG_MAKER_NOTE, from within ed but duplicated here for convenience
Returns
0 if not recognized, nonzero if recognized. The specific nonzero value returned may identify a subtype unique within this module.
Definition at line 345 of file exif-mnote-data-fuji.c.
References _ExifEntry::data, and _ExifEntry::size.
Referenced by interpret_maker_note().
exif_mnote_data_fuji_load()
static void exif_mnote_data_fuji_load (ExifMnoteData * en, const unsigned char * buf, unsigned int buf_size) static
Definition at line 156 of file exif-mnote-data-fuji.c.
References CHECKOVERFLOW, _MnoteFujiEntry::components, _ExifMnoteDataFuji::count, _MnoteFujiEntry::data, _ExifMnoteDataFuji::entries, EXIF_BYTE_ORDER_INTEL, exif_format_get_size(), exif_get_long(), exif_get_short(), exif_log(), EXIF_LOG_CODE_CORRUPT_DATA, EXIF_LOG_CODE_DEBUG, EXIF_LOG_NO_MEMORY, exif_mem_alloc(), exif_mnote_data_fuji_clear(), _MnoteFujiEntry::format, _ExifMnoteData::log, _ExifMnoteData::mem, mnote_fuji_tag_get_name(), _ExifMnoteDataFuji::offset, _ExifMnoteDataFuji::order, _MnoteFujiEntry::order, _MnoteFujiEntry::size, and _MnoteFujiEntry::tag.
Referenced by exif_mnote_data_fuji_new().
exif_mnote_data_fuji_new()
ExifMnoteData * exif_mnote_data_fuji_new (ExifMem * mem)
Definition at line 352 of file exif-mnote-data-fuji.c.
References _ExifMnoteDataMethods::count, exif_mem_alloc(), exif_mnote_data_construct(), exif_mnote_data_fuji_count(), exif_mnote_data_fuji_free(), exif_mnote_data_fuji_get_description(), exif_mnote_data_fuji_get_id(), exif_mnote_data_fuji_get_name(), exif_mnote_data_fuji_get_title(), exif_mnote_data_fuji_get_value(), exif_mnote_data_fuji_load(), exif_mnote_data_fuji_save(), exif_mnote_data_fuji_set_byte_order(), exif_mnote_data_fuji_set_offset(), _ExifMnoteDataMethods::free, _ExifMnoteDataMethods::get_description, _ExifMnoteDataMethods::get_id, _ExifMnoteDataMethods::get_name, _ExifMnoteDataMethods::get_title, _ExifMnoteDataMethods::get_value, _ExifMnoteDataMethods::load, _ExifMnoteData::methods, _ExifMnoteDataMethods::save, _ExifMnoteDataMethods::set_byte_order, and _ExifMnoteDataMethods::set_offset.
Referenced by interpret_maker_note().
exif_mnote_data_fuji_save()
static void exif_mnote_data_fuji_save (ExifMnoteData * ne, unsigned char ** buf, unsigned int * buf_size) static
Definition at line 83 of file exif-mnote-data-fuji.c.
References _MnoteFujiEntry::components, _ExifMnoteDataFuji::count, _MnoteFujiEntry::data, _ExifMnoteDataFuji::entries, exif_format_get_size(), exif_mem_alloc(), exif_mem_realloc(), exif_set_long(), exif_set_short(), _MnoteFujiEntry::format, _ExifMnoteData::mem, _ExifMnoteDataFuji::order, and _MnoteFujiEntry::tag.
Referenced by exif_mnote_data_fuji_new().
exif_mnote_data_fuji_set_byte_order()
static void exif_mnote_data_fuji_set_byte_order (ExifMnoteData * d, ExifByteOrder o) static
Definition at line 319 of file exif-mnote-data-fuji.c.
References _MnoteFujiEntry::components, _ExifMnoteDataFuji::count, _MnoteFujiEntry::data, _ExifMnoteDataFuji::entries, exif_array_set_byte_order(), exif_format_get_size(), _MnoteFujiEntry::format, _ExifMnoteDataFuji::order, _MnoteFujiEntry::order, and _MnoteFujiEntry::size.
Referenced by exif_mnote_data_fuji_new().
exif_mnote_data_fuji_set_offset()
static void exif_mnote_data_fuji_set_offset (ExifMnoteData * n, unsigned int o) static
Definition at line 339 of file exif-mnote-data-fuji.c.
Referenced by exif_mnote_data_fuji_new().
libexif Generated by