EXIF library (libexif) Internals: libexif/pentax/exif-mnote-data-pentax.h File Reference
exif-mnote-data-pentax.h File Reference
#include <libexif/exif-byte-order.h>
#include <libexif/exif-mnote-data.h>
#include <libexif/exif-mnote-data-priv.h>
#include <libexif/pentax/mnote-pentax-entry.h>
#include <libexif/exif-data.h>
#include <libexif/exif-mem.h>
Data Structures
struct _ExifMnoteDataPentax
Typedefs
typedef struct _ExifMnoteDataPentax ExifMnoteDataPentax
Enumerations
enum PentaxVersion { pentaxV1 = 1 , pentaxV2 = 2 , pentaxV3 = 3 , casioV2 = 4 }
Functions
int exif_mnote_data_pentax_identify (const ExifData *ed, const ExifEntry *e)
Detect if MakerNote is recognized as one handled by the Pentax module.
ExifMnoteData * exif_mnote_data_pentax_new (ExifMem *)
Typedef Documentation
ExifMnoteDataPentax
typedef struct _ExifMnoteDataPentax ExifMnoteDataPentax
Definition at line 35 of file exif-mnote-data-pentax.h.
Enumeration Type Documentation
PentaxVersion
enum PentaxVersion
Enumerator
pentaxV1
pentaxV2
pentaxV3
casioV2
Definition at line 33 of file exif-mnote-data-pentax.h.
Function Documentation
exif_mnote_data_pentax_identify()
int exif_mnote_data_pentax_identify (const ExifData * ed, const ExifEntry * e)
Detect if MakerNote is recognized as one handled by the Pentax module.
Parameters
[in] ed image ExifData to identify as as a Pentax type
[in] e ExifEntry for EXIF_TAG_MAKER_NOTE, from within ed but duplicated here for convenience
Returns
0 if not recognized, nonzero if recognized. The specific nonzero value returned may identify a subtype unique within this module.
Definition at line 428 of file exif-mnote-data-pentax.c.
References casioV2, _ExifEntry::data, pentaxV1, pentaxV2, pentaxV3, and _ExifEntry::size.
Referenced by interpret_maker_note().
exif_mnote_data_pentax_new()
ExifMnoteData * exif_mnote_data_pentax_new (ExifMem * mem)
Definition at line 452 of file exif-mnote-data-pentax.c.
References _ExifMnoteDataMethods::count, exif_mem_alloc(), exif_mnote_data_construct(), exif_mnote_data_pentax_count(), exif_mnote_data_pentax_free(), exif_mnote_data_pentax_get_description(), exif_mnote_data_pentax_get_id(), exif_mnote_data_pentax_get_name(), exif_mnote_data_pentax_get_title(), exif_mnote_data_pentax_get_value(), exif_mnote_data_pentax_load(), exif_mnote_data_pentax_save(), exif_mnote_data_pentax_set_byte_order(), exif_mnote_data_pentax_set_offset(), _ExifMnoteDataMethods::free, _ExifMnoteDataMethods::get_description, _ExifMnoteDataMethods::get_id, _ExifMnoteDataMethods::get_name, _ExifMnoteDataMethods::get_title, _ExifMnoteDataMethods::get_value, _ExifMnoteDataMethods::load, _ExifMnoteData::methods, _ExifMnoteDataMethods::save, _ExifMnoteDataMethods::set_byte_order, and _ExifMnoteDataMethods::set_offset.
Referenced by interpret_maker_note().
libexif Generated by