EXIF library (libexif) Internals: libexif/olympus/exif-mnote-data-olympus.h File Reference
exif-mnote-data-olympus.h File Reference
#include <libexif/exif-mnote-data-priv.h>
#include <libexif/olympus/mnote-olympus-entry.h>
#include <libexif/exif-byte-order.h>
#include <libexif/exif-data.h>
#include <libexif/exif-mem.h>
Data Structures
struct _ExifMnoteDataOlympus
Typedefs
typedef struct _ExifMnoteDataOlympus ExifMnoteDataOlympus
Enumerations
enum OlympusVersion {
unrecognized = 0, nikonV1 = 1, nikonV2 = 2, olympusV1 = 3,
olympusV2 = 4, sanyoV1 = 5, epsonV1 = 6, nikonV0 = 7
}
Functions
int exif_mnote_data_olympus_identify (const ExifData *ed, const ExifEntry *e)
Detect if MakerNote is recognized as one handled by the Olympus module.
ExifMnoteData * exif_mnote_data_olympus_new (ExifMem *)
Typedef Documentation
ExifMnoteDataOlympus
typedef struct _ExifMnoteDataOlympus ExifMnoteDataOlympus
Definition at line 42 of file exif-mnote-data-olympus.h.
Enumeration Type Documentation
OlympusVersion
enum OlympusVersion
Enumerator
unrecognized
nikonV1
nikonV2
olympusV1
olympusV2
sanyoV1
epsonV1
nikonV0
Definition at line 30 of file exif-mnote-data-olympus.h.
Function Documentation
exif_mnote_data_olympus_identify()
int exif_mnote_data_olympus_identify (const ExifData * ed, const ExifEntry * e)
Detect if MakerNote is recognized as one handled by the Olympus module.
Parameters
[in] ed image ExifData to identify as as an Olympus type
[in] e ExifEntry for EXIF_TAG_MAKER_NOTE, from within ed but duplicated here for convenience
Returns
0 if not recognized, nonzero if recognized. The specific nonzero value returned may identify a subtype unique within this module.
Definition at line 603 of file exif-mnote-data-olympus.c.
References _ExifEntry::data, exif_data_get_entry, exif_entry_get_value(), exif_mnote_data_olympus_identify_variant(), EXIF_TAG_MAKE, nikonV0, _ExifEntry::size, and unrecognized.
Referenced by interpret_maker_note().
exif_mnote_data_olympus_new()
ExifMnoteData* exif_mnote_data_olympus_new (ExifMem *)
Definition at line 629 of file exif-mnote-data-olympus.c.
References _ExifMnoteDataMethods::count, exif_mem_alloc(), exif_mnote_data_construct(), exif_mnote_data_olympus_count(), exif_mnote_data_olympus_free(), exif_mnote_data_olympus_get_description(), exif_mnote_data_olympus_get_id(), exif_mnote_data_olympus_get_name(), exif_mnote_data_olympus_get_title(), exif_mnote_data_olympus_get_value(), exif_mnote_data_olympus_load(), exif_mnote_data_olympus_save(), exif_mnote_data_olympus_set_byte_order(), exif_mnote_data_olympus_set_offset(), _ExifMnoteDataMethods::free, _ExifMnoteDataMethods::get_description, _ExifMnoteDataMethods::get_id, _ExifMnoteDataMethods::get_name, _ExifMnoteDataMethods::get_title, _ExifMnoteDataMethods::get_value, _ExifMnoteDataMethods::load, _ExifMnoteData::methods, _ExifMnoteDataMethods::save, _ExifMnoteDataMethods::set_byte_order, and _ExifMnoteDataMethods::set_offset.
Referenced by interpret_maker_note().
libexif Generated by