EXIF library (libexif) Internals: libexif/exif-format.c File Reference
exif-format.c File Reference
#include <config.h>
#include <libexif/exif-format.h>
#include <libexif/i18n.h>
#include <stdlib.h>
Functions
const char * exif_format_get_name (ExifFormat format)
Return a textual representation of the given EXIF data type.
unsigned char exif_format_get_size (ExifFormat format)
Return the raw size of the given EXIF data type.
Variables
struct {
ExifFormat format
const char * name
unsigned char size
} ExifFormatTable []
Table of data format types, descriptions and sizes.
Function Documentation
exif_format_get_name()
const char * exif_format_get_name (ExifFormat format)
Return a textual representation of the given EXIF data type.
Parameters
[in] format EXIF data format
Returns
localized textual name, or NULL if unknown
Definition at line 55 of file exif-format.c.
References _, bindtextdomain, ExifFormatTable, format, and name.
Referenced by content_foreach_func(), content_foreach_func(), content_foreach_func(), exif_entry_dump(), and exif_entry_fix().
exif_format_get_size()
unsigned char exif_format_get_size (ExifFormat format)
Return the raw size of the given EXIF data type.
Parameters
[in] format EXIF data format
Returns
size in bytes
Definition at line 68 of file exif-format.c.
References ExifFormatTable, and format.
Referenced by check_entry_format(), exif_array_set_byte_order(), exif_data_load_data_entry(), exif_data_save_data_entry(), exif_entry_fix(), exif_entry_format_value(), exif_entry_get_value(), exif_entry_initialize(), exif_entry_initialize_gps(), exif_mnote_data_apple_load(), exif_mnote_data_apple_set_byte_order(), exif_mnote_data_canon_load(), exif_mnote_data_canon_save(), exif_mnote_data_canon_set_byte_order(), exif_mnote_data_fuji_load(), exif_mnote_data_fuji_save(), exif_mnote_data_fuji_set_byte_order(), exif_mnote_data_olympus_load(), exif_mnote_data_olympus_save(), exif_mnote_data_olympus_set_byte_order(), exif_mnote_data_pentax_load(), exif_mnote_data_pentax_save(), exif_mnote_data_pentax_set_byte_order(), main(), and mnote_apple_entry_get_value().
Variable Documentation
[struct]
const struct { ... } ExifFormatTable[]
Initial value:
= {
        {EXIF_FORMAT_SHORT,     N_("Short"),     2},
        {EXIF_FORMAT_RATIONAL,  N_("Rational"),  8},
        {EXIF_FORMAT_SRATIONAL, N_("SRational"), 8},
        {EXIF_FORMAT_UNDEFINED, N_("Undefined"), 1},
        {EXIF_FORMAT_ASCII,     N_("ASCII"),     1},
        {EXIF_FORMAT_LONG,      N_("Long"),      4},
        {EXIF_FORMAT_BYTE,      N_("Byte"),      1},
        {EXIF_FORMAT_SBYTE,     N_("SByte"),     1},
        {EXIF_FORMAT_SSHORT,    N_("SShort"),    2},
        {EXIF_FORMAT_SLONG,     N_("SLong"),     4},
        {EXIF_FORMAT_FLOAT,     N_("Float"),     4},
        {EXIF_FORMAT_DOUBLE,    N_("Double"),    8},
        {0, NULL, 0}
}
Table of data format types, descriptions and sizes.
This table should be sorted in decreasing order of popularity in order to decrease the total average lookup time.
Referenced by exif_format_get_name(), and exif_format_get_size().
format
ExifFormat format
Definition at line 35 of file exif-format.c.
Referenced by exif_entry_log(), exif_format_get_name(), exif_format_get_size(), exif_get_short_convert(), exif_log(), and exif_logv().
name
const char* name (void)
Definition at line 36 of file exif-format.c.
Referenced by exif_format_get_name().
size
unsigned char size
Definition at line 37 of file exif-format.c.
Referenced by exif_data_load_data_entry(), exif_data_new_from_data(), exif_loader_write_file(), main(), mnote_apple_entry_get_value(), and mnote_canon_entry_get_value().
libexif Generated by