EXIF library (libexif) Internals: libexif/exif-log.c File Reference
libexif
exif-log.c File Reference
#include <config.h>
#include <libexif/exif-log.h>
#include <libexif/i18n.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct _ExifLog
Functions
const char * exif_log_code_get_title (ExifLogCode code)
Return a textual description of the given class of error log.
const char * exif_log_code_get_message (ExifLogCode code)
Return a verbose description of the given class of error log.
ExifLog * exif_log_new_mem (ExifMem *mem)
ExifLog * exif_log_new (void)
Create a new logging instance.
void exif_log_ref (ExifLog *log)
void exif_log_unref (ExifLog *log)
void exif_log_free (ExifLog *log)
Delete instance of ExifLog.
void exif_log_set_func (ExifLog *log, ExifLogFunc func, void *data)
Register log callback function.
void exif_log (ExifLog *log, ExifLogCode code, const char *domain, const char *format,...)
void exif_logv (ExifLog *log, ExifLogCode code, const char *domain, const char *format, va_list args)
Variables
struct {
ExifLogCode code
const char * title
const char * message
} codes []
Function Documentation
void exif_log (ExifLog * log, ExifLogCode code, const char * domain, const char * format, ...)
Definition at line 135 of file exif-log.c.
Referenced by exif_content_add_entry(), exif_content_fix(), exif_data_load_data(), exif_data_load_data_content(), exif_data_load_data_entry(), exif_data_load_data_thumbnail(), exif_data_save_data(), exif_data_save_data_content(), exif_loader_get_buf(), exif_loader_write(), exif_loader_write_file(), exif_mnote_data_canon_load(), exif_mnote_data_fuji_load(), exif_mnote_data_olympus_load(), exif_mnote_data_pentax_load(), exif_mnote_data_pentax_save(), fix_func(), interpret_maker_note(), and remove_not_recorded().
const char* exif_log_code_get_message (ExifLogCode code)
Return a verbose description of the given class of error log.
Parameters:
[in] code logging message class
Returns:
verbose description of the log class
Definition at line 62 of file exif-log.c.
const char* exif_log_code_get_title (ExifLogCode code)
Return a textual description of the given class of error log.
Parameters:
[in] code logging message class
Returns:
textual description of the log class
Definition at line 53 of file exif-log.c.
void exif_log_free (ExifLog * log)
Delete instance of ExifLog.
See also:
exif_log_new
Parameters:
[in] log ExifLog
Returns:
new instance of ExifLog
Definition at line 112 of file exif-log.c.
Referenced by exif_log_unref().
ExifLog* exif_log_new (void)
Create a new logging instance.
See also:
exif_log_free
Returns:
new instance of ExifLog
Definition at line 86 of file exif-log.c.
ExifLog* exif_log_new_mem (ExifMem * mem)
Definition at line 71 of file exif-log.c.
Referenced by exif_log_new().
void exif_log_ref (ExifLog * log)
Definition at line 97 of file exif-log.c.
Referenced by exif_content_log(), exif_data_log(), exif_loader_log(), and exif_mnote_data_log().
void exif_log_set_func (ExifLog * log, ExifLogFunc func, void * data)
Register log callback function.
Calls to the log callback function are purely for diagnostic purposes.
Parameters:
[in] log logging state variable
[in] func callback function to set
[in] data data to pass into callback function
Definition at line 123 of file exif-log.c.
void exif_log_unref (ExifLog * log)
Definition at line 104 of file exif-log.c.
Referenced by exif_content_free(), exif_content_log(), exif_data_free(), exif_data_log(), exif_loader_free(), exif_loader_log(), exif_mnote_data_free(), and exif_mnote_data_log().
void exif_logv (ExifLog * log, ExifLogCode code, const char * domain, const char * format, va_list args)
Definition at line 146 of file exif-log.c.
Referenced by exif_entry_log(), and exif_log().
Variable Documentation
ExifLogCode code
Definition at line 39 of file exif-log.c.
struct { ... } codes[] [static]
Referenced by exif_log_code_get_message(), and exif_log_code_get_title().
const char* message
Definition at line 41 of file exif-log.c.
Referenced by exif_log_code_get_message().
const char* title
Definition at line 40 of file exif-log.c.
Generated by