EXIF library (libexif) Internals: libexif/exif-utils.c File Reference
exif-utils.c File Reference
#include <config.h>
#include <libexif/exif-utils.h>
Functions
void exif_array_set_byte_order (ExifFormat f, unsigned char *b, unsigned int n, ExifByteOrder o_orig, ExifByteOrder o_new)
ExifSShort exif_get_sshort (const unsigned char *buf, ExifByteOrder order)
Retrieve an ExifSShort value from memory.
ExifShort exif_get_short (const unsigned char *buf, ExifByteOrder order)
Retrieve an ExifShort value from memory.
void exif_set_sshort (unsigned char *b, ExifByteOrder order, ExifSShort value)
Store an ExifSShort value into memory in EXIF format.
void exif_set_short (unsigned char *b, ExifByteOrder order, ExifShort value)
Store an ExifShort value into memory in EXIF format.
ExifSLong exif_get_slong (const unsigned char *b, ExifByteOrder order)
Retrieve an ExifSLong value from memory.
void exif_set_slong (unsigned char *b, ExifByteOrder order, ExifSLong value)
Store an ExifSLong value into memory in EXIF format.
ExifLong exif_get_long (const unsigned char *buf, ExifByteOrder order)
Retrieve an ExifLong value from memory.
void exif_set_long (unsigned char *b, ExifByteOrder order, ExifLong value)
Store an ExifLong value into memory in EXIF format.
ExifSRational exif_get_srational (const unsigned char *buf, ExifByteOrder order)
Retrieve an ExifSRational value from memory.
ExifRational exif_get_rational (const unsigned char *buf, ExifByteOrder order)
Retrieve an ExifRational value from memory.
void exif_set_rational (unsigned char *buf, ExifByteOrder order, ExifRational value)
Store an ExifRational value into memory in EXIF format.
void exif_set_srational (unsigned char *buf, ExifByteOrder order, ExifSRational value)
Store an ExifSRational value into memory in EXIF format.
void exif_convert_utf16_to_utf8 (char *out, unsigned int outlen, const unsigned char *in, unsigned int inlen)
This function converts rather UCS-2LE than UTF-16 to UTF-8.
Function Documentation
exif_array_set_byte_order()
void exif_array_set_byte_order (ExifFormat f, unsigned char * b, unsigned int n, ExifByteOrder o_orig, ExifByteOrder o_new)
Definition at line 28 of file exif-utils.c.
References EXIF_FORMAT_ASCII, EXIF_FORMAT_BYTE, exif_format_get_size(), EXIF_FORMAT_LONG, EXIF_FORMAT_RATIONAL, EXIF_FORMAT_SHORT, EXIF_FORMAT_SLONG, EXIF_FORMAT_SRATIONAL, EXIF_FORMAT_SSHORT, EXIF_FORMAT_UNDEFINED, exif_get_long(), exif_get_rational(), exif_get_short(), exif_get_slong(), exif_get_srational(), exif_get_sshort(), exif_set_long(), exif_set_rational(), exif_set_short(), exif_set_slong(), exif_set_srational(), and exif_set_sshort().
Referenced by entry_set_byte_order(), exif_mnote_data_apple_set_byte_order(), exif_mnote_data_canon_set_byte_order(), exif_mnote_data_fuji_set_byte_order(), exif_mnote_data_olympus_set_byte_order(), and exif_mnote_data_pentax_set_byte_order().
exif_convert_utf16_to_utf8()
void exif_convert_utf16_to_utf8 (char * out, unsigned int outlen, const unsigned char * in, unsigned int inlen)
This function converts rather UCS-2LE than UTF-16 to UTF-8.
It should really be replaced by iconv().
Definition at line 222 of file exif-utils.c.
References EXIF_BYTE_ORDER_INTEL, and exif_get_short().
Referenced by exif_entry_get_value().
exif_get_long()
ExifLong exif_get_long (const unsigned char * b, ExifByteOrder order)
Retrieve an ExifLong value from memory.
Parameters
[in] b pointer to raw EXIF value in memory
[in] order byte order of raw value
Returns
value
Definition at line 167 of file exif-utils.c.
References exif_get_slong().
Referenced by exif_array_set_byte_order(), exif_data_load_data(), exif_data_load_data_content(), exif_data_load_data_entry(), exif_entry_format_value(), exif_get_rational(), exif_get_short_convert(), exif_mnote_data_apple_load(), exif_mnote_data_canon_load(), exif_mnote_data_fuji_load(), exif_mnote_data_olympus_load(), exif_mnote_data_pentax_load(), mnote_apple_entry_get_value(), mnote_canon_entry_get_value(), mnote_fuji_entry_get_value(), mnote_olympus_entry_get_value(), and mnote_pentax_entry_get_value().
exif_get_rational()
ExifRational exif_get_rational (const unsigned char * b, ExifByteOrder order)
Retrieve an ExifRational value from memory.
Parameters
[in] b pointer to raw EXIF value in memory
[in] order byte order of raw value
Returns
value
Definition at line 190 of file exif-utils.c.
References ExifRational::denominator, exif_get_long(), and ExifRational::numerator.
Referenced by exif_array_set_byte_order(), exif_entry_fix(), exif_entry_format_value(), exif_entry_get_value(), mnote_apple_entry_get_value(), mnote_fuji_entry_get_value(), and mnote_olympus_entry_get_value().
exif_get_short()
ExifShort exif_get_short (const unsigned char * b, ExifByteOrder order)
Retrieve an ExifShort value from memory.
Parameters
[in] b pointer to raw EXIF value in memory
[in] order byte order of raw value
Returns
value
Definition at line 104 of file exif-utils.c.
References exif_get_sshort().
Referenced by cmp_func(), exif_array_set_byte_order(), exif_convert_utf16_to_utf8(), exif_data_load_data(), exif_data_load_data_content(), exif_data_load_data_entry(), exif_entry_format_value(), exif_entry_get_value(), exif_get_short_convert(), exif_mnote_data_apple_load(), exif_mnote_data_canon_load(), exif_mnote_data_fuji_load(), exif_mnote_data_olympus_load(), exif_mnote_data_pentax_load(), mnote_apple_entry_get_value(), mnote_canon_entry_count_values(), mnote_canon_entry_get_value(), mnote_fuji_entry_get_value(), mnote_olympus_entry_get_value(), and mnote_pentax_entry_get_value().
exif_get_slong()
ExifSLong exif_get_slong (const unsigned char * b, ExifByteOrder order)
Retrieve an ExifSLong value from memory.
Parameters
[in] b pointer to raw EXIF value in memory
[in] order byte order of raw value
Returns
value
Definition at line 132 of file exif-utils.c.
References EXIF_BYTE_ORDER_INTEL, and EXIF_BYTE_ORDER_MOTOROLA.
Referenced by exif_array_set_byte_order(), exif_entry_format_value(), exif_get_long(), exif_get_short_convert(), exif_get_srational(), mnote_apple_entry_get_value(), mnote_canon_entry_get_value(), mnote_fuji_entry_get_value(), mnote_olympus_entry_get_value(), and mnote_pentax_entry_get_value().
exif_get_srational()
ExifSRational exif_get_srational (const unsigned char * b, ExifByteOrder order)
Retrieve an ExifSRational value from memory.
Parameters
[in] b pointer to raw EXIF value in memory
[in] order byte order of raw value
Returns
value
Definition at line 179 of file exif-utils.c.
References ExifSRational::denominator, exif_get_slong(), and ExifSRational::numerator.
Referenced by exif_array_set_byte_order(), exif_entry_fix(), exif_entry_format_value(), exif_entry_get_value(), mnote_apple_entry_get_value(), mnote_fuji_entry_get_value(), and mnote_olympus_entry_get_value().
exif_get_sshort()
ExifSShort exif_get_sshort (const unsigned char * b, ExifByteOrder order)
Retrieve an ExifSShort value from memory.
Parameters
[in] b pointer to raw EXIF value in memory
[in] order byte order of raw value
Returns
value
Definition at line 89 of file exif-utils.c.
References EXIF_BYTE_ORDER_INTEL, and EXIF_BYTE_ORDER_MOTOROLA.
Referenced by exif_array_set_byte_order(), exif_entry_format_value(), exif_get_short(), exif_get_short_convert(), mnote_apple_entry_get_value(), mnote_canon_entry_get_value(), mnote_fuji_entry_get_value(), mnote_olympus_entry_get_value(), and mnote_pentax_entry_get_value().
exif_set_long()
void exif_set_long (unsigned char * b, ExifByteOrder order, ExifLong value)
Store an ExifLong value into memory in EXIF format.
Parameters
[out] b buffer in which to write raw value
[in] order byte order to use
[in] value data value to store
Definition at line 173 of file exif-utils.c.
References exif_set_slong().
Referenced by exif_array_set_byte_order(), exif_data_save_data(), exif_data_save_data_content(), exif_data_save_data_entry(), exif_mnote_data_canon_save(), exif_mnote_data_fuji_save(), exif_mnote_data_olympus_save(), exif_mnote_data_pentax_save(), and exif_set_rational().
exif_set_rational()
void exif_set_rational (unsigned char * b, ExifByteOrder order, ExifRational value)
Store an ExifRational value into memory in EXIF format.
Parameters
[out] b buffer in which to write raw value
[in] order byte order to use
[in] value data value to store
Definition at line 201 of file exif-utils.c.
References ExifRational::denominator, exif_set_long(), and ExifRational::numerator.
Referenced by exif_array_set_byte_order(), exif_entry_fix(), exif_entry_initialize(), and main().
exif_set_short()
void exif_set_short (unsigned char * b, ExifByteOrder order, ExifShort value)
Store an ExifShort value into memory in EXIF format.
Parameters
[out] b buffer in which to write raw value
[in] order byte order to use
[in] value data value to store
Definition at line 126 of file exif-utils.c.
References exif_set_sshort().
Referenced by exif_array_set_byte_order(), exif_data_save_data(), exif_data_save_data_content(), exif_data_save_data_entry(), exif_entry_fix(), exif_entry_initialize(), exif_mnote_data_canon_save(), exif_mnote_data_fuji_save(), exif_mnote_data_olympus_save(), exif_mnote_data_pentax_save(), main(), and main().
exif_set_slong()
void exif_set_slong (unsigned char * b, ExifByteOrder order, ExifSLong value)
Store an ExifSLong value into memory in EXIF format.
Parameters
[out] b buffer in which to write raw value
[in] order byte order to use
[in] value data value to store
Definition at line 147 of file exif-utils.c.
References EXIF_BYTE_ORDER_INTEL, and EXIF_BYTE_ORDER_MOTOROLA.
Referenced by exif_array_set_byte_order(), exif_set_long(), and exif_set_srational().
exif_set_srational()
void exif_set_srational (unsigned char * b, ExifByteOrder order, ExifSRational value)
Store an ExifSRational value into memory in EXIF format.
Parameters
[out] b buffer in which to write raw value
[in] order byte order to use
[in] value data value to store
Definition at line 210 of file exif-utils.c.
References ExifSRational::denominator, exif_set_slong(), and ExifSRational::numerator.
Referenced by exif_array_set_byte_order(), exif_entry_fix(), and main().
exif_set_sshort()
void exif_set_sshort (unsigned char * b, ExifByteOrder order, ExifSShort value)
Store an ExifSShort value into memory in EXIF format.
Parameters
[out] b buffer in which to write raw value
[in] order byte order to use
[in] value data value to store
Definition at line 110 of file exif-utils.c.
References EXIF_BYTE_ORDER_INTEL, and EXIF_BYTE_ORDER_MOTOROLA.
Referenced by exif_array_set_byte_order(), and exif_set_short().
libexif Generated by