EXIF library (libexif) Internals: libexif/exif-mnote-data-priv.h File Reference
exif-mnote-data-priv.h File Reference
#include <libexif/exif-mnote-data.h>
#include <libexif/exif-byte-order.h>
#include <libexif/exif-log.h>
Data Structures
struct _ExifMnoteDataMethods
struct _ExifMnoteData
Typedefs
typedef struct _ExifMnoteDataMethods ExifMnoteDataMethods
typedef struct _ExifMnoteDataPriv ExifMnoteDataPriv
Functions
void exif_mnote_data_construct (ExifMnoteData *, ExifMem *mem)
void exif_mnote_data_set_byte_order (ExifMnoteData *, ExifByteOrder)
void exif_mnote_data_set_offset (ExifMnoteData *, unsigned int)
Typedef Documentation
ExifMnoteDataMethods
typedef struct _ExifMnoteDataMethods ExifMnoteDataMethods
Definition at line 35 of file exif-mnote-data-priv.h.
ExifMnoteDataPriv
typedef struct _ExifMnoteDataPriv ExifMnoteDataPriv
Definition at line 59 of file exif-mnote-data-priv.h.
Function Documentation
exif_mnote_data_construct()
void exif_mnote_data_construct (ExifMnoteData * d, ExifMem * mem)
Definition at line 37 of file exif-mnote-data.c.
References exif_mem_alloc(), exif_mem_ref(), _ExifMnoteData::mem, _ExifMnoteData::priv, and _ExifMnoteDataPriv::ref_count.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_fuji_new(), exif_mnote_data_olympus_new(), and exif_mnote_data_pentax_new().
exif_mnote_data_set_byte_order()
void exif_mnote_data_set_byte_order (ExifMnoteData * d, ExifByteOrder o)
Definition at line 98 of file exif-mnote-data.c.
References _ExifMnoteData::methods, and _ExifMnoteDataMethods::set_byte_order.
Referenced by exif_data_set_byte_order(), and interpret_maker_note().
exif_mnote_data_set_offset()
void exif_mnote_data_set_offset (ExifMnoteData * d, unsigned int o)
Definition at line 105 of file exif-mnote-data.c.
References _ExifMnoteData::methods, and _ExifMnoteDataMethods::set_offset.
Referenced by exif_data_save_data_entry(), and interpret_maker_note().
libexif Generated by