EXIF library (libexif) Internals: libexif/pentax/exif-mnote-data-pentax.c File Reference
exif-mnote-data-pentax.c File Reference
#include "config.h"
#include "exif-mnote-data-pentax.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <libexif/exif-byte-order.h>
#include <libexif/exif-utils.h>
Macros
#define CHECKOVERFLOW(offset, datasize, structsize) (((offset) >= (datasize)) || ((structsize) > (datasize)) || ((offset) > (datasize) - (structsize)))
Functions
static void exif_mnote_data_pentax_clear (ExifMnoteDataPentax *n)
static void exif_mnote_data_pentax_free (ExifMnoteData *n)
static char * exif_mnote_data_pentax_get_value (ExifMnoteData *d, unsigned int i, char *val, unsigned int maxlen)
static void exif_mnote_data_pentax_save (ExifMnoteData *ne, unsigned char **buf, unsigned int *buf_size)
save the MnoteData from ne to buf
static void exif_mnote_data_pentax_load (ExifMnoteData *en, const unsigned char *buf, unsigned int buf_size)
static unsigned int exif_mnote_data_pentax_count (ExifMnoteData *n)
static unsigned int exif_mnote_data_pentax_get_id (ExifMnoteData *d, unsigned int n)
static const char * exif_mnote_data_pentax_get_name (ExifMnoteData *d, unsigned int n)
static const char * exif_mnote_data_pentax_get_title (ExifMnoteData *d, unsigned int n)
static const char * exif_mnote_data_pentax_get_description (ExifMnoteData *d, unsigned int n)
static void exif_mnote_data_pentax_set_offset (ExifMnoteData *d, unsigned int o)
static void exif_mnote_data_pentax_set_byte_order (ExifMnoteData *d, ExifByteOrder o)
int exif_mnote_data_pentax_identify (const ExifData *ed, const ExifEntry *e)
Detect if MakerNote is recognized as one handled by the Pentax module.
ExifMnoteData * exif_mnote_data_pentax_new (ExifMem *mem)
Macro Definition Documentation
CHECKOVERFLOW
#define CHECKOVERFLOW (offset, datasize, structsize) (((offset) >= (datasize)) || ((structsize) > (datasize)) || ((offset) > (datasize) - (structsize)))
Definition at line 33 of file exif-mnote-data-pentax.c.
Function Documentation
exif_mnote_data_pentax_clear()
static void exif_mnote_data_pentax_clear (ExifMnoteDataPentax * n) static
Definition at line 36 of file exif-mnote-data-pentax.c.
References _ExifMnoteDataPentax::count, _MnotePentaxEntry::data, _ExifMnoteDataPentax::entries, exif_mem_free(), and _ExifMnoteData::mem.
Referenced by exif_mnote_data_pentax_free(), and exif_mnote_data_pentax_load().
exif_mnote_data_pentax_count()
static unsigned int exif_mnote_data_pentax_count (ExifMnoteData * n) static
Definition at line 356 of file exif-mnote-data-pentax.c.
Referenced by exif_mnote_data_pentax_new().
exif_mnote_data_pentax_free()
static void exif_mnote_data_pentax_free (ExifMnoteData * n) static
Definition at line 56 of file exif-mnote-data-pentax.c.
References exif_mnote_data_pentax_clear().
Referenced by exif_mnote_data_pentax_new().
exif_mnote_data_pentax_get_description()
static const char * exif_mnote_data_pentax_get_description (ExifMnoteData * d, unsigned int n) static
Definition at line 392 of file exif-mnote-data-pentax.c.
References _ExifMnoteDataPentax::count, _ExifMnoteDataPentax::entries, mnote_pentax_tag_get_description(), and _MnotePentaxEntry::tag.
Referenced by exif_mnote_data_pentax_new().
exif_mnote_data_pentax_get_id()
static unsigned int exif_mnote_data_pentax_get_id (ExifMnoteData * d, unsigned int n) static
Definition at line 362 of file exif-mnote-data-pentax.c.
References _ExifMnoteDataPentax::count, _ExifMnoteDataPentax::entries, and _MnotePentaxEntry::tag.
Referenced by exif_mnote_data_pentax_new().
exif_mnote_data_pentax_get_name()
static const char * exif_mnote_data_pentax_get_name (ExifMnoteData * d, unsigned int n) static
Definition at line 372 of file exif-mnote-data-pentax.c.
References _ExifMnoteDataPentax::count, _ExifMnoteDataPentax::entries, mnote_pentax_tag_get_name(), and _MnotePentaxEntry::tag.
Referenced by exif_mnote_data_pentax_new().
exif_mnote_data_pentax_get_title()
static const char * exif_mnote_data_pentax_get_title (ExifMnoteData * d, unsigned int n) static
Definition at line 382 of file exif-mnote-data-pentax.c.
References _ExifMnoteDataPentax::count, _ExifMnoteDataPentax::entries, mnote_pentax_tag_get_title(), and _MnotePentaxEntry::tag.
Referenced by exif_mnote_data_pentax_new().
exif_mnote_data_pentax_get_value()
static char * exif_mnote_data_pentax_get_value (ExifMnoteData * d, unsigned int i, char * val, unsigned int maxlen) static
Definition at line 64 of file exif-mnote-data-pentax.c.
References _ExifMnoteDataPentax::count, _ExifMnoteDataPentax::entries, and mnote_pentax_entry_get_value().
Referenced by exif_mnote_data_pentax_new().
exif_mnote_data_pentax_identify()
int exif_mnote_data_pentax_identify (const ExifData * ed, const ExifEntry * e)
Detect if MakerNote is recognized as one handled by the Pentax module.
Parameters
[in] ed image ExifData to identify as as a Pentax type
[in] e ExifEntry for EXIF_TAG_MAKER_NOTE, from within ed but duplicated here for convenience
Returns
0 if not recognized, nonzero if recognized. The specific nonzero value returned may identify a subtype unique within this module.
Definition at line 428 of file exif-mnote-data-pentax.c.
References casioV2, _ExifEntry::data, pentaxV1, pentaxV2, pentaxV3, and _ExifEntry::size.
Referenced by interpret_maker_note().
exif_mnote_data_pentax_load()
static void exif_mnote_data_pentax_load (ExifMnoteData * en, const unsigned char * buf, unsigned int buf_size) static
Definition at line 218 of file exif-mnote-data-pentax.c.
References casioV2, CHECKOVERFLOW, _MnotePentaxEntry::components, _ExifMnoteDataPentax::count, _MnotePentaxEntry::data, _ExifMnoteDataPentax::entries, EXIF_BYTE_ORDER_INTEL, EXIF_BYTE_ORDER_MOTOROLA, exif_format_get_size(), exif_get_long(), exif_get_short(), exif_log(), EXIF_LOG_CODE_CORRUPT_DATA, EXIF_LOG_CODE_DEBUG, EXIF_LOG_NO_MEMORY, exif_mem_alloc(), exif_mnote_data_pentax_clear(), _MnotePentaxEntry::format, _ExifMnoteData::log, _ExifMnoteData::mem, MNOTE_CASIO2_TAG_BASE, MNOTE_PENTAX2_TAG_BASE, mnote_pentax_tag_get_name(), _ExifMnoteDataPentax::offset, _ExifMnoteDataPentax::order, _MnotePentaxEntry::order, pentaxV1, pentaxV2, pentaxV3, _MnotePentaxEntry::size, _MnotePentaxEntry::tag, and _ExifMnoteDataPentax::version.
Referenced by exif_mnote_data_pentax_new().
exif_mnote_data_pentax_new()
ExifMnoteData * exif_mnote_data_pentax_new (ExifMem * mem)
Definition at line 452 of file exif-mnote-data-pentax.c.
References _ExifMnoteDataMethods::count, exif_mem_alloc(), exif_mnote_data_construct(), exif_mnote_data_pentax_count(), exif_mnote_data_pentax_free(), exif_mnote_data_pentax_get_description(), exif_mnote_data_pentax_get_id(), exif_mnote_data_pentax_get_name(), exif_mnote_data_pentax_get_title(), exif_mnote_data_pentax_get_value(), exif_mnote_data_pentax_load(), exif_mnote_data_pentax_save(), exif_mnote_data_pentax_set_byte_order(), exif_mnote_data_pentax_set_offset(), _ExifMnoteDataMethods::free, _ExifMnoteDataMethods::get_description, _ExifMnoteDataMethods::get_id, _ExifMnoteDataMethods::get_name, _ExifMnoteDataMethods::get_title, _ExifMnoteDataMethods::get_value, _ExifMnoteDataMethods::load, _ExifMnoteData::methods, _ExifMnoteDataMethods::save, _ExifMnoteDataMethods::set_byte_order, and _ExifMnoteDataMethods::set_offset.
Referenced by interpret_maker_note().
exif_mnote_data_pentax_save()
static void exif_mnote_data_pentax_save (ExifMnoteData * ne, unsigned char ** buf, unsigned int * buf_size) static
save the MnoteData from ne to buf
Parameters
ne extract the data from this structure
*buf write the mnoteData to this buffer (buffer will be allocated)
buf_size the final size of the buffer
Definition at line 81 of file exif-mnote-data-pentax.c.
References casioV2, _MnotePentaxEntry::components, _ExifMnoteDataPentax::count, _MnotePentaxEntry::data, _ExifMnoteDataPentax::entries, EXIF_BYTE_ORDER_INTEL, exif_format_get_size(), exif_log(), EXIF_LOG_CODE_CORRUPT_DATA, EXIF_LOG_NO_MEMORY, exif_mem_alloc(), exif_mem_realloc(), exif_set_long(), exif_set_short(), _MnotePentaxEntry::format, _ExifMnoteData::log, _ExifMnoteData::mem, MNOTE_PENTAX2_TAG_BASE, _ExifMnoteDataPentax::offset, _ExifMnoteDataPentax::order, pentaxV1, pentaxV2, pentaxV3, _MnotePentaxEntry::tag, and _ExifMnoteDataPentax::version.
Referenced by exif_mnote_data_pentax_new().
exif_mnote_data_pentax_set_byte_order()
static void exif_mnote_data_pentax_set_byte_order (ExifMnoteData * d, ExifByteOrder o) static
Definition at line 408 of file exif-mnote-data-pentax.c.
References _MnotePentaxEntry::components, _ExifMnoteDataPentax::count, _MnotePentaxEntry::data, _ExifMnoteDataPentax::entries, exif_array_set_byte_order(), exif_format_get_size(), _MnotePentaxEntry::format, _ExifMnoteDataPentax::order, _MnotePentaxEntry::order, and _MnotePentaxEntry::size.
Referenced by exif_mnote_data_pentax_new().
exif_mnote_data_pentax_set_offset()
static void exif_mnote_data_pentax_set_offset (ExifMnoteData * d, unsigned int o) static
Definition at line 402 of file exif-mnote-data-pentax.c.
Referenced by exif_mnote_data_pentax_new().
libexif Generated by