EXIF library (libexif) Internals: libexif/exif-mnote-data.c File Reference
exif-mnote-data.c File Reference
#include <config.h>
#include <libexif/exif-mnote-data.h>
#include <libexif/exif-mnote-data-priv.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct _ExifMnoteDataPriv
Functions
void exif_mnote_data_construct (ExifMnoteData *d, ExifMem *mem)
void exif_mnote_data_ref (ExifMnoteData *d)
static void exif_mnote_data_free (ExifMnoteData *d)
void exif_mnote_data_unref (ExifMnoteData *d)
void exif_mnote_data_load (ExifMnoteData *d, const unsigned char *buf, unsigned int buf_size)
Load the MakerNote data from a memory buffer.
void exif_mnote_data_save (ExifMnoteData *d, unsigned char **buf, unsigned int *buf_size)
Save the raw MakerNote data into a memory buffer.
void exif_mnote_data_set_byte_order (ExifMnoteData *d, ExifByteOrder o)
void exif_mnote_data_set_offset (ExifMnoteData *d, unsigned int o)
unsigned int exif_mnote_data_count (ExifMnoteData *d)
Return the number of tags in the MakerNote.
unsigned int exif_mnote_data_get_id (ExifMnoteData *d, unsigned int n)
Return the MakerNote tag number for the tag at the specified index within the MakerNote.
const char * exif_mnote_data_get_name (ExifMnoteData *d, unsigned int n)
Returns textual name of the given MakerNote tag.
const char * exif_mnote_data_get_title (ExifMnoteData *d, unsigned int n)
Returns textual title of the given MakerNote tag.
const char * exif_mnote_data_get_description (ExifMnoteData *d, unsigned int n)
Returns verbose textual description of the given MakerNote tag.
char * exif_mnote_data_get_value (ExifMnoteData *d, unsigned int n, char *val, unsigned int maxlen)
Return a textual representation of the value of the MakerNote entry.
void exif_mnote_data_log (ExifMnoteData *d, ExifLog *log)
Function Documentation
exif_mnote_data_construct()
void exif_mnote_data_construct (ExifMnoteData * d, ExifMem * mem)
Definition at line 37 of file exif-mnote-data.c.
References exif_mem_alloc(), exif_mem_ref(), _ExifMnoteData::mem, _ExifMnoteData::priv, and _ExifMnoteDataPriv::ref_count.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_fuji_new(), exif_mnote_data_olympus_new(), and exif_mnote_data_pentax_new().
exif_mnote_data_count()
unsigned int exif_mnote_data_count (ExifMnoteData * d)
Return the number of tags in the MakerNote.
Parameters
[in] d MakerNote data
Returns
number of tags, or 0 if no MakerNote or the type is not supported
Definition at line 112 of file exif-mnote-data.c.
References _ExifMnoteDataMethods::count, and _ExifMnoteData::methods.
Referenced by dump_makernote(), dump_makernote(), mnote_null_test(), test_exif_data(), test_exif_data(), and test_exif_data().
exif_mnote_data_free()
static void exif_mnote_data_free (ExifMnoteData * d) static
Definition at line 57 of file exif-mnote-data.c.
References exif_log_unref(), exif_mem_free(), exif_mem_unref(), _ExifMnoteDataMethods::free, _ExifMnoteData::log, _ExifMnoteData::mem, _ExifMnoteData::methods, and _ExifMnoteData::priv.
Referenced by exif_mnote_data_unref().
exif_mnote_data_get_description()
const char * exif_mnote_data_get_description (ExifMnoteData * d, unsigned int n)
Returns verbose textual description of the given MakerNote tag.
Parameters
[in] d MakerNote data
[in] n index of the entry within the MakerNote data
Returns
textual description of the tag or NULL on error
Definition at line 140 of file exif-mnote-data.c.
References _ExifMnoteDataMethods::get_description, and _ExifMnoteData::methods.
Referenced by mnote_null_test(), test_exif_data(), test_exif_data(), and test_exif_data().
exif_mnote_data_get_id()
unsigned int exif_mnote_data_get_id (ExifMnoteData * d, unsigned int n)
Return the MakerNote tag number for the tag at the specified index within the MakerNote.
Parameters
[in] d MakerNote data
[in] n index of the entry within the MakerNote data
Returns
MakerNote tag number
Definition at line 119 of file exif-mnote-data.c.
References _ExifMnoteDataMethods::get_id, and _ExifMnoteData::methods.
Referenced by dump_makernote(), dump_makernote(), and mnote_null_test().
exif_mnote_data_get_name()
const char * exif_mnote_data_get_name (ExifMnoteData * d, unsigned int n)
Returns textual name of the given MakerNote tag.
The name is a short, unique (within this type of MakerNote), non-localized text string containing only US-ASCII alphanumeric characters.
Parameters
[in] d MakerNote data
[in] n index of the entry within the MakerNote data
Returns
textual name of the tag or NULL on error
Definition at line 126 of file exif-mnote-data.c.
References _ExifMnoteDataMethods::get_name, and _ExifMnoteData::methods.
Referenced by dump_makernote(), dump_makernote(), mnote_null_test(), test_exif_data(), test_exif_data(), and test_exif_data().
exif_mnote_data_get_title()
const char * exif_mnote_data_get_title (ExifMnoteData * d, unsigned int n)
Returns textual title of the given MakerNote tag.
The title is a short, localized textual description of the tag.
Parameters
[in] d MakerNote data
[in] n index of the entry within the MakerNote data
Returns
textual name of the tag or NULL on error
Definition at line 133 of file exif-mnote-data.c.
References _ExifMnoteDataMethods::get_title, and _ExifMnoteData::methods.
Referenced by mnote_null_test(), test_exif_data(), test_exif_data(), and test_exif_data().
exif_mnote_data_get_value()
char * exif_mnote_data_get_value (ExifMnoteData * d, unsigned int n, char * val, unsigned int maxlen)
Return a textual representation of the value of the MakerNote entry.
Warning
The character set of the returned string may be in the encoding of the current locale or the native encoding of the camera.
Parameters
[in] d MakerNote data
[in] n index of the entry within the MakerNote data
[out] val buffer in which to store value
[in] maxlen length of the buffer val
Returns
val pointer, or NULL on error
Definition at line 147 of file exif-mnote-data.c.
References _ExifMnoteDataMethods::get_value, and _ExifMnoteData::methods.
Referenced by dump_makernote(), dump_makernote(), mnote_null_test(), test_exif_data(), test_exif_data(), and test_exif_data().
exif_mnote_data_load()
void exif_mnote_data_load (ExifMnoteData * d, const unsigned char * buf, unsigned int buf_size)
Load the MakerNote data from a memory buffer.
Parameters
[in] d MakerNote data
[in] buf pointer to raw MakerNote tag data
[in] buf_size number of bytes of data at buf
Definition at line 82 of file exif-mnote-data.c.
References _ExifMnoteDataMethods::load, and _ExifMnoteData::methods.
Referenced by interpret_maker_note(), and mnote_null_test().
exif_mnote_data_log()
void exif_mnote_data_log (ExifMnoteData * d, ExifLog * log)
Definition at line 154 of file exif-mnote-data.c.
References exif_log_ref(), exif_log_unref(), and _ExifMnoteData::log.
Referenced by interpret_maker_note(), and mnote_null_test().
exif_mnote_data_ref()
void exif_mnote_data_ref (ExifMnoteData * d)
Definition at line 51 of file exif-mnote-data.c.
References _ExifMnoteData::priv, and _ExifMnoteDataPriv::ref_count.
Referenced by mnote_null_test(), test_exif_data(), test_exif_data(), and test_exif_data().
exif_mnote_data_save()
void exif_mnote_data_save (ExifMnoteData * d, unsigned char ** buf, unsigned int * buf_size)
Save the raw MakerNote data into a memory buffer.
The buffer is allocated by this function and must subsequently be freed by the caller.
Parameters
[in,out] d extract the data from this structure
[out] buf pointer to buffer pointer containing MakerNote data on return
[out] buf_size pointer to the size of the buffer
Definition at line 90 of file exif-mnote-data.c.
References _ExifMnoteData::methods, and _ExifMnoteDataMethods::save.
Referenced by exif_data_save_data_entry(), and mnote_null_test().
exif_mnote_data_set_byte_order()
void exif_mnote_data_set_byte_order (ExifMnoteData * d, ExifByteOrder o)
Definition at line 98 of file exif-mnote-data.c.
References _ExifMnoteData::methods, and _ExifMnoteDataMethods::set_byte_order.
Referenced by exif_data_set_byte_order(), and interpret_maker_note().
exif_mnote_data_set_offset()
void exif_mnote_data_set_offset (ExifMnoteData * d, unsigned int o)
Definition at line 105 of file exif-mnote-data.c.
References _ExifMnoteData::methods, and _ExifMnoteDataMethods::set_offset.
Referenced by exif_data_save_data_entry(), and interpret_maker_note().
exif_mnote_data_unref()
void exif_mnote_data_unref (ExifMnoteData * d)
Definition at line 73 of file exif-mnote-data.c.
References exif_mnote_data_free(), _ExifMnoteData::priv, and _ExifMnoteDataPriv::ref_count.
Referenced by exif_data_free(), mnote_null_test(), test_exif_data(), test_exif_data(), and test_exif_data().
libexif Generated by