EXIF library (libexif) Internals: libexif/exif-ifd.c File Reference
exif-ifd.c File Reference
#include <config.h>
#include <libexif/exif-ifd.h>
#include <stdlib.h>
Functions
const char * exif_ifd_get_name (ExifIfd ifd)
Return a textual name of the given IFD.
Variables
struct {
ExifIfd ifd
const char * name
} ExifIfdTable []
Function Documentation
exif_ifd_get_name()
const char * exif_ifd_get_name (ExifIfd ifd)
Return a textual name of the given IFD.
The name is a short, unique, non-localized text string containing only US-ASCII alphanumeric characters.
Parameters
[in] ifd IFD
Returns
textual name of the IFD, or NULL if unknown
Definition at line 42 of file exif-ifd.c.
References ExifIfdTable, ifd, and name.
Referenced by exif_content_fix(), exif_data_dump(), exif_data_load_data_content(), exif_data_save_data_content(), and remove_not_recorded().
Variable Documentation
[struct]
const struct { ... } ExifIfdTable[]
Initial value:
= {
        {EXIF_IFD_0, "0"},
        {EXIF_IFD_1, "1"},
        {EXIF_IFD_EXIF, "EXIF"},
        {EXIF_IFD_GPS, "GPS"},
        {EXIF_IFD_INTEROPERABILITY, "Interoperability"},
        {0, NULL}
}
Referenced by exif_ifd_get_name().
ifd
ExifIfd ifd
Definition at line 30 of file exif-ifd.c.
Referenced by exif_content_fix(), exif_data_load_data_content(), exif_data_save_data_content(), exif_ifd_get_name(), exif_tag_get_description_in_ifd(), exif_tag_get_name_in_ifd(), exif_tag_get_support_level_in_ifd(), exif_tag_get_title_in_ifd(), get_support_level_any_type(), get_support_level_in_ifd(), and remove_not_recorded().
name
const char* name (void)
Definition at line 31 of file exif-ifd.c.
Referenced by exif_ifd_get_name().
libexif Generated by