EXIF library (libexif) Internals: libexif/canon/exif-mnote-data-canon.h File Reference
exif-mnote-data-canon.h File Reference
#include <libexif/exif-byte-order.h>
#include <libexif/exif-mnote-data.h>
#include <libexif/exif-mnote-data-priv.h>
#include <libexif/exif-mem.h>
#include <libexif/exif-data.h>
#include <libexif/canon/mnote-canon-entry.h>
Data Structures
struct _ExifMnoteDataCanon
Typedefs
typedef struct _ExifMnoteDataCanon ExifMnoteDataCanon
Functions
int exif_mnote_data_canon_identify (const ExifData *ed, const ExifEntry *e)
Detect if MakerNote is recognized as one handled by the Canon module.
ExifMnoteData * exif_mnote_data_canon_new (ExifMem *mem, ExifDataOption o)
Typedef Documentation
ExifMnoteDataCanon
typedef struct _ExifMnoteDataCanon ExifMnoteDataCanon
Definition at line 30 of file exif-mnote-data-canon.h.
Function Documentation
exif_mnote_data_canon_identify()
int exif_mnote_data_canon_identify (const ExifData * ed, const ExifEntry * e)
Detect if MakerNote is recognized as one handled by the Canon module.
Parameters
[in] ed image ExifData to identify as as a Canon type
[in] e ExifEntry for EXIF_TAG_MAKER_NOTE, from within ed but duplicated here for convenience
Returns
0 if not recognized, nonzero if recognized. The specific nonzero value returned may identify a subtype unique within this module.
Definition at line 350 of file exif-mnote-data-canon.c.
References exif_data_get_entry, exif_entry_get_value(), and EXIF_TAG_MAKE.
Referenced by interpret_maker_note().
exif_mnote_data_canon_new()
ExifMnoteData* exif_mnote_data_canon_new (ExifMem * mem, ExifDataOption o)
Definition at line 362 of file exif-mnote-data-canon.c.
References _ExifMnoteDataMethods::count, exif_mem_alloc(), exif_mnote_data_canon_count(), exif_mnote_data_canon_free(), exif_mnote_data_canon_get_description(), exif_mnote_data_canon_get_id(), exif_mnote_data_canon_get_name(), exif_mnote_data_canon_get_title(), exif_mnote_data_canon_get_value(), exif_mnote_data_canon_load(), exif_mnote_data_canon_save(), exif_mnote_data_canon_set_byte_order(), exif_mnote_data_canon_set_offset(), exif_mnote_data_construct(), _ExifMnoteDataMethods::free, _ExifMnoteDataMethods::get_description, _ExifMnoteDataMethods::get_id, _ExifMnoteDataMethods::get_name, _ExifMnoteDataMethods::get_title, _ExifMnoteDataMethods::get_value, _ExifMnoteDataMethods::load, _ExifMnoteData::methods, _ExifMnoteDataCanon::options, _ExifMnoteDataMethods::save, _ExifMnoteDataMethods::set_byte_order, and _ExifMnoteDataMethods::set_offset.
Referenced by interpret_maker_note().
libexif Generated by