EXIF library (libexif) Internals: libexif/exif-byte-order.c File Reference
exif-byte-order.c File Reference
#include <config.h>
#include <libexif/exif-byte-order.h>
#include <libexif/i18n.h>
#include <stdlib.h>
Functions
const char * exif_byte_order_get_name (ExifByteOrder order)
Return a short, localized, textual name for the given byte order.
Function Documentation
exif_byte_order_get_name()
const char * exif_byte_order_get_name (ExifByteOrder order)
Return a short, localized, textual name for the given byte order.
Parameters
[in] order byte order
Returns
localized textual name of the byte order, or NULL if unknown
Definition at line 31 of file exif-byte-order.c.
References _, EXIF_BYTE_ORDER_INTEL, and EXIF_BYTE_ORDER_MOTOROLA.
Referenced by test_exif_data(), test_exif_data(), test_exif_data(), test_parse(), and test_parse().
libexif Generated by