EXIF library (libexif) Internals: libexif/canon/exif-mnote-data-canon.c File Reference
exif-mnote-data-canon.c File Reference
#include <config.h>
#include "exif-mnote-data-canon.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <libexif/exif-byte-order.h>
#include <libexif/exif-utils.h>
#include <libexif/exif-data.h>
Macros
#define CHECKOVERFLOW(offset, datasize, structsize) (((offset) >= (datasize)) || ((structsize) > (datasize)) || ((offset) > (datasize) - (structsize)))
#define FAILSAFE_SIZE_MAX 1000000L
Functions
static void exif_mnote_data_canon_clear (ExifMnoteDataCanon *n)
static void exif_mnote_data_canon_free (ExifMnoteData *n)
static void exif_mnote_data_canon_get_tags (ExifMnoteDataCanon *dc, unsigned int n, unsigned int *m, unsigned int *s)
static char * exif_mnote_data_canon_get_value (ExifMnoteData *note, unsigned int n, char *val, unsigned int maxlen)
static void exif_mnote_data_canon_set_byte_order (ExifMnoteData *d, ExifByteOrder o)
static void exif_mnote_data_canon_set_offset (ExifMnoteData *n, unsigned int o)
static void exif_mnote_data_canon_save (ExifMnoteData *ne, unsigned char **buf, unsigned int *buf_size)
static void exif_mnote_data_canon_load (ExifMnoteData *ne, const unsigned char *buf, unsigned int buf_size)
static unsigned int exif_mnote_data_canon_count (ExifMnoteData *n)
static unsigned int exif_mnote_data_canon_get_id (ExifMnoteData *d, unsigned int i)
static const char * exif_mnote_data_canon_get_name (ExifMnoteData *note, unsigned int i)
static const char * exif_mnote_data_canon_get_title (ExifMnoteData *note, unsigned int i)
static const char * exif_mnote_data_canon_get_description (ExifMnoteData *note, unsigned int i)
int exif_mnote_data_canon_identify (const ExifData *ed, const ExifEntry *e)
Detect if MakerNote is recognized as one handled by the Canon module.
ExifMnoteData * exif_mnote_data_canon_new (ExifMem *mem, ExifDataOption o)
Macro Definition Documentation
CHECKOVERFLOW
#define CHECKOVERFLOW (offset, datasize, structsize) (((offset) >= (datasize)) || ((structsize) > (datasize)) || ((offset) > (datasize) - (structsize)))
Definition at line 35 of file exif-mnote-data-canon.c.
FAILSAFE_SIZE_MAX
#define FAILSAFE_SIZE_MAX 1000000L
Definition at line 38 of file exif-mnote-data-canon.c.
Function Documentation
exif_mnote_data_canon_clear()
static void exif_mnote_data_canon_clear (ExifMnoteDataCanon * n) static
Definition at line 41 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _MnoteCanonEntry::data, _ExifMnoteDataCanon::entries, exif_mem_free(), and _ExifMnoteData::mem.
Referenced by exif_mnote_data_canon_free(), and exif_mnote_data_canon_load().
exif_mnote_data_canon_count()
static unsigned int exif_mnote_data_canon_count (ExifMnoteData * n) static
Definition at line 340 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, and mnote_canon_entry_count_values().
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_free()
static void exif_mnote_data_canon_free (ExifMnoteData * n) static
Definition at line 61 of file exif-mnote-data-canon.c.
References exif_mnote_data_canon_clear().
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_get_description()
static const char * exif_mnote_data_canon_get_description (ExifMnoteData * note, unsigned int i) static
Definition at line 387 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, exif_mnote_data_canon_get_tags(), mnote_canon_tag_get_description(), and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_get_id()
static unsigned int exif_mnote_data_canon_get_id (ExifMnoteData * d, unsigned int i) static
Definition at line 351 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, exif_mnote_data_canon_get_tags(), and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_get_name()
static const char * exif_mnote_data_canon_get_name (ExifMnoteData * note, unsigned int i) static
Definition at line 363 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, exif_mnote_data_canon_get_tags(), mnote_canon_tag_get_name_sub(), _ExifMnoteDataCanon::options, and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_get_tags()
static void exif_mnote_data_canon_get_tags (ExifMnoteDataCanon * dc, unsigned int n, unsigned int * m, unsigned int * s) static
Definition at line 69 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, and mnote_canon_entry_count_values().
Referenced by exif_mnote_data_canon_get_description(), exif_mnote_data_canon_get_id(), exif_mnote_data_canon_get_name(), exif_mnote_data_canon_get_title(), and exif_mnote_data_canon_get_value().
exif_mnote_data_canon_get_title()
static const char * exif_mnote_data_canon_get_title (ExifMnoteData * note, unsigned int i) static
Definition at line 375 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, exif_mnote_data_canon_get_tags(), mnote_canon_tag_get_title_sub(), _ExifMnoteDataCanon::options, and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_get_value()
static char * exif_mnote_data_canon_get_value (ExifMnoteData * note, unsigned int n, char * val, unsigned int maxlen) static
Definition at line 88 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, exif_mnote_data_canon_get_tags(), and mnote_canon_entry_get_value().
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_identify()
int exif_mnote_data_canon_identify (const ExifData * ed, const ExifEntry * e)
Detect if MakerNote is recognized as one handled by the Canon module.
Parameters
[in] ed image ExifData to identify as as a Canon type
[in] e ExifEntry for EXIF_TAG_MAKER_NOTE, from within ed but duplicated here for convenience
Returns
0 if not recognized, nonzero if recognized. The specific nonzero value returned may identify a subtype unique within this module.
Definition at line 399 of file exif-mnote-data-canon.c.
References exif_data_get_entry, exif_entry_get_value(), and EXIF_TAG_MAKE.
Referenced by interpret_maker_note().
exif_mnote_data_canon_load()
static void exif_mnote_data_canon_load (ExifMnoteData * ne, const unsigned char * buf, unsigned int buf_size) static
Definition at line 208 of file exif-mnote-data-canon.c.
References CHECKOVERFLOW, _MnoteCanonEntry::components, _ExifMnoteDataCanon::count, _MnoteCanonEntry::data, _ExifMnoteDataCanon::entries, exif_format_get_size(), exif_get_long(), exif_get_short(), exif_log(), EXIF_LOG_CODE_CORRUPT_DATA, EXIF_LOG_CODE_DEBUG, EXIF_LOG_NO_MEMORY, exif_mem_alloc(), exif_mem_free(), exif_mnote_data_canon_clear(), FAILSAFE_SIZE_MAX, _MnoteCanonEntry::format, _ExifMnoteData::log, _ExifMnoteData::mem, mnote_canon_entry_count_values(), mnote_canon_tag_get_name(), _ExifMnoteDataCanon::offset, _ExifMnoteDataCanon::order, _MnoteCanonEntry::order, _MnoteCanonEntry::size, and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_new()
ExifMnoteData * exif_mnote_data_canon_new (ExifMem * mem, ExifDataOption o)
Definition at line 412 of file exif-mnote-data-canon.c.
References _ExifMnoteDataMethods::count, exif_mem_alloc(), exif_mnote_data_canon_count(), exif_mnote_data_canon_free(), exif_mnote_data_canon_get_description(), exif_mnote_data_canon_get_id(), exif_mnote_data_canon_get_name(), exif_mnote_data_canon_get_title(), exif_mnote_data_canon_get_value(), exif_mnote_data_canon_load(), exif_mnote_data_canon_save(), exif_mnote_data_canon_set_byte_order(), exif_mnote_data_canon_set_offset(), exif_mnote_data_construct(), _ExifMnoteDataMethods::free, _ExifMnoteDataMethods::get_description, _ExifMnoteDataMethods::get_id, _ExifMnoteDataMethods::get_name, _ExifMnoteDataMethods::get_title, _ExifMnoteDataMethods::get_value, _ExifMnoteDataMethods::load, _ExifMnoteData::methods, _ExifMnoteDataCanon::options, _ExifMnoteDataMethods::save, _ExifMnoteDataMethods::set_byte_order, and _ExifMnoteDataMethods::set_offset.
Referenced by interpret_maker_note().
exif_mnote_data_canon_save()
static void exif_mnote_data_canon_save (ExifMnoteData * ne, unsigned char ** buf, unsigned int * buf_size) static
Definition at line 126 of file exif-mnote-data-canon.c.
References _MnoteCanonEntry::components, _ExifMnoteDataCanon::count, _MnoteCanonEntry::data, _ExifMnoteDataCanon::entries, exif_format_get_size(), EXIF_LOG_NO_MEMORY, exif_mem_alloc(), exif_mem_realloc(), exif_set_long(), exif_set_short(), _MnoteCanonEntry::format, _ExifMnoteData::log, _ExifMnoteData::mem, _ExifMnoteDataCanon::offset, _ExifMnoteDataCanon::order, and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_set_byte_order()
static void exif_mnote_data_canon_set_byte_order (ExifMnoteData * d, ExifByteOrder o) static
Definition at line 100 of file exif-mnote-data-canon.c.
References _MnoteCanonEntry::components, _ExifMnoteDataCanon::count, _MnoteCanonEntry::data, _ExifMnoteDataCanon::entries, exif_array_set_byte_order(), exif_format_get_size(), _MnoteCanonEntry::format, _ExifMnoteDataCanon::order, _MnoteCanonEntry::order, and _MnoteCanonEntry::size.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_set_offset()
static void exif_mnote_data_canon_set_offset (ExifMnoteData * n, unsigned int o) static
Definition at line 120 of file exif-mnote-data-canon.c.
Referenced by exif_mnote_data_canon_new().
libexif Generated by