EXIF library (libexif) Internals: libexif/pentax/mnote-pentax-entry.h File Reference
mnote-pentax-entry.h File Reference
#include <libexif/exif-format.h>
#include <libexif/exif-byte-order.h>
#include <libexif/pentax/mnote-pentax-tag.h>
Data Structures
struct _MnotePentaxEntry
Typedefs
typedef struct _MnotePentaxEntry MnotePentaxEntry
Functions
char * mnote_pentax_entry_get_value (MnotePentaxEntry *entry, char *val, unsigned int maxlen)
Typedef Documentation
MnotePentaxEntry
typedef struct _MnotePentaxEntry MnotePentaxEntry
Definition at line 30 of file mnote-pentax-entry.h.
Function Documentation
mnote_pentax_entry_get_value()
char * mnote_pentax_entry_get_value (MnotePentaxEntry * entry, char * val, unsigned int maxlen)
Definition at line 310 of file mnote-pentax-entry.c.
References _, CC, CC2, CF, _MnotePentaxEntry::components, _MnotePentaxEntry::data, elem, EXIF_BYTE_ORDER_MOTOROLA, EXIF_FORMAT_ASCII, EXIF_FORMAT_LONG, EXIF_FORMAT_SHORT, EXIF_FORMAT_SLONG, EXIF_FORMAT_SSHORT, EXIF_FORMAT_UNDEFINED, exif_get_long(), exif_get_short(), exif_get_slong(), exif_get_sshort(), _MnotePentaxEntry::format, index, index1, index2, items, items2, MIN, MNOTE_CASIO2_TAG_BESTSHOT_MODE, MNOTE_PENTAX2_TAG_AFPOINT_SELECTED, MNOTE_PENTAX2_TAG_AUTO_AFPOINT, MNOTE_PENTAX2_TAG_DATE, MNOTE_PENTAX2_TAG_FLASH_MODE, MNOTE_PENTAX2_TAG_FOCUS_MODE, MNOTE_PENTAX2_TAG_IMAGE_SIZE, MNOTE_PENTAX2_TAG_MODE, MNOTE_PENTAX2_TAG_PICTURE_MODE, MNOTE_PENTAX2_TAG_QUALITY, MNOTE_PENTAX2_TAG_TIME, MNOTE_PENTAX2_TAG_WHITE_BALANCE, MNOTE_PENTAX_TAG_COLOR, MNOTE_PENTAX_TAG_CONTRAST, MNOTE_PENTAX_TAG_FLASH, MNOTE_PENTAX_TAG_FOCUS, MNOTE_PENTAX_TAG_ISO_SPEED, MNOTE_PENTAX_TAG_MODE, MNOTE_PENTAX_TAG_PRINTIM, MNOTE_PENTAX_TAG_QUALITY, MNOTE_PENTAX_TAG_SATURATION, MNOTE_PENTAX_TAG_SHARPNESS, MNOTE_PENTAX_TAG_TZ_CITY, MNOTE_PENTAX_TAG_TZ_DST, MNOTE_PENTAX_TAG_WHITE_BALANCE, MNOTE_PENTAX_TAG_ZOOM, _MnotePentaxEntry::order, _MnotePentaxEntry::size, tag, and _MnotePentaxEntry::tag.
Referenced by exif_mnote_data_pentax_get_value().
libexif Generated by