EXIF library (libexif) Internals: libexif/canon/mnote-canon-tag.h File Reference
mnote-canon-tag.h File Reference
#include <libexif/exif-data.h>
Typedefs
typedef enum _MnoteCanonTag MnoteCanonTag
Enumerations
enum _MnoteCanonTag {
MNOTE_CANON_TAG_UNKNOWN_0 = 0x0 , MNOTE_CANON_TAG_SETTINGS_1 = 0x1 , MNOTE_CANON_TAG_FOCAL_LENGTH = 0x2 , MNOTE_CANON_TAG_UNKNOWN_3 = 0x3 ,
MNOTE_CANON_TAG_SETTINGS_2 = 0x4 , MNOTE_CANON_TAG_PANORAMA = 0x5 , MNOTE_CANON_TAG_IMAGE_TYPE = 0x6 , MNOTE_CANON_TAG_FIRMWARE = 0x7 ,
MNOTE_CANON_TAG_IMAGE_NUMBER = 0x8 , MNOTE_CANON_TAG_OWNER = 0x9 , MNOTE_CANON_TAG_UNKNOWN_10 = 0xa , MNOTE_CANON_TAG_SERIAL_NUMBER = 0xc ,
MNOTE_CANON_TAG_CAMERA_INFO = 0xd , MNOTE_CANON_TAG_FILE_LENGTH = 0xe , MNOTE_CANON_TAG_CUSTOM_FUNCS = 0xf , MNOTE_CANON_TAG_MODEL_ID = 0x10 ,
MNOTE_CANON_TAG_MOVIE_INFO = 0x11 , MNOTE_CANON_TAG_AF_INFO = 0x12 , MNOTE_CANON_TAG_THUMBNAIL_VALID_AREA = 0x13 , MNOTE_CANON_TAG_SERIAL_NUMBER_FORMAT = 0x15 ,
MNOTE_CANON_TAG_SUPER_MACRO = 0x1a , MNOTE_CANON_TAG_DATE_STAMP_MODE = 0x1c , MNOTE_CANON_TAG_MY_COLORS = 0x1d , MNOTE_CANON_TAG_FIRMWARE_REVISION = 0x1e ,
MNOTE_CANON_TAG_CATEGORIES = 0x23 , MNOTE_CANON_TAG_FACEDETECT1 = 0x24 , MNOTE_CANON_TAG_FACEDETECT2 = 0x25 , MNOTE_CANON_TAG_AF_INFO2 = 0x26 ,
MNOTE_CANON_TAG_CONTRAST_INFO = 0x27 , MNOTE_CANON_TAG_IMAGE_UNIQUE_ID = 0x28 , MNOTE_CANON_TAG_WB_INFO = 0x29 , MNOTE_CANON_TAG_FACEDETECT3 = 0x2f ,
MNOTE_CANON_TAG_TIMEINFO = 0x35 , MNOTE_CANON_TAG_BATTERY_TYPE = 0x38 , MNOTE_CANON_TAG_AF_INFO3 = 0x3c , MNOTE_CANON_TAG_RAW_DATA_OFFSET = 0x81 ,
MNOTE_CANON_TAG_ORIGINAL_DECISION_DATA_OFFSET = 0x83 , MNOTE_CANON_TAG_PERSONAL_FUNCTIONS = 0x91 , MNOTE_CANON_TAG_PERSONAL_FUNCTIONS_VALUES = 0x92 , MNOTE_CANON_TAG_FILE_INFO = 0x93 ,
MNOTE_CANON_TAG_LENS_MODEL = 0x95 , MNOTE_CANON_TAG_CMOS_SERIAL = 0x96 , MNOTE_CANON_TAG_DUST_REMOVAL_DATA = 0x97 , MNOTE_CANON_TAG_CROP_INFO = 0x98 ,
MNOTE_CANON_TAG_CUSTOM_FUNCTIONS2 = 0x99 , MNOTE_CANON_TAG_ASPECT_INFO = 0x9a , MNOTE_CANON_TAG_COLOR_INFORMATION = 0xa0 , MNOTE_CANON_TAG_TONE_CURVE_TABLE = 0xa1 ,
MNOTE_CANON_TAG_SHARPNESS_TABLE = 0xa2 , MNOTE_CANON_TAG_SHARPNESS_FREQ_TABLE = 0xa3 , MNOTE_CANON_TAG_WHITEBALANCE_TABLE = 0xa3 , MNOTE_CANON_TAG_COLOR_BALANCE = 0xa9 ,
MNOTE_CANON_TAG_MEASURED_COLOR = 0xaa , MNOTE_CANON_TAG_COLOR_TEMPERATURE = 0xae , MNOTE_CANON_TAG_CANON_FLAGS = 0xb0 , MNOTE_CANON_TAG_MODIFIED_INFO = 0xb1 ,
MNOTE_CANON_TAG_TONECURVE_MATCHING = 0xb2 , MNOTE_CANON_TAG_WHITEBALANCE_MATCHING = 0xb3 , MNOTE_CANON_TAG_COLOR_SPACE = 0xb4 , MNOTE_CANON_TAG_PREVIEW_IMAGE_INFO = 0xb6 ,
MNOTE_CANON_TAG_VRD_OFFSET = 0xd0 , MNOTE_CANON_TAG_SENSOR_INFO = 0xe0 , MNOTE_CANON_TAG_WB_PACKET = 0x4001 , MNOTE_CANON_TAG_COLOR_INFO = 0x4003 ,
MNOTE_CANON_TAG_FLAVOR = 0x4005 , MNOTE_CANON_TAG_PICTURESTYLE_USERDEF = 0x4008 , MNOTE_CANON_TAG_PICTURESTYLE_PC = 0x4009 , MNOTE_CANON_TAG_CUSTOMPICTURE_STYLE_FN = 0x4010 ,
MNOTE_CANON_TAG_AF_MICRO_ADJUST = 0x4013 , MNOTE_CANON_TAG_VIGNETTING_CORRECT = 0x4015 , MNOTE_CANON_TAG_VIGNETTING_CORRECT2 = 0x4016 , MNOTE_CANON_TAG_LIGHTINGOPT = 0x4018 ,
MNOTE_CANON_TAG_LENS_INFO = 0x4019 , MNOTE_CANON_TAG_AMBIENCE_INFO = 0x4020 , MNOTE_CANON_TAG_MULTI_EXPOSURE = 0x4021 , MNOTE_CANON_TAG_FILTER_INFO = 0x4024 ,
MNOTE_CANON_TAG_HDR_INFO = 0x4025 , MNOTE_CANON_TAG_AF_CONFIG = 0x4028 , MNOTE_CANON_TAG_RAW_BURST_INFO = 0x403f
}
Functions
const char * mnote_canon_tag_get_name (MnoteCanonTag)
const char * mnote_canon_tag_get_name_sub (MnoteCanonTag, unsigned int, ExifDataOption)
const char * mnote_canon_tag_get_title (MnoteCanonTag)
const char * mnote_canon_tag_get_title_sub (MnoteCanonTag, unsigned int, ExifDataOption)
const char * mnote_canon_tag_get_description (MnoteCanonTag)
Typedef Documentation
MnoteCanonTag
typedef enum _MnoteCanonTag MnoteCanonTag
Definition at line 1 of file mnote-canon-tag.h.
Enumeration Type Documentation
_MnoteCanonTag
enum _MnoteCanonTag
Enumerator
MNOTE_CANON_TAG_UNKNOWN_0
MNOTE_CANON_TAG_SETTINGS_1
MNOTE_CANON_TAG_FOCAL_LENGTH
MNOTE_CANON_TAG_UNKNOWN_3
MNOTE_CANON_TAG_SETTINGS_2
MNOTE_CANON_TAG_PANORAMA
MNOTE_CANON_TAG_IMAGE_TYPE
MNOTE_CANON_TAG_FIRMWARE
MNOTE_CANON_TAG_IMAGE_NUMBER
MNOTE_CANON_TAG_OWNER
MNOTE_CANON_TAG_UNKNOWN_10
MNOTE_CANON_TAG_SERIAL_NUMBER
MNOTE_CANON_TAG_CAMERA_INFO
MNOTE_CANON_TAG_FILE_LENGTH
MNOTE_CANON_TAG_CUSTOM_FUNCS
MNOTE_CANON_TAG_MODEL_ID
MNOTE_CANON_TAG_MOVIE_INFO
MNOTE_CANON_TAG_AF_INFO
MNOTE_CANON_TAG_THUMBNAIL_VALID_AREA
MNOTE_CANON_TAG_SERIAL_NUMBER_FORMAT
MNOTE_CANON_TAG_SUPER_MACRO
MNOTE_CANON_TAG_DATE_STAMP_MODE
MNOTE_CANON_TAG_MY_COLORS
MNOTE_CANON_TAG_FIRMWARE_REVISION
MNOTE_CANON_TAG_CATEGORIES
MNOTE_CANON_TAG_FACEDETECT1
MNOTE_CANON_TAG_FACEDETECT2
MNOTE_CANON_TAG_AF_INFO2
MNOTE_CANON_TAG_CONTRAST_INFO
MNOTE_CANON_TAG_IMAGE_UNIQUE_ID
MNOTE_CANON_TAG_WB_INFO
MNOTE_CANON_TAG_FACEDETECT3
MNOTE_CANON_TAG_TIMEINFO
MNOTE_CANON_TAG_BATTERY_TYPE
MNOTE_CANON_TAG_AF_INFO3
MNOTE_CANON_TAG_RAW_DATA_OFFSET
MNOTE_CANON_TAG_ORIGINAL_DECISION_DATA_OFFSET
MNOTE_CANON_TAG_PERSONAL_FUNCTIONS
MNOTE_CANON_TAG_PERSONAL_FUNCTIONS_VALUES
MNOTE_CANON_TAG_FILE_INFO
MNOTE_CANON_TAG_LENS_MODEL
MNOTE_CANON_TAG_CMOS_SERIAL
MNOTE_CANON_TAG_DUST_REMOVAL_DATA
MNOTE_CANON_TAG_CROP_INFO
MNOTE_CANON_TAG_CUSTOM_FUNCTIONS2
MNOTE_CANON_TAG_ASPECT_INFO
MNOTE_CANON_TAG_COLOR_INFORMATION
MNOTE_CANON_TAG_TONE_CURVE_TABLE
MNOTE_CANON_TAG_SHARPNESS_TABLE
MNOTE_CANON_TAG_SHARPNESS_FREQ_TABLE
MNOTE_CANON_TAG_WHITEBALANCE_TABLE
MNOTE_CANON_TAG_COLOR_BALANCE
MNOTE_CANON_TAG_MEASURED_COLOR
MNOTE_CANON_TAG_COLOR_TEMPERATURE
MNOTE_CANON_TAG_CANON_FLAGS
MNOTE_CANON_TAG_MODIFIED_INFO
MNOTE_CANON_TAG_TONECURVE_MATCHING
MNOTE_CANON_TAG_WHITEBALANCE_MATCHING
MNOTE_CANON_TAG_COLOR_SPACE
MNOTE_CANON_TAG_PREVIEW_IMAGE_INFO
MNOTE_CANON_TAG_VRD_OFFSET
MNOTE_CANON_TAG_SENSOR_INFO
MNOTE_CANON_TAG_WB_PACKET
MNOTE_CANON_TAG_COLOR_INFO
MNOTE_CANON_TAG_FLAVOR
MNOTE_CANON_TAG_PICTURESTYLE_USERDEF
MNOTE_CANON_TAG_PICTURESTYLE_PC
MNOTE_CANON_TAG_CUSTOMPICTURE_STYLE_FN
MNOTE_CANON_TAG_AF_MICRO_ADJUST
MNOTE_CANON_TAG_VIGNETTING_CORRECT
MNOTE_CANON_TAG_VIGNETTING_CORRECT2
MNOTE_CANON_TAG_LIGHTINGOPT
MNOTE_CANON_TAG_LENS_INFO
MNOTE_CANON_TAG_AMBIENCE_INFO
MNOTE_CANON_TAG_MULTI_EXPOSURE
MNOTE_CANON_TAG_FILTER_INFO
MNOTE_CANON_TAG_HDR_INFO
MNOTE_CANON_TAG_AF_CONFIG
MNOTE_CANON_TAG_RAW_BURST_INFO
Definition at line 30 of file mnote-canon-tag.h.
Function Documentation
mnote_canon_tag_get_description()
const char* mnote_canon_tag_get_description (MnoteCanonTag t)
Definition at line 268 of file mnote-canon-tag.c.
References _, bindtextdomain, description, table, and tag.
Referenced by exif_mnote_data_canon_get_description().
mnote_canon_tag_get_name()
const char* mnote_canon_tag_get_name (MnoteCanonTag t)
Definition at line 209 of file mnote-canon-tag.c.
References table, and tag.
Referenced by exif_mnote_data_canon_load(), and mnote_canon_tag_get_name_sub().
mnote_canon_tag_get_name_sub()
const char* mnote_canon_tag_get_name_sub (MnoteCanonTag t, unsigned int s, ExifDataOption o)
Definition at line 219 of file mnote-canon-tag.c.
References EXIF_DATA_OPTION_IGNORE_UNKNOWN_TAGS, mnote_canon_tag_get_name(), subtag, table_sub, and tag.
Referenced by exif_mnote_data_canon_get_name().
mnote_canon_tag_get_title()
const char* mnote_canon_tag_get_title (MnoteCanonTag t)
Definition at line 238 of file mnote-canon-tag.c.
References _, bindtextdomain, table, tag, and title.
Referenced by mnote_canon_tag_get_title_sub().
mnote_canon_tag_get_title_sub()
const char* mnote_canon_tag_get_title_sub (MnoteCanonTag t, unsigned int s, ExifDataOption o)
Definition at line 249 of file mnote-canon-tag.c.
References _, EXIF_DATA_OPTION_IGNORE_UNKNOWN_TAGS, mnote_canon_tag_get_title(), name, subtag, table_sub, and tag.
Referenced by exif_mnote_data_canon_get_title().
libexif Generated by