EXIF library (libexif) Internals: libexif/apple/mnote-apple-entry.h File Reference
mnote-apple-entry.h File Reference
#include <libexif/exif-byte-order.h>
#include <libexif/exif-format.h>
#include <libexif/apple/mnote-apple-tag.h>
Data Structures
struct _MnoteAppleEntry
Typedefs
typedef struct _MnoteAppleEntry MnoteAppleEntry
Functions
char * mnote_apple_entry_get_value (MnoteAppleEntry *, char *, unsigned int)
Typedef Documentation
MnoteAppleEntry
typedef struct _MnoteAppleEntry MnoteAppleEntry
Definition at line 1 of file mnote-apple-entry.h.
Function Documentation
mnote_apple_entry_get_value()
char* mnote_apple_entry_get_value (MnoteAppleEntry * entry, char * v, unsigned int maxlen)
Definition at line 34 of file mnote-apple-entry.c.
References _, _MnoteAppleEntry::components, _MnoteAppleEntry::data, ExifRational::denominator, ExifSRational::denominator, EXIF_FORMAT_ASCII, exif_format_get_size(), EXIF_FORMAT_LONG, EXIF_FORMAT_RATIONAL, EXIF_FORMAT_SHORT, EXIF_FORMAT_SLONG, EXIF_FORMAT_SRATIONAL, EXIF_FORMAT_SSHORT, EXIF_FORMAT_UNDEFINED, exif_get_long(), exif_get_rational(), exif_get_short(), exif_get_slong(), exif_get_srational(), exif_get_sshort(), _MnoteAppleEntry::format, MIN, MNOTE_APPLE_TAG_BURST_UUID, MNOTE_APPLE_TAG_HDR, MNOTE_APPLE_TAG_IMAGE_UNIQUE_ID, MNOTE_APPLE_TAG_MEDIA_GROUP_UUID, ExifRational::numerator, ExifSRational::numerator, _MnoteAppleEntry::order, _MnoteAppleEntry::size, size, and _MnoteAppleEntry::tag.
Referenced by exif_mnote_data_apple_get_value().
libexif Generated by