EXIF library (libexif) Internals: libexif/pentax/mnote-pentax-tag.c File Reference
mnote-pentax-tag.c File Reference
#include <config.h>
#include "mnote-pentax-tag.h"
#include <stdlib.h>
#include <libexif/i18n.h>
Functions
const char * mnote_pentax_tag_get_name (MnotePentaxTag t)
const char * mnote_pentax_tag_get_title (MnotePentaxTag t)
const char * mnote_pentax_tag_get_description (MnotePentaxTag t)
Variables
struct {
MnotePentaxTag tag
const char * name
const char * title
const char * description
} table []
Function Documentation
mnote_pentax_tag_get_description()
const char* mnote_pentax_tag_get_description (MnotePentaxTag t)
Definition at line 163 of file mnote-pentax-tag.c.
References _, bindtextdomain, description, table, and tag.
Referenced by exif_mnote_data_pentax_get_description().
mnote_pentax_tag_get_name()
const char* mnote_pentax_tag_get_name (MnotePentaxTag t)
Definition at line 142 of file mnote-pentax-tag.c.
References name, table, and tag.
Referenced by exif_mnote_data_pentax_get_name(), and exif_mnote_data_pentax_load().
mnote_pentax_tag_get_title()
const char* mnote_pentax_tag_get_title (MnotePentaxTag t)
Definition at line 152 of file mnote-pentax-tag.c.
References _, bindtextdomain, table, tag, and title.
Referenced by exif_mnote_data_pentax_get_title().
Variable Documentation
description
const char* description
Definition at line 32 of file mnote-pentax-tag.c.
Referenced by mnote_pentax_tag_get_description().
name
const char* name (void)
Definition at line 30 of file mnote-pentax-tag.c.
Referenced by mnote_pentax_tag_get_name().
const { ... } table[]
Referenced by mnote_pentax_tag_get_description(), mnote_pentax_tag_get_name(), and mnote_pentax_tag_get_title().
tag
MnotePentaxTag tag
Definition at line 29 of file mnote-pentax-tag.c.
Referenced by mnote_pentax_tag_get_description(), mnote_pentax_tag_get_name(), and mnote_pentax_tag_get_title().
title
const char* title
Definition at line 31 of file mnote-pentax-tag.c.
Referenced by mnote_pentax_tag_get_title().
libexif Generated by