EXIF library (libexif) Internals: libexif/fuji/mnote-fuji-entry.h File Reference
mnote-fuji-entry.h File Reference
#include <libexif/exif-format.h>
#include <libexif/fuji/mnote-fuji-tag.h>
#include <libexif/fuji/exif-mnote-data-fuji.h>
Data Structures
struct _MnoteFujiEntry
Typedefs
typedef struct _MnoteFujiEntry MnoteFujiEntry
typedef struct _MnoteFujiEntryPrivate MnoteFujiEntryPrivate
Functions
char * mnote_fuji_entry_get_value (MnoteFujiEntry *entry, char *val, unsigned int maxlen)
Typedef Documentation
MnoteFujiEntry
typedef struct _MnoteFujiEntry MnoteFujiEntry
Definition at line 1 of file mnote-fuji-entry.h.
MnoteFujiEntryPrivate
typedef struct _MnoteFujiEntryPrivate MnoteFujiEntryPrivate
Definition at line 1 of file mnote-fuji-entry.h.
Function Documentation
mnote_fuji_entry_get_value()
char* mnote_fuji_entry_get_value (MnoteFujiEntry * entry, char * val, unsigned int maxlen)
Definition at line 190 of file mnote-fuji-entry.c.
References _, CC, CF, _MnoteFujiEntry::components, _MnoteFujiEntry::data, ExifRational::denominator, ExifSRational::denominator, elem, EXIF_FORMAT_ASCII, EXIF_FORMAT_LONG, EXIF_FORMAT_RATIONAL, EXIF_FORMAT_SHORT, EXIF_FORMAT_SLONG, EXIF_FORMAT_SRATIONAL, EXIF_FORMAT_SSHORT, EXIF_FORMAT_UNDEFINED, exif_get_long(), exif_get_rational(), exif_get_short(), exif_get_slong(), exif_get_srational(), exif_get_sshort(), _MnoteFujiEntry::format, index, items, MIN, MNOTE_FUJI_TAG_AUTO_EXPOSURE_CHECK, MNOTE_FUJI_TAG_BLUR_CHECK, MNOTE_FUJI_TAG_COLOR, MNOTE_FUJI_TAG_CONT_TAKING, MNOTE_FUJI_TAG_DYNAMIC_RANGE, MNOTE_FUJI_TAG_DYNAMIC_RANGE_SETTING, MNOTE_FUJI_TAG_FILM_MODE, MNOTE_FUJI_TAG_FINEPIX_COLOR, MNOTE_FUJI_TAG_FLASH_MODE, MNOTE_FUJI_TAG_FOCUS_CHECK, MNOTE_FUJI_TAG_FOCUS_MODE, MNOTE_FUJI_TAG_FOCUS_POINT, MNOTE_FUJI_TAG_MACRO, MNOTE_FUJI_TAG_MAX_FOCAL_LENGTH, MNOTE_FUJI_TAG_MIN_FOCAL_LENGTH, MNOTE_FUJI_TAG_PICTURE_MODE, MNOTE_FUJI_TAG_SHARPNESS, MNOTE_FUJI_TAG_SLOW_SYNC, MNOTE_FUJI_TAG_TONE, MNOTE_FUJI_TAG_VERSION, MNOTE_FUJI_TAG_WHITE_BALANCE, ExifRational::numerator, ExifSRational::numerator, _MnoteFujiEntry::order, _MnoteFujiEntry::size, tag, and _MnoteFujiEntry::tag.
Referenced by exif_mnote_data_fuji_get_value().
libexif Generated by