EXIF library (libexif) Internals: libexif/fuji/mnote-fuji-tag.c File Reference
libexif » fuji
mnote-fuji-tag.c File Reference
#include <stdlib.h>
#include <config.h>
#include <libexif/i18n.h>
#include "mnote-fuji-tag.h"
Functions
const char * mnote_fuji_tag_get_name (MnoteFujiTag t)
const char * mnote_fuji_tag_get_title (MnoteFujiTag t)
const char * mnote_fuji_tag_get_description (MnoteFujiTag t)
Variables
struct {
MnoteFujiTag tag
const char * name
const char * title
const char * description
} table []
Function Documentation
const char* mnote_fuji_tag_get_description (MnoteFujiTag t)
Definition at line 93 of file mnote-fuji-tag.c.
Referenced by exif_mnote_data_fuji_get_description().
const char* mnote_fuji_tag_get_name (MnoteFujiTag t)
Definition at line 72 of file mnote-fuji-tag.c.
Referenced by exif_mnote_data_fuji_get_name(), and exif_mnote_data_fuji_load().
const char* mnote_fuji_tag_get_title (MnoteFujiTag t)
Definition at line 82 of file mnote-fuji-tag.c.
Referenced by exif_mnote_data_fuji_get_title().
Variable Documentation
const char* description
Definition at line 33 of file mnote-fuji-tag.c.
const char* name
Definition at line 31 of file mnote-fuji-tag.c.
struct { ... } table[] [static]
MnoteFujiTag tag
Definition at line 30 of file mnote-fuji-tag.c.
const char* title
Definition at line 32 of file mnote-fuji-tag.c.
Generated by