EXIF library (libexif) Internals: libexif/apple/mnote-apple-tag.h File Reference
mnote-apple-tag.h File Reference
Typedefs
typedef enum _MnoteAppleTag MnoteAppleTag
Enumerations
enum _MnoteAppleTag {
MNOTE_APPLE_TAG_RUNTIME = 0x3 , MNOTE_APPLE_TAG_ACCELERATION_VECTOR = 0x9 , MNOTE_APPLE_TAG_HDR = 0xA , MNOTE_APPLE_TAG_BURST_UUID = 0xB ,
MNOTE_APPLE_TAG_MEDIA_GROUP_UUID = 0x11 , MNOTE_APPLE_TAG_IMAGE_UNIQUE_ID = 0x15
}
Functions
const char * mnote_apple_tag_get_name (MnoteAppleTag)
const char * mnote_apple_tag_get_title (MnoteAppleTag)
const char * mnote_apple_tag_get_description (MnoteAppleTag)
Typedef Documentation
MnoteAppleTag
typedef enum _MnoteAppleTag MnoteAppleTag
Definition at line 38 of file mnote-apple-tag.h.
Enumeration Type Documentation
_MnoteAppleTag
enum _MnoteAppleTag
Enumerator
MNOTE_APPLE_TAG_RUNTIME
MNOTE_APPLE_TAG_ACCELERATION_VECTOR
MNOTE_APPLE_TAG_HDR
MNOTE_APPLE_TAG_BURST_UUID
MNOTE_APPLE_TAG_MEDIA_GROUP_UUID
MNOTE_APPLE_TAG_IMAGE_UNIQUE_ID
Definition at line 30 of file mnote-apple-tag.h.
Function Documentation
mnote_apple_tag_get_description()
const char * mnote_apple_tag_get_description (MnoteAppleTag t)
Definition at line 79 of file mnote-apple-tag.c.
References _, bindtextdomain, description, table, and tag.
Referenced by exif_mnote_data_apple_get_description().
mnote_apple_tag_get_name()
const char * mnote_apple_tag_get_name (MnoteAppleTag t)
Definition at line 50 of file mnote-apple-tag.c.
References table, and tag.
Referenced by exif_mnote_data_apple_get_name().
mnote_apple_tag_get_title()
const char * mnote_apple_tag_get_title (MnoteAppleTag t)
Definition at line 63 of file mnote-apple-tag.c.
References _, bindtextdomain, table, tag, and title.
Referenced by exif_mnote_data_apple_get_title().
libexif Generated by