EXIF library (libexif) Internals: libexif/pentax/mnote-pentax-entry.c File Reference
mnote-pentax-entry.c File Reference
#include <config.h>
#include "mnote-pentax-entry.h"
#include <libexif/i18n.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libexif/exif-format.h>
#include <libexif/exif-utils.h>
#include <libexif/exif-entry.h>
Macros
#define CF(format, target, v, maxlen)
#define CC(number, target, v, maxlen)
#define CC2(number, t1, t2, v, maxlen)
Functions
char * mnote_pentax_entry_get_value (MnotePentaxEntry *entry, char *val, unsigned int maxlen)
Variables
struct {
MnotePentaxTag tag
struct {
int index
const char * string
} elem [33]
} items []
struct {
MnotePentaxTag tag
struct {
int index1
int index2
const char * string
} elem [39]
} items2 []
Macro Definition Documentation
CC
#define CC (number, target, v, maxlen)
Value:
{                                                                       \
        if (number != target) {                                         \
                snprintf (v, maxlen,                                    \
                        _("Invalid number of components (%i, "          \
                        "expected %i)."), (int) number, (int) target);  \
                break;                                                  \
        }                                                               \
}
Definition at line 47 of file mnote-pentax-entry.c.
CC2
#define CC2 (number, t1, t2, v, maxlen)
Value:
{                                                                       \
        if ((number != t1) && (number != t2)) {                         \
                snprintf (v, maxlen,                                    \
                        _("Invalid number of components (%i, "          \
                        "expected %i or %i)."), (int) number,           \
                        (int) t1, (int) t2);                            \
                break;                                                  \
        }                                                               \
}
Definition at line 57 of file mnote-pentax-entry.c.
CF
#define CF (format, target, v, maxlen)
Value:
{                                                               \
        if (format != target) {                                 \
                snprintf (v, maxlen,                            \
                        _("Invalid format '%s', "               \
                        "expected '%s'."),                      \
                        exif_format_get_name (format),          \
                        exif_format_get_name (target));         \
                break;                                          \
        }                                                       \
}
Definition at line 35 of file mnote-pentax-entry.c.
Function Documentation
mnote_pentax_entry_get_value()
char* mnote_pentax_entry_get_value (MnotePentaxEntry * entry, char * val, unsigned int maxlen)
Definition at line 308 of file mnote-pentax-entry.c.
References _, CC, CC2, CF, _MnotePentaxEntry::components, _MnotePentaxEntry::data, elem, EXIF_BYTE_ORDER_MOTOROLA, EXIF_FORMAT_ASCII, EXIF_FORMAT_LONG, EXIF_FORMAT_SHORT, EXIF_FORMAT_SLONG, EXIF_FORMAT_SSHORT, EXIF_FORMAT_UNDEFINED, exif_get_long(), exif_get_short(), exif_get_slong(), exif_get_sshort(), _MnotePentaxEntry::format, index, index1, index2, items, items2, MIN, MNOTE_CASIO2_TAG_BESTSHOT_MODE, MNOTE_PENTAX2_TAG_AFPOINT_SELECTED, MNOTE_PENTAX2_TAG_AUTO_AFPOINT, MNOTE_PENTAX2_TAG_DATE, MNOTE_PENTAX2_TAG_FLASH_MODE, MNOTE_PENTAX2_TAG_FOCUS_MODE, MNOTE_PENTAX2_TAG_IMAGE_SIZE, MNOTE_PENTAX2_TAG_MODE, MNOTE_PENTAX2_TAG_PICTURE_MODE, MNOTE_PENTAX2_TAG_QUALITY, MNOTE_PENTAX2_TAG_TIME, MNOTE_PENTAX2_TAG_WHITE_BALANCE, MNOTE_PENTAX_TAG_COLOR, MNOTE_PENTAX_TAG_CONTRAST, MNOTE_PENTAX_TAG_FLASH, MNOTE_PENTAX_TAG_FOCUS, MNOTE_PENTAX_TAG_ISO_SPEED, MNOTE_PENTAX_TAG_MODE, MNOTE_PENTAX_TAG_PRINTIM, MNOTE_PENTAX_TAG_QUALITY, MNOTE_PENTAX_TAG_SATURATION, MNOTE_PENTAX_TAG_SHARPNESS, MNOTE_PENTAX_TAG_TZ_CITY, MNOTE_PENTAX_TAG_TZ_DST, MNOTE_PENTAX_TAG_WHITE_BALANCE, MNOTE_PENTAX_TAG_ZOOM, _MnotePentaxEntry::order, _MnotePentaxEntry::size, tag, and _MnotePentaxEntry::tag.
Referenced by exif_mnote_data_pentax_get_value().
Variable Documentation
struct { ... } elem[39]
Referenced by mnote_pentax_entry_get_value().
index
int index
Definition at line 71 of file mnote-pentax-entry.c.
Referenced by mnote_pentax_entry_get_value().
index1
int index1
Definition at line 271 of file mnote-pentax-entry.c.
Referenced by mnote_pentax_entry_get_value().
index2
int index2
Definition at line 271 of file mnote-pentax-entry.c.
Referenced by mnote_pentax_entry_get_value().
const { ... } items[]
Referenced by mnote_pentax_entry_get_value().
const { ... } items2[]
Referenced by mnote_pentax_entry_get_value().
string
const char* string
Definition at line 72 of file mnote-pentax-entry.c.
tag
MnotePentaxTag tag
Definition at line 69 of file mnote-pentax-entry.c.
Referenced by mnote_pentax_entry_get_value().
libexif Generated by