EXIF library (libexif) Internals: libexif/canon/mnote-canon-entry.h File Reference
mnote-canon-entry.h File Reference
#include <libexif/exif-format.h>
#include <libexif/exif-byte-order.h>
#include <libexif/canon/mnote-canon-tag.h>
Data Structures
struct _MnoteCanonEntry
Typedefs
typedef struct _MnoteCanonEntry MnoteCanonEntry
Functions
unsigned int mnote_canon_entry_count_values (const MnoteCanonEntry *)
char * mnote_canon_entry_get_value (const MnoteCanonEntry *, unsigned int t, char *val, unsigned int maxlen)
Typedef Documentation
MnoteCanonEntry
typedef struct _MnoteCanonEntry MnoteCanonEntry
Definition at line 1 of file mnote-canon-entry.h.
Function Documentation
mnote_canon_entry_count_values()
unsigned int mnote_canon_entry_count_values (const MnoteCanonEntry * entry)
Definition at line 502 of file mnote-canon-entry.c.
References _MnoteCanonEntry::components, _MnoteCanonEntry::data, EXIF_FORMAT_SHORT, exif_get_short(), _MnoteCanonEntry::format, MIN, MNOTE_CANON_TAG_COLOR_INFORMATION, MNOTE_CANON_TAG_CUSTOM_FUNCS, MNOTE_CANON_TAG_FOCAL_LENGTH, MNOTE_CANON_TAG_PANORAMA, MNOTE_CANON_TAG_SETTINGS_1, MNOTE_CANON_TAG_SETTINGS_2, _MnoteCanonEntry::order, _MnoteCanonEntry::size, and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_count(), exif_mnote_data_canon_get_tags(), and exif_mnote_data_canon_load().
mnote_canon_entry_get_value()
char* mnote_canon_entry_get_value (const MnoteCanonEntry * entry, unsigned int t, char * val, unsigned int maxlen)
Definition at line 549 of file mnote-canon-entry.c.
References _, apex_value_to_aperture(), apex_value_to_iso_speed(), apex_value_to_shutter_speed(), canon_search_table_bitfield(), canon_search_table_value(), CC, CF, color_information, _MnoteCanonEntry::components, _MnoteCanonEntry::data, entries_focal_length, entries_panorama, entries_settings_1, entries_settings_2, EXIF_FORMAT_ASCII, EXIF_FORMAT_LONG, EXIF_FORMAT_SHORT, EXIF_FORMAT_SLONG, EXIF_FORMAT_SSHORT, exif_get_long(), exif_get_short(), exif_get_slong(), exif_get_sshort(), _MnoteCanonEntry::format, MIN, MNOTE_CANON_TAG_COLOR_INFORMATION, MNOTE_CANON_TAG_CUSTOM_FUNCS, MNOTE_CANON_TAG_FIRMWARE, MNOTE_CANON_TAG_FOCAL_LENGTH, MNOTE_CANON_TAG_IMAGE_NUMBER, MNOTE_CANON_TAG_IMAGE_TYPE, MNOTE_CANON_TAG_OWNER, MNOTE_CANON_TAG_PANORAMA, MNOTE_CANON_TAG_SERIAL_NUMBER, MNOTE_CANON_TAG_SETTINGS_1, MNOTE_CANON_TAG_SETTINGS_2, _MnoteCanonEntry::order, _MnoteCanonEntry::size, size, and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_get_value().
libexif Generated by