EXIF library (libexif) Internals: libexif/fuji/mnote-fuji-tag.h File Reference
mnote-fuji-tag.h File Reference
#include <libexif/exif-data.h>
Typedefs
typedef enum _MnoteFujiTag MnoteFujiTag
Enumerations
enum _MnoteFujiTag {
MNOTE_FUJI_TAG_VERSION = 0x0000 , MNOTE_FUJI_TAG_SERIAL_NUMBER = 0x0010 , MNOTE_FUJI_TAG_QUALITY = 0x1000 , MNOTE_FUJI_TAG_SHARPNESS = 0x1001 ,
MNOTE_FUJI_TAG_WHITE_BALANCE = 0x1002 , MNOTE_FUJI_TAG_COLOR = 0x1003 , MNOTE_FUJI_TAG_TONE = 0x1004 , MNOTE_FUJI_TAG_UNKNOWN_1006 = 0x1006 ,
MNOTE_FUJI_TAG_UNKNOWN_1007 = 0x1007 , MNOTE_FUJI_TAG_UNKNOWN_1008 = 0x1008 , MNOTE_FUJI_TAG_UNKNOWN_1009 = 0x1009 , MNOTE_FUJI_TAG_UNKNOWN_100A = 0x100A ,
MNOTE_FUJI_TAG_UNKNOWN_100B = 0x100B , MNOTE_FUJI_TAG_FLASH_MODE = 0x1010 , MNOTE_FUJI_TAG_FLASH_STRENGTH = 0x1011 , MNOTE_FUJI_TAG_MACRO = 0x1020 ,
MNOTE_FUJI_TAG_FOCUS_MODE = 0x1021 , MNOTE_FUJI_TAG_UNKNOWN_1022 = 0x1022 , MNOTE_FUJI_TAG_FOCUS_POINT = 0x1023 , MNOTE_FUJI_TAG_UNKNOWN_1024 = 0x1024 ,
MNOTE_FUJI_TAG_UNKNOWN_1025 = 0x1025 , MNOTE_FUJI_TAG_SLOW_SYNC = 0x1030 , MNOTE_FUJI_TAG_PICTURE_MODE = 0x1031 , MNOTE_FUJI_TAG_UNKNOWN_1032 = 0x1032 ,
MNOTE_FUJI_TAG_CONT_TAKING = 0x1100 , MNOTE_FUJI_TAG_SEQUENCE_NUMBER = 0x1101 , MNOTE_FUJI_TAG_UNKNOWN_1200 = 0x1200 , MNOTE_FUJI_TAG_FINEPIX_COLOR = 0x1210 ,
MNOTE_FUJI_TAG_BLUR_CHECK = 0x1300 , MNOTE_FUJI_TAG_FOCUS_CHECK = 0x1301 , MNOTE_FUJI_TAG_AUTO_EXPOSURE_CHECK = 0x1302 , MNOTE_FUJI_TAG_UNKNOWN_1303 = 0x1303 ,
MNOTE_FUJI_TAG_DYNAMIC_RANGE = 0x1400 , MNOTE_FUJI_TAG_FILM_MODE = 0x1401 , MNOTE_FUJI_TAG_DYNAMIC_RANGE_SETTING = 0x1402 , MNOTE_FUJI_TAG_DEV_DYNAMIC_RANGE_SETTING = 0x1403 ,
MNOTE_FUJI_TAG_MIN_FOCAL_LENGTH = 0x1404 , MNOTE_FUJI_TAG_MAX_FOCAL_LENGTH = 0x1405 , MNOTE_FUJI_TAG_MAX_APERT_AT_MIN_FOC = 0x1406 , MNOTE_FUJI_TAG_MAX_APERT_AT_MAX_FOC = 0x1407 ,
MNOTE_FUJI_TAG_UNKNOWN_1408 = 0x1408 , MNOTE_FUJI_TAG_UNKNOWN_1409 = 0x1409 , MNOTE_FUJI_TAG_UNKNOWN_140A = 0x140A , MNOTE_FUJI_TAG_UNKNOWN_1410 = 0x1410 ,
MNOTE_FUJI_TAG_UNKNOWN_1421 = 0x1421 , MNOTE_FUJI_TAG_UNKNOWN_4100 = 0x4100 , MNOTE_FUJI_TAG_UNKNOWN_4800 = 0x4800 , MNOTE_FUJI_TAG_FILE_SOURCE = 0x8000 ,
MNOTE_FUJI_TAG_ORDER_NUMBER = 0x8002 , MNOTE_FUJI_TAG_FRAME_NUMBER = 0x8003
}
Functions
const char * mnote_fuji_tag_get_name (MnoteFujiTag tag)
const char * mnote_fuji_tag_get_title (MnoteFujiTag tag)
const char * mnote_fuji_tag_get_description (MnoteFujiTag tag)
Typedef Documentation
MnoteFujiTag
typedef enum _MnoteFujiTag MnoteFujiTag
Definition at line 1 of file mnote-fuji-tag.h.
Enumeration Type Documentation
_MnoteFujiTag
enum _MnoteFujiTag
Enumerator
MNOTE_FUJI_TAG_VERSION
MNOTE_FUJI_TAG_SERIAL_NUMBER
MNOTE_FUJI_TAG_QUALITY
MNOTE_FUJI_TAG_SHARPNESS
MNOTE_FUJI_TAG_WHITE_BALANCE
MNOTE_FUJI_TAG_COLOR
MNOTE_FUJI_TAG_TONE
MNOTE_FUJI_TAG_UNKNOWN_1006
MNOTE_FUJI_TAG_UNKNOWN_1007
MNOTE_FUJI_TAG_UNKNOWN_1008
MNOTE_FUJI_TAG_UNKNOWN_1009
MNOTE_FUJI_TAG_UNKNOWN_100A
MNOTE_FUJI_TAG_UNKNOWN_100B
MNOTE_FUJI_TAG_FLASH_MODE
MNOTE_FUJI_TAG_FLASH_STRENGTH
MNOTE_FUJI_TAG_MACRO
MNOTE_FUJI_TAG_FOCUS_MODE
MNOTE_FUJI_TAG_UNKNOWN_1022
MNOTE_FUJI_TAG_FOCUS_POINT
MNOTE_FUJI_TAG_UNKNOWN_1024
MNOTE_FUJI_TAG_UNKNOWN_1025
MNOTE_FUJI_TAG_SLOW_SYNC
MNOTE_FUJI_TAG_PICTURE_MODE
MNOTE_FUJI_TAG_UNKNOWN_1032
MNOTE_FUJI_TAG_CONT_TAKING
MNOTE_FUJI_TAG_SEQUENCE_NUMBER
MNOTE_FUJI_TAG_UNKNOWN_1200
MNOTE_FUJI_TAG_FINEPIX_COLOR
MNOTE_FUJI_TAG_BLUR_CHECK
MNOTE_FUJI_TAG_FOCUS_CHECK
MNOTE_FUJI_TAG_AUTO_EXPOSURE_CHECK
MNOTE_FUJI_TAG_UNKNOWN_1303
MNOTE_FUJI_TAG_DYNAMIC_RANGE
MNOTE_FUJI_TAG_FILM_MODE
MNOTE_FUJI_TAG_DYNAMIC_RANGE_SETTING
MNOTE_FUJI_TAG_DEV_DYNAMIC_RANGE_SETTING
MNOTE_FUJI_TAG_MIN_FOCAL_LENGTH
MNOTE_FUJI_TAG_MAX_FOCAL_LENGTH
MNOTE_FUJI_TAG_MAX_APERT_AT_MIN_FOC
MNOTE_FUJI_TAG_MAX_APERT_AT_MAX_FOC
MNOTE_FUJI_TAG_UNKNOWN_1408
MNOTE_FUJI_TAG_UNKNOWN_1409
MNOTE_FUJI_TAG_UNKNOWN_140A
MNOTE_FUJI_TAG_UNKNOWN_1410
MNOTE_FUJI_TAG_UNKNOWN_1421
MNOTE_FUJI_TAG_UNKNOWN_4100
MNOTE_FUJI_TAG_UNKNOWN_4800
MNOTE_FUJI_TAG_FILE_SOURCE
MNOTE_FUJI_TAG_ORDER_NUMBER
MNOTE_FUJI_TAG_FRAME_NUMBER
Definition at line 30 of file mnote-fuji-tag.h.
Function Documentation
mnote_fuji_tag_get_description()
const char* mnote_fuji_tag_get_description (MnoteFujiTag tag)
Definition at line 93 of file mnote-fuji-tag.c.
References _, bindtextdomain, description, table, and tag.
Referenced by exif_mnote_data_fuji_get_description().
mnote_fuji_tag_get_name()
const char* mnote_fuji_tag_get_name (MnoteFujiTag tag)
Definition at line 72 of file mnote-fuji-tag.c.
References name, table, and tag.
Referenced by exif_mnote_data_fuji_get_name(), and exif_mnote_data_fuji_load().
mnote_fuji_tag_get_title()
const char* mnote_fuji_tag_get_title (MnoteFujiTag tag)
Definition at line 82 of file mnote-fuji-tag.c.
References _, bindtextdomain, table, tag, and title.
Referenced by exif_mnote_data_fuji_get_title().
libexif Generated by