EXIF library (libexif) Internals: libexif/fuji/mnote-fuji-entry.c File Reference
mnote-fuji-entry.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <config.h>
#include <libexif/i18n.h>
#include "mnote-fuji-entry.h"
Macros
#define CF(format, target, v, maxlen)
#define CC(number, target, v, maxlen)
Functions
char * mnote_fuji_entry_get_value (MnoteFujiEntry *entry, char *val, unsigned int maxlen)
Variables
struct {
MnoteFujiTag tag
struct {
int index
const char * string
} elem [22]
} items []
Macro Definition Documentation
CC
#define CC (number, target, v, maxlen)
Value:
{                                                                       \
        if (number != target) {                                         \
                snprintf (v, maxlen,                                    \
                        _("Invalid number of components (%i, "          \
                        "expected %i)."), (int) number, (int) target);  \
                break;                                                  \
        }                                                               \
}
Definition at line 45 of file mnote-fuji-entry.c.
CF
#define CF (format, target, v, maxlen)
Value:
{                                                               \
        if (format != target) {                                 \
                snprintf (v, maxlen,                            \
                        _("Invalid format '%s', "               \
                        "expected '%s'."),                      \
                        exif_format_get_name (format),          \
                        exif_format_get_name (target));         \
                break;                                          \
        }                                                       \
}
Definition at line 33 of file mnote-fuji-entry.c.
Function Documentation
mnote_fuji_entry_get_value()
char * mnote_fuji_entry_get_value (MnoteFujiEntry * entry, char * val, unsigned int maxlen)
Definition at line 192 of file mnote-fuji-entry.c.
References _, CC, CF, _MnoteFujiEntry::components, _MnoteFujiEntry::data, ExifRational::denominator, ExifSRational::denominator, elem, EXIF_FORMAT_ASCII, EXIF_FORMAT_LONG, EXIF_FORMAT_RATIONAL, EXIF_FORMAT_SHORT, EXIF_FORMAT_SLONG, EXIF_FORMAT_SRATIONAL, EXIF_FORMAT_SSHORT, EXIF_FORMAT_UNDEFINED, exif_get_long(), exif_get_rational(), exif_get_short(), exif_get_slong(), exif_get_srational(), exif_get_sshort(), _MnoteFujiEntry::format, index, items, MIN, MNOTE_FUJI_TAG_AUTO_EXPOSURE_CHECK, MNOTE_FUJI_TAG_BLUR_CHECK, MNOTE_FUJI_TAG_COLOR, MNOTE_FUJI_TAG_CONT_TAKING, MNOTE_FUJI_TAG_DYNAMIC_RANGE, MNOTE_FUJI_TAG_DYNAMIC_RANGE_SETTING, MNOTE_FUJI_TAG_FILM_MODE, MNOTE_FUJI_TAG_FINEPIX_COLOR, MNOTE_FUJI_TAG_FLASH_MODE, MNOTE_FUJI_TAG_FOCUS_CHECK, MNOTE_FUJI_TAG_FOCUS_MODE, MNOTE_FUJI_TAG_FOCUS_POINT, MNOTE_FUJI_TAG_MACRO, MNOTE_FUJI_TAG_MAX_FOCAL_LENGTH, MNOTE_FUJI_TAG_MIN_FOCAL_LENGTH, MNOTE_FUJI_TAG_PICTURE_MODE, MNOTE_FUJI_TAG_SHARPNESS, MNOTE_FUJI_TAG_SLOW_SYNC, MNOTE_FUJI_TAG_TONE, MNOTE_FUJI_TAG_VERSION, MNOTE_FUJI_TAG_WHITE_BALANCE, ExifRational::numerator, ExifSRational::numerator, _MnoteFujiEntry::order, _MnoteFujiEntry::size, tag, and _MnoteFujiEntry::tag.
Referenced by exif_mnote_data_fuji_get_value().
Variable Documentation
[struct]
struct { ... } elem[22]
Referenced by mnote_fuji_entry_get_value().
index
int index
Definition at line 58 of file mnote-fuji-entry.c.
Referenced by mnote_fuji_entry_get_value().
[struct]
const struct { ... } items[]
Referenced by mnote_fuji_entry_get_value().
string
const char* string
Definition at line 59 of file mnote-fuji-entry.c.
Referenced by split_ws_string(), and split_ws_string().
tag
MnoteFujiTag tag
Definition at line 56 of file mnote-fuji-entry.c.
Referenced by mnote_fuji_entry_get_value().
libexif Generated by