EXIF library (libexif) Internals: libexif/canon/mnote-canon-tag.c File Reference
mnote-canon-tag.c File Reference
#include <config.h>
#include "mnote-canon-tag.h"
#include <stdlib.h>
#include <libexif/i18n.h>
Functions
const char * mnote_canon_tag_get_name (MnoteCanonTag t)
const char * mnote_canon_tag_get_name_sub (MnoteCanonTag t, unsigned int s, ExifDataOption o)
const char * mnote_canon_tag_get_title (MnoteCanonTag t)
const char * mnote_canon_tag_get_title_sub (MnoteCanonTag t, unsigned int s, ExifDataOption o)
const char * mnote_canon_tag_get_description (MnoteCanonTag t)
Variables
struct {
MnoteCanonTag tag
const char * name
const char * title
const char * description
} table []
struct {
MnoteCanonTag tag
unsigned int subtag
const char * name
} table_sub []
Function Documentation
mnote_canon_tag_get_description()
const char * mnote_canon_tag_get_description (MnoteCanonTag t)
Definition at line 277 of file mnote-canon-tag.c.
References _, bindtextdomain, description, table, and tag.
Referenced by exif_mnote_data_canon_get_description().
mnote_canon_tag_get_name()
const char * mnote_canon_tag_get_name (MnoteCanonTag t)
Definition at line 211 of file mnote-canon-tag.c.
References table, and tag.
Referenced by exif_mnote_data_canon_load(), and mnote_canon_tag_get_name_sub().
mnote_canon_tag_get_name_sub()
const char * mnote_canon_tag_get_name_sub (MnoteCanonTag t, unsigned int s, ExifDataOption o)
Definition at line 221 of file mnote-canon-tag.c.
References EXIF_DATA_OPTION_IGNORE_UNKNOWN_TAGS, mnote_canon_tag_get_name(), subtag, table_sub, and tag.
Referenced by exif_mnote_data_canon_get_name().
mnote_canon_tag_get_title()
const char * mnote_canon_tag_get_title (MnoteCanonTag t)
Definition at line 240 of file mnote-canon-tag.c.
References _, bindtextdomain, table, tag, and title.
Referenced by mnote_canon_tag_get_title_sub().
mnote_canon_tag_get_title_sub()
const char * mnote_canon_tag_get_title_sub (MnoteCanonTag t, unsigned int s, ExifDataOption o)
Definition at line 255 of file mnote-canon-tag.c.
References _, EXIF_DATA_OPTION_IGNORE_UNKNOWN_TAGS, mnote_canon_tag_get_title(), name, subtag, table_sub, and tag.
Referenced by exif_mnote_data_canon_get_title().
Variable Documentation
description
const char* description
Definition at line 34 of file mnote-canon-tag.c.
Referenced by mnote_canon_tag_get_description().
name
const char* name (void)
Definition at line 32 of file mnote-canon-tag.c.
Referenced by mnote_canon_tag_get_title_sub().
subtag
unsigned int subtag
Definition at line 118 of file mnote-canon-tag.c.
Referenced by canon_search_table_bitfield(), canon_search_table_value(), mnote_canon_tag_get_name_sub(), and mnote_canon_tag_get_title_sub().
[struct]
const struct { ... } table[]
Referenced by mnote_canon_tag_get_description(), mnote_canon_tag_get_name(), and mnote_canon_tag_get_title().
[struct]
const struct { ... } table_sub[]
Referenced by mnote_canon_tag_get_name_sub(), and mnote_canon_tag_get_title_sub().
tag
MnoteCanonTag tag
Definition at line 31 of file mnote-canon-tag.c.
Referenced by mnote_canon_tag_get_description(), mnote_canon_tag_get_name(), mnote_canon_tag_get_name_sub(), mnote_canon_tag_get_title(), and mnote_canon_tag_get_title_sub().
title
const char* title
Definition at line 33 of file mnote-canon-tag.c.
Referenced by mnote_canon_tag_get_title().
libexif Generated by