EXIF library (libexif) Internals: libexif/olympus/mnote-olympus-tag.c File Reference
mnote-olympus-tag.c File Reference
#include <config.h>
#include "mnote-olympus-tag.h"
#include <libexif/i18n.h>
#include <libexif/exif-utils.h>
#include <stdlib.h>
Functions
const char * mnote_olympus_tag_get_name (MnoteOlympusTag t)
Return a textual name of the given tag within the Olympus-style MakerNote.
const char * mnote_olympus_tag_get_title (MnoteOlympusTag t)
Return a textual title of the given tag within the Olympus-style MakerNote.
const char * mnote_olympus_tag_get_description (MnoteOlympusTag t)
Return a verbose textual description of the given tag within the Olympus-style MakerNote.
Variables
struct {
MnoteOlympusTag tag
const char * name
const char * title
const char * description
} table []
Function Documentation
mnote_olympus_tag_get_description()
const char* mnote_olympus_tag_get_description (MnoteOlympusTag tag)
Return a verbose textual description of the given tag within the Olympus-style MakerNote.
The description is a verbose, localized description of the tag.
Parameters
[in] tag EXIF tag
Returns
textual description of the tag, or NULL if the tag is unknown
Definition at line 250 of file mnote-olympus-tag.c.
References _, bindtextdomain, description, table, and tag.
Referenced by exif_mnote_data_olympus_get_description().
mnote_olympus_tag_get_name()
const char* mnote_olympus_tag_get_name (MnoteOlympusTag tag)
Return a textual name of the given tag within the Olympus-style MakerNote.
The name is a short, unique, non-localized text string containing only US-ASCII alphanumeric characters.
Parameters
[in] tag Olympus-style MakerNote tag
Returns
textual name of the tag, or NULL if the tag is unknown
Definition at line 229 of file mnote-olympus-tag.c.
References name, table, and tag.
Referenced by exif_mnote_data_olympus_get_name(), and exif_mnote_data_olympus_load().
mnote_olympus_tag_get_title()
const char* mnote_olympus_tag_get_title (MnoteOlympusTag tag)
Return a textual title of the given tag within the Olympus-style MakerNote.
The title is a short, localized description of the tag.
Parameters
[in] tag Olympus-style MakerNote tag
Returns
textual title of the tag, or NULL if the tag is unknown
Definition at line 239 of file mnote-olympus-tag.c.
References _, bindtextdomain, table, tag, and title.
Referenced by exif_mnote_data_olympus_get_title().
Variable Documentation
description
const char* description
Definition at line 33 of file mnote-olympus-tag.c.
Referenced by mnote_olympus_tag_get_description().
name
const char* name (void)
Definition at line 31 of file mnote-olympus-tag.c.
Referenced by mnote_olympus_tag_get_name().
const { ... } table[]
Referenced by mnote_olympus_tag_get_description(), mnote_olympus_tag_get_name(), and mnote_olympus_tag_get_title().
tag
MnoteOlympusTag tag
Definition at line 30 of file mnote-olympus-tag.c.
Referenced by mnote_olympus_tag_get_description(), mnote_olympus_tag_get_name(), and mnote_olympus_tag_get_title().
title
const char* title
Definition at line 32 of file mnote-olympus-tag.c.
Referenced by mnote_olympus_tag_get_title().
libexif Generated by