EXIF library (libexif) Internals: libexif/olympus/mnote-olympus-tag.h File Reference
mnote-olympus-tag.h File Reference
Macros
#define MNOTE_OLYMPUS_TAG_UNKNOWN_1 MNOTE_OLYMPUS_TAG_BWMODE
#define MNOTE_OLYMPUS_TAG_UNKNOWN_2 MNOTE_OLYMPUS_TAG_FOCALPLANEDIAGONAL
#define MNOTE_OLYMPUS_TAG_UNKNOWN_3 MNOTE_OLYMPUS_TAG_LENSDISTORTION
#define MNOTE_OLYMPUS_TAG_UNKNOWN_5 MNOTE_OLYMPUS_TAG_DATADUMP
#define MNOTE_NIKON_TAG_PREVIEWIMAGE MNOTE_NIKON_TAG_PREVIEWIMAGE_IFD_POINTER
Typedefs
typedef enum _MnoteOlympusTag MnoteOlympusTag
Enumerations
enum _MnoteOlympusTag {
MNOTE_NIKON_TAG_FIRMWARE = 0x0001 , MNOTE_NIKON_TAG_ISO = 0x0002 , MNOTE_NIKON_TAG_COLORMODE1 = 0x0003 , MNOTE_NIKON_TAG_QUALITY = 0x0004 ,
MNOTE_NIKON_TAG_WHITEBALANCE = 0x0005 , MNOTE_NIKON_TAG_SHARPENING = 0x0006 , MNOTE_NIKON_TAG_FOCUSMODE = 0x0007 , MNOTE_NIKON_TAG_FLASHSETTING = 0x0008 ,
MNOTE_NIKON_TAG_FLASHMODE = 0x0009 , MNOTE_NIKON_TAG_WHITEBALANCEFINE = 0x000b , MNOTE_NIKON_TAG_WHITEBALANCERB = 0x000c , MNOTE_NIKON_TAG_PROGRAMSHIFT = 0x000d ,
MNOTE_NIKON_TAG_EXPOSUREDIFF = 0x000e , MNOTE_NIKON_TAG_ISOSELECTION = 0x000f , MNOTE_NIKON_TAG_PREVIEWIMAGE_IFD_POINTER = 0x0011 , MNOTE_NIKON_TAG_FLASHEXPCOMPENSATION = 0x0012 ,
MNOTE_NIKON_TAG_ISO2 = 0x0013 , MNOTE_NIKON_TAG_IMAGEBOUNDARY = 0x0016 , MNOTE_NIKON_TAG_EXTERNALFLASHEXPCOMPENSATION = 0x0017 , MNOTE_NIKON_TAG_FLASHEXPOSUREBRACKETVAL = 0x0018 ,
MNOTE_NIKON_TAG_EXPOSUREBRACKETVAL = 0x0019 , MNOTE_NIKON_TAG_CROPHISPEED = 0x001b , MNOTE_NIKON_TAG_EXPOSURETUNING = 0x001c , MNOTE_NIKON_TAG_SERIALNUMBER = 0x001d ,
MNOTE_NIKON_TAG_COLORSPACE = 0x001e , MNOTE_NIKON_TAG_VRINFO = 0x001f , MNOTE_NIKON_TAG_IMAGEAUTHENTICATION = 0x0020 , MNOTE_NIKON_TAG_FACEDETECT = 0x0021 ,
MNOTE_NIKON_TAG_ACTIVEDLIGHTING = 0x0022 , MNOTE_NIKON_TAG_PICTURECONTROLDATA = 0x0023 , MNOTE_NIKON_TAG_WORLDTIME = 0x0024 , MNOTE_NIKON_TAG_ISOINFO = 0x0025 ,
MNOTE_NIKON_TAG_VIGNETTECONTROL = 0x002a , MNOTE_NIKON_TAG_DISTORTINFO = 0x002b , MNOTE_NIKON_TAG_SHUTTERMODE = 0x0034 , MNOTE_NIKON_TAG_HDRINFO = 0x0035 ,
MNOTE_NIKON_TAG_MECHANICALSHUTTERCOUNT = 0x0037 , MNOTE_NIKON_TAG_LOCATIONINFO = 0x0039 , MNOTE_NIKON_TAG_BLACKLEVEL = 0x003d , MNOTE_NIKON_TAG_IMAGESIZERAW = 0x003e ,
MNOTE_NIKON_TAG_CROPAREA = 0x0045 , MNOTE_NIKON_TAG_NIKONSETTINGS = 0x004e , MNOTE_NIKON_TAG_COLORTEMPERATUREAUTO = 0x004f , MNOTE_NIKON_TAG_IMAGEADJUSTMENT = 0x0080 ,
MNOTE_NIKON_TAG_TONECOMPENSATION = 0x0081 , MNOTE_NIKON_TAG_ADAPTER = 0x0082 , MNOTE_NIKON_TAG_LENSTYPE = 0x0083 , MNOTE_NIKON_TAG_LENS = 0x0084 ,
MNOTE_NIKON_TAG_MANUALFOCUSDISTANCE = 0x0085 , MNOTE_NIKON_TAG_DIGITALZOOM = 0x0086 , MNOTE_NIKON_TAG_FLASHUSED = 0x0087 , MNOTE_NIKON_TAG_AFFOCUSPOSITION = 0x0088 ,
MNOTE_NIKON_TAG_BRACKETING = 0x0089 , MNOTE_NIKON_TAG_UNKNOWN_0X008A = 0x008a , MNOTE_NIKON_TAG_LENS_FSTOPS = 0x008b , MNOTE_NIKON_TAG_CURVE = 0x008c ,
MNOTE_NIKON_TAG_COLORMODE = 0x008d , MNOTE_NIKON_TAG_LIGHTTYPE = 0x0090 , MNOTE_NIKON_TAG_SHOTINFO = 0x0091 , MNOTE_NIKON_TAG_HUE = 0x0092 ,
MNOTE_NIKON_TAG_SATURATION = 0x0094 , MNOTE_NIKON_TAG_NOISEREDUCTION = 0x0095 , MNOTE_NIKON_TAG_COLORBALANCE = 0x0097 , MNOTE_NIKON_TAG_LENSDATA = 0x0098 ,
MNOTE_NIKON_TAG_SENSORPIXELSIZE = 0x009a , MNOTE_NIKON_TAG_UNKNOWN_0X009B = 0x009b , MNOTE_NIKON_TAG_RETOUCHHISTORY = 0x009e , MNOTE_NIKON_TAG_SERIALNUMBER2 = 0x00a0 ,
MNOTE_NIKON_TAG_IMAGE_DATASIZE = 0x00a2 , MNOTE_NIKON_TAG_UNKNOWN_0X00A3 = 0x00a3 , MNOTE_NIKON_TAG_TOTALPICTURES = 0x00a7 , MNOTE_NIKON_TAG_FLASHINFO = 0x00a8 ,
MNOTE_NIKON_TAG_OPTIMIZATION = 0x00a9 , MNOTE_NIKON_TAG_SATURATION2 = 0x00aa , MNOTE_NIKON_TAG_VARIPROGRAM = 0x00ab , MNOTE_NIKON_TAG_MULTIEXPOSURE = 0x00b0 ,
MNOTE_NIKON_TAG_HIGHISONR = 0x00b1 , MNOTE_NIKON_TAG_TONINGEFFECT = 0x00b3 , MNOTE_NIKON_TAG_POWERUPTIME = 0x00b6 , MNOTE_NIKON_TAG_AFINFO2 = 0x00b7 ,
MNOTE_NIKON_TAG_FILEINFO = 0x00b8 , MNOTE_NIKON_TAG_RETOUCHINFO = 0x00bb , MNOTE_NIKON_TAG_CAPTUREEDITORDATA = 0x0e01 , MNOTE_NIKON_TAG_CAPTUREEDITORVER = 0x0e09 ,
MNOTE_NIKON_TAG_UNKNOWN_0X0E0E = 0x0e0e , MNOTE_NIKON_TAG_UNKNOWN_0X0E10 = 0x0e10 , MNOTE_NIKON1_TAG_BASE = 0x8000 , MNOTE_NIKON1_TAG_UNKNOWN_0X0002 = 0x0002 + MNOTE_NIKON1_TAG_BASE ,
MNOTE_NIKON1_TAG_QUALITY = 0x0003 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_COLORMODE = 0x0004 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_IMAGEADJUSTMENT = 0x0005 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_CCDSENSITIVITY = 0x0006 + MNOTE_NIKON1_TAG_BASE ,
MNOTE_NIKON1_TAG_WHITEBALANCE = 0x0007 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_FOCUS = 0x0008 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_UNKNOWN_0X0009 = 0x0009 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_DIGITALZOOM = 0x000a + MNOTE_NIKON1_TAG_BASE ,
MNOTE_NIKON1_TAG_CONVERTER = 0x000b + MNOTE_NIKON1_TAG_BASE , MNOTE_OLYMPUS_TAG_THUMBNAILIMAGE = 0x0100 , MNOTE_OLYMPUS_TAG_MODE = 0x0200 , MNOTE_OLYMPUS_TAG_QUALITY = 0x0201 ,
MNOTE_OLYMPUS_TAG_MACRO = 0x0202 , MNOTE_OLYMPUS_TAG_BWMODE = 0x0203 , MNOTE_OLYMPUS_TAG_DIGIZOOM = 0x0204 , MNOTE_OLYMPUS_TAG_FOCALPLANEDIAGONAL = 0x0205 ,
MNOTE_OLYMPUS_TAG_LENSDISTORTION = 0x0206 , MNOTE_OLYMPUS_TAG_VERSION = 0x0207 , MNOTE_OLYMPUS_TAG_INFO = 0x0208 , MNOTE_OLYMPUS_TAG_ID = 0x0209 ,
MNOTE_OLYMPUS_TAG_PRECAPTUREFRAMES = 0x0300 , MNOTE_OLYMPUS_TAG_WHITEBOARD = 0x0301 , MNOTE_OLYMPUS_TAG_ONETOUCHWB = 0x0302 , MNOTE_OLYMPUS_TAG_WHITEBALANCEBRACKET = 0x0303 ,
MNOTE_OLYMPUS_TAG_WHITEBALANCEBIAS = 0x0304 , MNOTE_OLYMPUS_TAG_DATADUMP = 0x0f00 , MNOTE_OLYMPUS_TAG_UNKNOWN_4 = 0x0f04 , MNOTE_OLYMPUS_TAG_SHUTTERSPEED = 0x1000 ,
MNOTE_OLYMPUS_TAG_ISOVALUE = 0x1001 , MNOTE_OLYMPUS_TAG_APERTUREVALUE = 0x1002 , MNOTE_OLYMPUS_TAG_BRIGHTNESSVALUE = 0x1003 , MNOTE_OLYMPUS_TAG_FLASHMODE = 0x1004 ,
MNOTE_OLYMPUS_TAG_FLASHDEVICE = 0x1005 , MNOTE_OLYMPUS_TAG_EXPOSURECOMP = 0x1006 , MNOTE_OLYMPUS_TAG_SENSORTEMPERATURE = 0x1007 , MNOTE_OLYMPUS_TAG_LENSTEMPERATURE = 0x1008 ,
MNOTE_OLYMPUS_TAG_LIGHTCONDITION = 0x1009 , MNOTE_OLYMPUS_TAG_FOCUSRANGE = 0x100a , MNOTE_OLYMPUS_TAG_MANFOCUS = 0x100b , MNOTE_OLYMPUS_TAG_FOCUSDIST = 0x100c ,
MNOTE_OLYMPUS_TAG_ZOOMSTEPCOUNT = 0x100d , MNOTE_OLYMPUS_TAG_FOCUSSTEPCOUNT = 0x100e , MNOTE_OLYMPUS_TAG_SHARPNESS = 0x100f , MNOTE_OLYMPUS_TAG_FLASHCHARGELEVEL = 0x1010 ,
MNOTE_OLYMPUS_TAG_COLORMATRIX = 0x1011 , MNOTE_OLYMPUS_TAG_BLACKLEVEL = 0x1012 , MNOTE_OLYMPUS_TAG_WBALANCE = 0x1015 , MNOTE_OLYMPUS_TAG_REDBALANCE = 0x1017 ,
MNOTE_OLYMPUS_TAG_BLUEBALANCE = 0x1018 , MNOTE_OLYMPUS_TAG_COLORMATRIXNUMBER = 0x1019 , MNOTE_OLYMPUS_TAG_SERIALNUMBER2 = 0x101a , MNOTE_OLYMPUS_TAG_FLASHEXPOSURECOMP = 0x1023 ,
MNOTE_OLYMPUS_TAG_INTERNALFLASHTABLE = 0x1024 , MNOTE_OLYMPUS_TAG_EXTERNALFLASHGVALUE = 0x1025 , MNOTE_OLYMPUS_TAG_EXTERNALFLASHBOUNCE = 0x1026 , MNOTE_OLYMPUS_TAG_EXTERNALFLASHZOOM = 0x1027 ,
MNOTE_OLYMPUS_TAG_EXTERNALFLASHMODE = 0x1028 , MNOTE_OLYMPUS_TAG_CONTRAST = 0x1029 , MNOTE_OLYMPUS_TAG_SHARPNESSFACTOR = 0x102a , MNOTE_OLYMPUS_TAG_COLORCONTROL = 0x102b ,
MNOTE_OLYMPUS_TAG_IMAGEWIDTH = 0x102e , MNOTE_OLYMPUS_TAG_IMAGEHEIGHT = 0x102f , MNOTE_OLYMPUS_TAG_SCENEDETECT = 0x1030 , MNOTE_OLYMPUS_TAG_COMPRESSIONRATIO = 0x1034 ,
MNOTE_OLYMPUS_TAG_PREVIEWIMAGEVALID = 0x1035 , MNOTE_OLYMPUS_TAG_AFRESULT = 0x1038 , MNOTE_OLYMPUS_TAG_CCDSCANMODE = 0x1039 , MNOTE_OLYMPUS_TAG_NOISEREDUCTION = 0x103a ,
MNOTE_OLYMPUS_TAG_INFINITYLENSSTEP = 0x103b , MNOTE_OLYMPUS_TAG_NEARLENSSTEP = 0x103c , MNOTE_OLYMPUS_TAG_LIGHTVALUECENTER = 0x103d , MNOTE_OLYMPUS_TAG_LIGHTVALUEPERIPHERY = 0x103e ,
MNOTE_EPSON_TAG_IMAGE_WIDTH = 0x020b , MNOTE_EPSON_TAG_IMAGE_HEIGHT = 0x020c , MNOTE_EPSON_TAG_SOFTWARE = 0x020d , MNOTE_SANYO_TAG_SEQUENTIALSHOT = 0x020e ,
MNOTE_SANYO_TAG_WIDERANGE = 0x020f , MNOTE_SANYO_TAG_COLORADJUSTMENTMODE = 0x0210 , MNOTE_SANYO_TAG_FOCUSMODE = 0x0212 , MNOTE_SANYO_TAG_QUICKSHOT = 0x0213 ,
MNOTE_SANYO_TAG_SELFTIMER = 0x0214 , MNOTE_SANYO_TAG_VOICEMEMO = 0x0216 , MNOTE_SANYO_TAG_RECORDSHUTTERRELEASE = 0x0217 , MNOTE_SANYO_TAG_FLICKERREDUCE = 0x0218 ,
MNOTE_SANYO_TAG_OPTICALZOOM = 0x0219 , MNOTE_SANYO_TAG_CCDSENSITIVITY = 0x021a , MNOTE_SANYO_TAG_DIGITALZOOM = 0x021b , MNOTE_SANYO_TAG_LIGHTSOURCESPECIAL = 0x021d ,
MNOTE_SANYO_TAG_RESAVED = 0x021e , MNOTE_SANYO_TAG_SCENESELECT = 0x021f , MNOTE_SANYO_TAG_MANUALFOCUSDISTANCE = 0x0223 , MNOTE_SANYO_TAG_SEQUENCESHOTINTERVAL = 0x0224
}
Functions
const char * mnote_olympus_tag_get_name (MnoteOlympusTag tag)
Return a textual name of the given tag within the Olympus-style MakerNote.
const char * mnote_olympus_tag_get_title (MnoteOlympusTag tag)
Return a textual title of the given tag within the Olympus-style MakerNote.
const char * mnote_olympus_tag_get_description (MnoteOlympusTag tag)
Return a verbose textual description of the given tag within the Olympus-style MakerNote.
Macro Definition Documentation
MNOTE_NIKON_TAG_PREVIEWIMAGE
#define MNOTE_NIKON_TAG_PREVIEWIMAGE MNOTE_NIKON_TAG_PREVIEWIMAGE_IFD_POINTER
Definition at line 227 of file mnote-olympus-tag.h.
MNOTE_OLYMPUS_TAG_UNKNOWN_1
#define MNOTE_OLYMPUS_TAG_UNKNOWN_1 MNOTE_OLYMPUS_TAG_BWMODE
Definition at line 223 of file mnote-olympus-tag.h.
MNOTE_OLYMPUS_TAG_UNKNOWN_2
#define MNOTE_OLYMPUS_TAG_UNKNOWN_2 MNOTE_OLYMPUS_TAG_FOCALPLANEDIAGONAL
Definition at line 224 of file mnote-olympus-tag.h.
MNOTE_OLYMPUS_TAG_UNKNOWN_3
#define MNOTE_OLYMPUS_TAG_UNKNOWN_3 MNOTE_OLYMPUS_TAG_LENSDISTORTION
Definition at line 225 of file mnote-olympus-tag.h.
MNOTE_OLYMPUS_TAG_UNKNOWN_5
#define MNOTE_OLYMPUS_TAG_UNKNOWN_5 MNOTE_OLYMPUS_TAG_DATADUMP
Definition at line 226 of file mnote-olympus-tag.h.
Typedef Documentation
MnoteOlympusTag
typedef enum _MnoteOlympusTag MnoteOlympusTag
Definition at line 1 of file mnote-olympus-tag.h.
Enumeration Type Documentation
_MnoteOlympusTag
enum _MnoteOlympusTag
Enumerator
MNOTE_NIKON_TAG_FIRMWARE
MNOTE_NIKON_TAG_ISO
MNOTE_NIKON_TAG_COLORMODE1
MNOTE_NIKON_TAG_QUALITY
MNOTE_NIKON_TAG_WHITEBALANCE
MNOTE_NIKON_TAG_SHARPENING
MNOTE_NIKON_TAG_FOCUSMODE
MNOTE_NIKON_TAG_FLASHSETTING
MNOTE_NIKON_TAG_FLASHMODE
MNOTE_NIKON_TAG_WHITEBALANCEFINE
MNOTE_NIKON_TAG_WHITEBALANCERB
MNOTE_NIKON_TAG_PROGRAMSHIFT
MNOTE_NIKON_TAG_EXPOSUREDIFF
MNOTE_NIKON_TAG_ISOSELECTION
MNOTE_NIKON_TAG_PREVIEWIMAGE_IFD_POINTER
MNOTE_NIKON_TAG_FLASHEXPCOMPENSATION
MNOTE_NIKON_TAG_ISO2
MNOTE_NIKON_TAG_IMAGEBOUNDARY
MNOTE_NIKON_TAG_EXTERNALFLASHEXPCOMPENSATION
MNOTE_NIKON_TAG_FLASHEXPOSUREBRACKETVAL
MNOTE_NIKON_TAG_EXPOSUREBRACKETVAL
MNOTE_NIKON_TAG_CROPHISPEED
MNOTE_NIKON_TAG_EXPOSURETUNING
MNOTE_NIKON_TAG_SERIALNUMBER
MNOTE_NIKON_TAG_COLORSPACE
MNOTE_NIKON_TAG_VRINFO
MNOTE_NIKON_TAG_IMAGEAUTHENTICATION
MNOTE_NIKON_TAG_FACEDETECT
MNOTE_NIKON_TAG_ACTIVEDLIGHTING
MNOTE_NIKON_TAG_PICTURECONTROLDATA
MNOTE_NIKON_TAG_WORLDTIME
MNOTE_NIKON_TAG_ISOINFO
MNOTE_NIKON_TAG_VIGNETTECONTROL
MNOTE_NIKON_TAG_DISTORTINFO
MNOTE_NIKON_TAG_SHUTTERMODE
MNOTE_NIKON_TAG_HDRINFO
MNOTE_NIKON_TAG_MECHANICALSHUTTERCOUNT
MNOTE_NIKON_TAG_LOCATIONINFO
MNOTE_NIKON_TAG_BLACKLEVEL
MNOTE_NIKON_TAG_IMAGESIZERAW
MNOTE_NIKON_TAG_CROPAREA
MNOTE_NIKON_TAG_NIKONSETTINGS
MNOTE_NIKON_TAG_COLORTEMPERATUREAUTO
MNOTE_NIKON_TAG_IMAGEADJUSTMENT
MNOTE_NIKON_TAG_TONECOMPENSATION
MNOTE_NIKON_TAG_ADAPTER
MNOTE_NIKON_TAG_LENSTYPE
MNOTE_NIKON_TAG_LENS
MNOTE_NIKON_TAG_MANUALFOCUSDISTANCE
MNOTE_NIKON_TAG_DIGITALZOOM
MNOTE_NIKON_TAG_FLASHUSED
MNOTE_NIKON_TAG_AFFOCUSPOSITION
MNOTE_NIKON_TAG_BRACKETING
MNOTE_NIKON_TAG_UNKNOWN_0X008A
MNOTE_NIKON_TAG_LENS_FSTOPS
MNOTE_NIKON_TAG_CURVE
MNOTE_NIKON_TAG_COLORMODE
MNOTE_NIKON_TAG_LIGHTTYPE
MNOTE_NIKON_TAG_SHOTINFO
MNOTE_NIKON_TAG_HUE
MNOTE_NIKON_TAG_SATURATION
MNOTE_NIKON_TAG_NOISEREDUCTION
MNOTE_NIKON_TAG_COLORBALANCE
MNOTE_NIKON_TAG_LENSDATA
MNOTE_NIKON_TAG_SENSORPIXELSIZE
MNOTE_NIKON_TAG_UNKNOWN_0X009B
MNOTE_NIKON_TAG_RETOUCHHISTORY
MNOTE_NIKON_TAG_SERIALNUMBER2
MNOTE_NIKON_TAG_IMAGE_DATASIZE
MNOTE_NIKON_TAG_UNKNOWN_0X00A3
MNOTE_NIKON_TAG_TOTALPICTURES
MNOTE_NIKON_TAG_FLASHINFO
MNOTE_NIKON_TAG_OPTIMIZATION
MNOTE_NIKON_TAG_SATURATION2
MNOTE_NIKON_TAG_VARIPROGRAM
MNOTE_NIKON_TAG_MULTIEXPOSURE
MNOTE_NIKON_TAG_HIGHISONR
MNOTE_NIKON_TAG_TONINGEFFECT
MNOTE_NIKON_TAG_POWERUPTIME
MNOTE_NIKON_TAG_AFINFO2
MNOTE_NIKON_TAG_FILEINFO
MNOTE_NIKON_TAG_RETOUCHINFO
MNOTE_NIKON_TAG_CAPTUREEDITORDATA
MNOTE_NIKON_TAG_CAPTUREEDITORVER
MNOTE_NIKON_TAG_UNKNOWN_0X0E0E
MNOTE_NIKON_TAG_UNKNOWN_0X0E10
MNOTE_NIKON1_TAG_BASE
MNOTE_NIKON1_TAG_UNKNOWN_0X0002
MNOTE_NIKON1_TAG_QUALITY
MNOTE_NIKON1_TAG_COLORMODE
MNOTE_NIKON1_TAG_IMAGEADJUSTMENT
MNOTE_NIKON1_TAG_CCDSENSITIVITY
MNOTE_NIKON1_TAG_WHITEBALANCE
MNOTE_NIKON1_TAG_FOCUS
MNOTE_NIKON1_TAG_UNKNOWN_0X0009
MNOTE_NIKON1_TAG_DIGITALZOOM
MNOTE_NIKON1_TAG_CONVERTER
MNOTE_OLYMPUS_TAG_THUMBNAILIMAGE
MNOTE_OLYMPUS_TAG_MODE
MNOTE_OLYMPUS_TAG_QUALITY
MNOTE_OLYMPUS_TAG_MACRO
MNOTE_OLYMPUS_TAG_BWMODE
MNOTE_OLYMPUS_TAG_DIGIZOOM
MNOTE_OLYMPUS_TAG_FOCALPLANEDIAGONAL
MNOTE_OLYMPUS_TAG_LENSDISTORTION
MNOTE_OLYMPUS_TAG_VERSION
MNOTE_OLYMPUS_TAG_INFO
MNOTE_OLYMPUS_TAG_ID
MNOTE_OLYMPUS_TAG_PRECAPTUREFRAMES
MNOTE_OLYMPUS_TAG_WHITEBOARD
MNOTE_OLYMPUS_TAG_ONETOUCHWB
MNOTE_OLYMPUS_TAG_WHITEBALANCEBRACKET
MNOTE_OLYMPUS_TAG_WHITEBALANCEBIAS
MNOTE_OLYMPUS_TAG_DATADUMP
MNOTE_OLYMPUS_TAG_UNKNOWN_4
MNOTE_OLYMPUS_TAG_SHUTTERSPEED
MNOTE_OLYMPUS_TAG_ISOVALUE
MNOTE_OLYMPUS_TAG_APERTUREVALUE
MNOTE_OLYMPUS_TAG_BRIGHTNESSVALUE
MNOTE_OLYMPUS_TAG_FLASHMODE
MNOTE_OLYMPUS_TAG_FLASHDEVICE
MNOTE_OLYMPUS_TAG_EXPOSURECOMP
MNOTE_OLYMPUS_TAG_SENSORTEMPERATURE
MNOTE_OLYMPUS_TAG_LENSTEMPERATURE
MNOTE_OLYMPUS_TAG_LIGHTCONDITION
MNOTE_OLYMPUS_TAG_FOCUSRANGE
MNOTE_OLYMPUS_TAG_MANFOCUS
MNOTE_OLYMPUS_TAG_FOCUSDIST
MNOTE_OLYMPUS_TAG_ZOOMSTEPCOUNT
MNOTE_OLYMPUS_TAG_FOCUSSTEPCOUNT
MNOTE_OLYMPUS_TAG_SHARPNESS
MNOTE_OLYMPUS_TAG_FLASHCHARGELEVEL
MNOTE_OLYMPUS_TAG_COLORMATRIX
MNOTE_OLYMPUS_TAG_BLACKLEVEL
MNOTE_OLYMPUS_TAG_WBALANCE
MNOTE_OLYMPUS_TAG_REDBALANCE
MNOTE_OLYMPUS_TAG_BLUEBALANCE
MNOTE_OLYMPUS_TAG_COLORMATRIXNUMBER
MNOTE_OLYMPUS_TAG_SERIALNUMBER2
MNOTE_OLYMPUS_TAG_FLASHEXPOSURECOMP
MNOTE_OLYMPUS_TAG_INTERNALFLASHTABLE
MNOTE_OLYMPUS_TAG_EXTERNALFLASHGVALUE
MNOTE_OLYMPUS_TAG_EXTERNALFLASHBOUNCE
MNOTE_OLYMPUS_TAG_EXTERNALFLASHZOOM
MNOTE_OLYMPUS_TAG_EXTERNALFLASHMODE
MNOTE_OLYMPUS_TAG_CONTRAST
MNOTE_OLYMPUS_TAG_SHARPNESSFACTOR
MNOTE_OLYMPUS_TAG_COLORCONTROL
MNOTE_OLYMPUS_TAG_IMAGEWIDTH
MNOTE_OLYMPUS_TAG_IMAGEHEIGHT
MNOTE_OLYMPUS_TAG_SCENEDETECT
MNOTE_OLYMPUS_TAG_COMPRESSIONRATIO
MNOTE_OLYMPUS_TAG_PREVIEWIMAGEVALID
MNOTE_OLYMPUS_TAG_AFRESULT
MNOTE_OLYMPUS_TAG_CCDSCANMODE
MNOTE_OLYMPUS_TAG_NOISEREDUCTION
MNOTE_OLYMPUS_TAG_INFINITYLENSSTEP
MNOTE_OLYMPUS_TAG_NEARLENSSTEP
MNOTE_OLYMPUS_TAG_LIGHTVALUECENTER
MNOTE_OLYMPUS_TAG_LIGHTVALUEPERIPHERY
MNOTE_EPSON_TAG_IMAGE_WIDTH
MNOTE_EPSON_TAG_IMAGE_HEIGHT
MNOTE_EPSON_TAG_SOFTWARE
MNOTE_SANYO_TAG_SEQUENTIALSHOT
MNOTE_SANYO_TAG_WIDERANGE
MNOTE_SANYO_TAG_COLORADJUSTMENTMODE
MNOTE_SANYO_TAG_FOCUSMODE
MNOTE_SANYO_TAG_QUICKSHOT
MNOTE_SANYO_TAG_SELFTIMER
MNOTE_SANYO_TAG_VOICEMEMO
MNOTE_SANYO_TAG_RECORDSHUTTERRELEASE
MNOTE_SANYO_TAG_FLICKERREDUCE
MNOTE_SANYO_TAG_OPTICALZOOM
MNOTE_SANYO_TAG_CCDSENSITIVITY
MNOTE_SANYO_TAG_DIGITALZOOM
MNOTE_SANYO_TAG_LIGHTSOURCESPECIAL
MNOTE_SANYO_TAG_RESAVED
MNOTE_SANYO_TAG_SCENESELECT
MNOTE_SANYO_TAG_MANUALFOCUSDISTANCE
MNOTE_SANYO_TAG_SEQUENCESHOTINTERVAL
Definition at line 28 of file mnote-olympus-tag.h.
Function Documentation
mnote_olympus_tag_get_description()
const char* mnote_olympus_tag_get_description (MnoteOlympusTag tag)
Return a verbose textual description of the given tag within the Olympus-style MakerNote.
The description is a verbose, localized description of the tag.
Parameters
[in] tag EXIF tag
Returns
textual description of the tag, or NULL if the tag is unknown
Definition at line 250 of file mnote-olympus-tag.c.
References _, bindtextdomain, description, table, and tag.
Referenced by exif_mnote_data_olympus_get_description().
mnote_olympus_tag_get_name()
const char* mnote_olympus_tag_get_name (MnoteOlympusTag tag)
Return a textual name of the given tag within the Olympus-style MakerNote.
The name is a short, unique, non-localized text string containing only US-ASCII alphanumeric characters.
Parameters
[in] tag Olympus-style MakerNote tag
Returns
textual name of the tag, or NULL if the tag is unknown
Definition at line 229 of file mnote-olympus-tag.c.
References name, table, and tag.
Referenced by exif_mnote_data_olympus_get_name(), and exif_mnote_data_olympus_load().
mnote_olympus_tag_get_title()
const char* mnote_olympus_tag_get_title (MnoteOlympusTag tag)
Return a textual title of the given tag within the Olympus-style MakerNote.
The title is a short, localized description of the tag.
Parameters
[in] tag Olympus-style MakerNote tag
Returns
textual title of the tag, or NULL if the tag is unknown
Definition at line 239 of file mnote-olympus-tag.c.
References _, bindtextdomain, table, tag, and title.
Referenced by exif_mnote_data_olympus_get_title().
libexif Generated by