EXIF library (libexif) Internals: _ExifMnoteDataMethods Struct Reference
_ExifMnoteDataMethods Struct Reference
#include <exif-mnote-data-priv.h>
Data Fields
void(* free)(ExifMnoteData *)
void(* save)(ExifMnoteData *, unsigned char **, unsigned int *)
void(* load)(ExifMnoteData *, const unsigned char *, unsigned int)
void(* set_offset)(ExifMnoteData *, unsigned int)
void(* set_byte_order)(ExifMnoteData *, ExifByteOrder)
unsigned int(* count)(ExifMnoteData *)
unsigned int(* get_id)(ExifMnoteData *, unsigned int)
const char *(* get_name)(ExifMnoteData *, unsigned int)
const char *(* get_title)(ExifMnoteData *, unsigned int)
const char *(* get_description)(ExifMnoteData *, unsigned int)
char *(* get_value)(ExifMnoteData *, unsigned int, char *val, unsigned int maxlen)
Detailed Description
Definition at line 38 of file exif-mnote-data-priv.h.
Field Documentation
count
unsigned int(* _ExifMnoteDataMethods::count) (ExifMnoteData *)
Definition at line 50 of file exif-mnote-data-priv.h.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_count(), exif_mnote_data_fuji_new(), exif_mnote_data_olympus_new(), and exif_mnote_data_pentax_new().
free
void(* _ExifMnoteDataMethods::free) (ExifMnoteData *)
Definition at line 41 of file exif-mnote-data-priv.h.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_free(), exif_mnote_data_fuji_new(), exif_mnote_data_olympus_new(), and exif_mnote_data_pentax_new().
get_description
const char *(* _ExifMnoteDataMethods::get_description) (ExifMnoteData *, unsigned int)
Definition at line 54 of file exif-mnote-data-priv.h.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_fuji_new(), exif_mnote_data_get_description(), exif_mnote_data_olympus_new(), and exif_mnote_data_pentax_new().
get_id
unsigned int(* _ExifMnoteDataMethods::get_id) (ExifMnoteData *, unsigned int)
Definition at line 51 of file exif-mnote-data-priv.h.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_fuji_new(), exif_mnote_data_get_id(), exif_mnote_data_olympus_new(), and exif_mnote_data_pentax_new().
get_name
const char *(* _ExifMnoteDataMethods::get_name) (ExifMnoteData *, unsigned int)
Definition at line 52 of file exif-mnote-data-priv.h.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_fuji_new(), exif_mnote_data_get_name(), exif_mnote_data_olympus_new(), and exif_mnote_data_pentax_new().
get_title
const char *(* _ExifMnoteDataMethods::get_title) (ExifMnoteData *, unsigned int)
Definition at line 53 of file exif-mnote-data-priv.h.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_fuji_new(), exif_mnote_data_get_title(), exif_mnote_data_olympus_new(), and exif_mnote_data_pentax_new().
get_value
char *(* _ExifMnoteDataMethods::get_value) (ExifMnoteData *, unsigned int, char *val, unsigned int maxlen)
Definition at line 55 of file exif-mnote-data-priv.h.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_fuji_new(), exif_mnote_data_get_value(), exif_mnote_data_olympus_new(), and exif_mnote_data_pentax_new().
load
void(* _ExifMnoteDataMethods::load) (ExifMnoteData *, const unsigned char *, unsigned int)
Definition at line 45 of file exif-mnote-data-priv.h.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_fuji_new(), exif_mnote_data_load(), exif_mnote_data_olympus_new(), and exif_mnote_data_pentax_new().
save
void(* _ExifMnoteDataMethods::save) (ExifMnoteData *, unsigned char **, unsigned int *)
Definition at line 44 of file exif-mnote-data-priv.h.
Referenced by exif_mnote_data_canon_new(), exif_mnote_data_fuji_new(), exif_mnote_data_olympus_new(), exif_mnote_data_pentax_new(), and exif_mnote_data_save().
set_byte_order
void(* _ExifMnoteDataMethods::set_byte_order) (ExifMnoteData *, ExifByteOrder)
Definition at line 47 of file exif-mnote-data-priv.h.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_fuji_new(), exif_mnote_data_olympus_new(), exif_mnote_data_pentax_new(), and exif_mnote_data_set_byte_order().
set_offset
void(* _ExifMnoteDataMethods::set_offset) (ExifMnoteData *, unsigned int)
Definition at line 46 of file exif-mnote-data-priv.h.
Referenced by exif_mnote_data_apple_new(), exif_mnote_data_canon_new(), exif_mnote_data_fuji_new(), exif_mnote_data_olympus_new(), exif_mnote_data_pentax_new(), and exif_mnote_data_set_offset().
The documentation for this struct was generated from the following file:
libexif/exif-mnote-data-priv.h
libexif Generated by