EXIF library (libexif) Internals: test/test-fuzzer.c File Reference
test-fuzzer.c File Reference
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include "libexif/exif-data.h"
#include "libexif/exif-loader.h"
#include "libexif/exif-system.h"
Functions
void content_foreach_func (ExifEntry *entry, void *callback_data)
Completely parse all files given on the command line.
void content_foreach_func (ExifEntry *entry, void *UNUSED(callback_data))
void data_foreach_func (ExifContent *content, void *callback_data)
static int test_exif_data (ExifData *d)
static void test_parse (const char *filename, void *callback_data)
int main (const int argc, const char *argv[])
Function Documentation
content_foreach_func() [1/2]
void content_foreach_func (ExifEntry * entry, void * callback_data)
Completely parse all files given on the command line.
file test-fuzzer.c from test-parse.c and test-mnote.c
Copyright (C) 2007 Hans Ulrich Niedermann gp@n-.nosp@m.dime.nosp@m.nsion.nosp@m.al.d.nosp@m.e Copyright 2002 Lutz Mueller lutz@.nosp@m.user.nosp@m.s.sou.nosp@m.rcef.nosp@m.orge..nosp@m.net
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. Callback function handling an ExifEntry.
Referenced by data_foreach_func().
content_foreach_func() [2/2]
void content_foreach_func (ExifEntry * entry, void * UNUSEDcallback_data)
Definition at line 49 of file test-fuzzer.c.
References exif_entry_get_value(), exif_format_get_name(), exif_tag_get_name(), _ExifEntry::format, and _ExifEntry::tag.
data_foreach_func()
void data_foreach_func (ExifContent * content, void * callback_data)
Callback function handling an ExifContent (corresponds 1:1 to an IFD).
Definition at line 65 of file test-fuzzer.c.
References content_foreach_func(), exif_content_foreach_entry(), and exif_content_get_ifd().
Referenced by test_parse().
main()
int main (const int argc, const char * argv[])
Main program.
Definition at line 161 of file test-fuzzer.c.
References test_parse().
test_exif_data()
static int test_exif_data (ExifData * d) static
Definition at line 71 of file test-fuzzer.c.
References exif_byte_order_get_name(), exif_data_get_byte_order(), exif_data_get_mnote_data(), exif_mnote_data_count(), exif_mnote_data_get_description(), exif_mnote_data_get_name(), exif_mnote_data_get_title(), exif_mnote_data_get_value(), exif_mnote_data_ref(), exif_mnote_data_unref(), and name.
Referenced by test_parse().
test_parse()
static void test_parse (const char * filename, void * callback_data) static
Run EXIF parsing test on the given file.
Definition at line 105 of file test-fuzzer.c.
References data_foreach_func(), EXIF_BYTE_ORDER_INTEL, exif_data_foreach_content(), exif_data_log(), exif_data_new_from_file(), exif_data_save_data(), exif_data_set_byte_order(), exif_data_unref(), exif_loader_get_data(), exif_loader_new(), exif_loader_unref(), exif_loader_write(), exif_log_new(), exif_log_set_func(), and test_exif_data().
Referenced by main().
libexif Generated by