EXIF library (libexif) Internals: test/test-mem.c File Reference
test-mem.c File Reference
#include <config.h>
#include <libexif/exif-data.h>
#include <libexif/exif-ifd.h>
#include <libexif/exif-loader.h>
#include <stdio.h>
#include <stdlib.h>
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 33 of file test-mem.c.
References _ExifData::data, exif_data_dump(), exif_data_fix(), exif_data_new(), exif_data_save_data(), exif_data_set_data_type(), EXIF_DATA_TYPE_UNCOMPRESSED_CHUNKY, exif_data_unref(), exif_loader_get_data(), exif_loader_new(), exif_loader_unref(), exif_loader_write(), _ExifData::size, and size.
libexif Generated by