EXIF library (libexif) Internals: test/test-sorted.c File Reference
test
test-sorted.c File Reference
#include <libexif/exif-tag.h>
#include <stdio.h>
Functions
int main (void)
Function Documentation
int main (void)
Definition at line 29 of file test-sorted.c.
References exif_tag_table_count(), exif_tag_table_get_name(), and exif_tag_table_get_tag().
Generated by