EXIF library (libexif) Internals: test/test-tagtable.c File Reference
test-tagtable.c File Reference
#include "config.h"
#include <libexif/exif-tag.h>
#include <stdio.h>
#include <string.h>
Macros
#define VALIDATE(s) if (!(s)) {printf("Test %s FAILED\n", #s); fail=1;}
#define TESTBLOCK(t)
Functions
static int support_level (void)
static int name (void)
int main ()
Macro Definition Documentation
TESTBLOCK
#define TESTBLOCK (t)
Value:
{int rc = (t); fail |= rc; \
                      if (rc) printf("%s tests FAILED\n", #t);}
Definition at line 30 of file test-tagtable.c.
Referenced by main().
VALIDATE
#define VALIDATE (s) if (!(s)) {printf("Test %s FAILED\n", #s); fail=1;}
Definition at line 28 of file test-tagtable.c.
Referenced by name(), and support_level().
Function Documentation
main()
int main (void)
Definition at line 212 of file test-tagtable.c.
References name(), support_level(), and TESTBLOCK.
name()
static int name (void) static
Definition at line 172 of file test-tagtable.c.
References EXIF_IFD_0, EXIF_IFD_COUNT, EXIF_IFD_GPS, EXIF_IFD_INTEROPERABILITY, EXIF_TAG_EXIF_VERSION, exif_tag_get_name_in_ifd(), EXIF_TAG_GPS_LATITUDE_REF, EXIF_TAG_GPS_VERSION_ID, EXIF_TAG_INTEROPERABILITY_INDEX, and VALIDATE.
Referenced by main().
support_level()
static int support_level (void) static
Definition at line 34 of file test-tagtable.c.
References EXIF_DATA_TYPE_COMPRESSED, EXIF_DATA_TYPE_UNCOMPRESSED_CHUNKY, EXIF_DATA_TYPE_UNCOMPRESSED_PLANAR, EXIF_DATA_TYPE_UNCOMPRESSED_YCC, EXIF_DATA_TYPE_UNKNOWN, EXIF_IFD_0, EXIF_IFD_1, EXIF_IFD_COUNT, EXIF_IFD_EXIF, EXIF_IFD_GPS, EXIF_IFD_INTEROPERABILITY, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_UNKNOWN, EXIF_TAG_DOCUMENT_NAME, EXIF_TAG_EXIF_VERSION, exif_tag_get_support_level_in_ifd(), EXIF_TAG_GPS_LATITUDE_REF, EXIF_TAG_GPS_VERSION_ID, EXIF_TAG_INTEROPERABILITY_INDEX, EXIF_TAG_PLANAR_CONFIGURATION, EXIF_TAG_YCBCR_POSITIONING, and VALIDATE.
Referenced by main().
libexif Generated by