EXIF library (libexif) Internals: test/test-gps.c File Reference
test-gps.c File Reference
#include <libexif/exif-utils.h>
#include <libexif/exif-data.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
Functions
static int check_entry_format (ExifEntry *e)
int main (void)
Variables
static const uint16_t test_tags []
Function Documentation
check_entry_format()
static int check_entry_format (ExifEntry * e) static
Definition at line 77 of file test-gps.c.
References _ExifEntry::components, _ExifEntry::data, EXIF_FORMAT_ASCII, exif_format_get_size(), EXIF_FORMAT_UNDEFINED, EXIF_TAG_GPS_H_POSITIONING_ERROR, _ExifEntry::format, _ExifEntry::size, and _ExifEntry::tag.
Referenced by main().
main()
int main (void)
Definition at line 116 of file test-gps.c.
References check_entry_format(), exif_content_add_entry(), exif_content_remove_entry(), exif_data_new(), exif_data_unref(), exif_entry_initialize(), exif_entry_new(), exif_entry_unref(), EXIF_IFD_GPS, _ExifData::ifd, and test_tags.
Variable Documentation
test_tags
const uint16_t test_tags[] static
Definition at line 37 of file test-gps.c.
Referenced by main().
libexif Generated by