EXIF library (libexif) Internals: test/test-value.c File Reference
test-value.c File Reference
#include <libexif/exif-utils.h>
#include <libexif/exif-data.h>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static void check_entry_trunc (ExifEntry *e, int uniform)
int main (void)
Variables
static const ExifTag trunc_test_tags []
static const ExifTag nonuniform_test_tags []
static const ExifTag rational_test_tags []
Function Documentation
check_entry_trunc()
static void check_entry_trunc (ExifEntry * e, int uniform) static
Definition at line 94 of file test-value.c.
References exif_entry_get_value(), and _ExifEntry::tag.
Referenced by main().
main()
int main (void)
Definition at line 120 of file test-value.c.
References check_entry_trunc(), _ExifEntry::components, _ExifEntry::data, exif_content_add_entry(), exif_content_remove_entry(), exif_data_get_byte_order(), exif_data_new(), exif_data_unref(), exif_entry_fix(), exif_entry_initialize(), exif_entry_new(), exif_entry_new_mem(), exif_entry_unref(), EXIF_FORMAT_BYTE, exif_format_get_size(), EXIF_FORMAT_RATIONAL, EXIF_FORMAT_SHORT, EXIF_FORMAT_UNDEFINED, EXIF_IFD_0, EXIF_IFD_GPS, EXIF_IFD_INTEROPERABILITY, exif_mem_alloc(), exif_mem_new_default(), exif_mem_unref(), exif_set_rational(), exif_set_short(), exif_set_srational(), EXIF_TAG_GPS_ALTITUDE_REF, EXIF_TAG_GPS_TIME_STAMP, EXIF_TAG_GPS_VERSION_ID, EXIF_TAG_INTEROPERABILITY_VERSION, EXIF_TAG_SUB_SEC_TIME, EXIF_TAG_SUBJECT_AREA, EXIF_TAG_USER_COMMENT, EXIF_TAG_XP_COMMENT, _ExifEntry::format, _ExifData::ifd, nonuniform_test_tags, rational_test_tags, _ExifEntry::size, and trunc_test_tags.
Variable Documentation
nonuniform_test_tags
const ExifTag nonuniform_test_tags[] static
Initial value:
= {
        EXIF_TAG_RESOLUTION_UNIT,
        EXIF_TAG_COLOR_SPACE,
        EXIF_TAG_METERING_MODE,
}
Definition at line 66 of file test-value.c.
Referenced by main().
rational_test_tags
const ExifTag rational_test_tags[] static
Initial value:
= {
        EXIF_TAG_FNUMBER,
        EXIF_TAG_APERTURE_VALUE,
        EXIF_TAG_MAX_APERTURE_VALUE,
        EXIF_TAG_FOCAL_LENGTH,
        EXIF_TAG_SUBJECT_DISTANCE,
        EXIF_TAG_EXPOSURE_TIME,
        EXIF_TAG_SHUTTER_SPEED_VALUE,
        EXIF_TAG_BRIGHTNESS_VALUE,
        EXIF_TAG_EXPOSURE_BIAS_VALUE,
}
Definition at line 77 of file test-value.c.
Referenced by main().
trunc_test_tags
const ExifTag trunc_test_tags[] static
Initial value:
= {
        EXIF_TAG_PIXEL_X_DIMENSION,
        EXIF_TAG_SUBJECT_LOCATION,
        EXIF_TAG_IMAGE_WIDTH,
        EXIF_TAG_ORIENTATION,
        EXIF_TAG_SAMPLES_PER_PIXEL,
        EXIF_TAG_BITS_PER_SAMPLE,
        EXIF_TAG_X_RESOLUTION,
        EXIF_TAG_WHITE_POINT,
        EXIF_TAG_REFERENCE_BLACK_WHITE,
        EXIF_TAG_DATE_TIME,
        EXIF_TAG_IMAGE_DESCRIPTION,
        EXIF_TAG_EXIF_VERSION,
        EXIF_TAG_FLASH_PIX_VERSION,
        EXIF_TAG_COPYRIGHT,
        EXIF_TAG_FILE_SOURCE,
        EXIF_TAG_COMPONENTS_CONFIGURATION,
        EXIF_TAG_SCENE_TYPE,
        EXIF_TAG_YCBCR_SUB_SAMPLING,
        EXIF_TAG_PLANAR_CONFIGURATION,
}
Definition at line 40 of file test-value.c.
Referenced by main().
libexif Generated by