EXIF library (libexif) Internals: test/test-extract.c File Reference
test-extract.c File Reference
Extract EXIF data from a file and write it to another file.
#include "libexif/exif-data.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
Functions
int main (const int argc, const char *argv[])
Variables
static const unsigned char header [4] = {'\xff', '\xd8', '\xff', '\xe1'}
Detailed Description
Extract EXIF data from a file and write it to another file.
Copyright (C) 2019 Dan Fandrich dan@c.nosp@m.oneh.nosp@m.arves.nosp@m.ters.nosp@m..com
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
SPDX-License-Identifier: LGPL-2.0-or-later
Definition in file test-extract.c.
Function Documentation
main()
int main (const int argc, const char * argv[])
Definition at line 33 of file test-extract.c.
References EXIF_BYTE_ORDER_MOTOROLA, exif_data_new_from_file(), exif_data_save_data(), exif_data_unref(), exif_set_short(), and header.
Variable Documentation
header
const unsigned char header[4] = {'\xff', '\xd8', '\xff', '\xe1'} static
Definition at line 31 of file test-extract.c.
Referenced by main().
libexif Generated by