EXIF library (libexif) Internals: test/test-null.c File Reference
test-null.c File Reference
Pass NULL values into libexif APIs and ensure it doesn't crash.
#include "libexif/exif-data.h"
#include "libexif/exif-entry.h"
#include "libexif/exif-loader.h"
#include "libexif/exif-mnote-data.h"
#include <stdio.h>
#include <stdlib.h>
Functions
static void loader_null_test (void)
static void data_null_test (void)
static void content_null_test (void)
static void entry_null_test (void)
static void mnote_null_test (void)
static void log_null_test (void)
int main (void)
Detailed Description
Pass NULL values into libexif APIs and ensure it doesn't crash.
Copyright (C) 2019 Dan Fandrich dan@c.nosp@m.oneh.nosp@m.arves.nosp@m.ters.nosp@m..com
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
SPDX-License-Identifier: LGPL-2.0-or-later
Definition in file test-null.c.
Function Documentation
content_null_test()
static void content_null_test (void) static
Definition at line 171 of file test-null.c.
References exif_content_add_entry(), exif_content_dump(), exif_content_fix(), exif_content_foreach_entry(), exif_content_free(), exif_content_get_entry(), exif_content_get_ifd(), exif_content_log(), exif_content_new(), exif_content_new_mem(), exif_content_ref(), exif_content_remove_entry(), exif_content_unref(), and EXIF_TAG_COMPRESSION.
Referenced by main().
data_null_test()
static void data_null_test (void) static
Definition at line 94 of file test-null.c.
References EXIF_BYTE_ORDER_MOTOROLA, exif_data_dump(), exif_data_fix(), exif_data_foreach_content(), exif_data_get_byte_order(), exif_data_get_data_type(), exif_data_get_mnote_data(), exif_data_load_data(), exif_data_log(), exif_data_new(), exif_data_new_from_data(), exif_data_new_mem(), EXIF_DATA_OPTION_FOLLOW_SPECIFICATION, exif_data_ref(), exif_data_save_data(), exif_data_set_byte_order(), exif_data_set_data_type(), exif_data_set_option(), EXIF_DATA_TYPE_UNCOMPRESSED_CHUNKY, exif_data_unref(), and exif_data_unset_option().
Referenced by main().
entry_null_test()
static void entry_null_test (void) static
Definition at line 222 of file test-null.c.
References exif_content_get_entry(), exif_data_fix(), exif_data_new(), exif_data_unref(), exif_entry_dump(), exif_entry_fix(), exif_entry_free(), exif_entry_get_value(), exif_entry_initialize(), exif_entry_new_mem(), exif_entry_ref(), exif_entry_unref(), EXIF_IFD_0, EXIF_TAG_COMPRESSION, EXIF_TAG_X_RESOLUTION, and _ExifData::ifd.
Referenced by main().
loader_null_test()
static void loader_null_test (void) static
Definition at line 32 of file test-null.c.
References exif_loader_get_buf(), exif_loader_get_data(), exif_loader_log(), exif_loader_new(), exif_loader_new_mem(), exif_loader_ref(), exif_loader_reset(), exif_loader_unref(), exif_loader_write(), and exif_loader_write_file().
Referenced by main().
log_null_test()
static void log_null_test (void) static
Definition at line 307 of file test-null.c.
References exif_log(), EXIF_LOG_CODE_CORRUPT_DATA, exif_log_free(), exif_log_new(), exif_log_new_mem(), exif_log_ref(), exif_log_set_func(), exif_log_unref(), and exif_logv().
Referenced by main().
main()
int main (void)
Definition at line 341 of file test-null.c.
References content_null_test(), data_null_test(), entry_null_test(), loader_null_test(), log_null_test(), and mnote_null_test().
mnote_null_test()
static void mnote_null_test (void) static
Definition at line 277 of file test-null.c.
References exif_mnote_data_count(), exif_mnote_data_get_description(), exif_mnote_data_get_id(), exif_mnote_data_get_name(), exif_mnote_data_get_title(), exif_mnote_data_get_value(), exif_mnote_data_load(), exif_mnote_data_log(), exif_mnote_data_ref(), exif_mnote_data_save(), and exif_mnote_data_unref().
Referenced by main().
libexif Generated by