EXIF library (libexif) Internals: test/test-mnote.c File Reference
test-mnote.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <libexif/exif-data.h>
Functions
static int test_exif_data (ExifData *d)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 71 of file test-mnote.c.
References exif_data_new_from_data(), exif_data_new_from_file(), exif_data_save_data(), exif_data_unref(), and test_exif_data().
test_exif_data()
static int test_exif_data (ExifData * d) static
Definition at line 29 of file test-mnote.c.
References exif_byte_order_get_name(), exif_data_get_byte_order(), exif_data_get_mnote_data(), exif_data_unref(), exif_mnote_data_count(), exif_mnote_data_get_description(), exif_mnote_data_get_name(), exif_mnote_data_get_title(), exif_mnote_data_get_value(), exif_mnote_data_ref(), and exif_mnote_data_unref().
Referenced by main().
libexif Generated by