EXIF library (libexif) Internals: test/nls/test-codeset.c File Reference
test-codeset.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <i18n.h>
#include <langinfo.h>
#include <libintl.h>
Data Structures
struct TestCase
Functions
static int my_streq (const char *va, const char *vb)
static int check (const int i)
static int checks ()
int main (int argc, char *argv[])
Variables
const TestCase testcases []
Function Documentation
check()
static int check (const int i) static
Definition at line 71 of file test-codeset.c.
References bind_textdomain_codeset, gettext, TestCase::latin1, my_streq(), TestCase::orig, textdomain, and TestCase::utf8.
Referenced by checks().
checks()
static int checks () static
Definition at line 133 of file test-codeset.c.
References bindtextdomain, check(), and TestCase::locale.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 178 of file test-codeset.c.
References checks(), and TestCase::locale.
my_streq()
static int my_streq (const char * va, const char * vb) static
Definition at line 12 of file test-codeset.c.
Referenced by check().
Variable Documentation
testcases
const TestCase testcases[]
Initial value:
= {
        { "de_DE",
          N_("High saturation"),
          "Hohe S\344ttigung",
          "Hohe S\303\244ttigung" },
        { "fr_FR",
          N_("Not defined"),
          "Non d\233fini",
          "Non d\303\251fini"
        },
        { "es_ES",
          N_("High saturation"),
          "Alta saturaci\363n",
          "Alta saturaci\303\263n"
        },
        { NULL, NULL, NULL, NULL }
}
Definition at line 46 of file test-codeset.c.
libexif Generated by